const fs = require('fs');
const path = require('path');

const dir = 'd:/02_PROJECTS/5_KAT JOURNEY/APP/src/locales';

const translations = {
  vi: {
    reportTitle: "BÁO CÁO CHUYẾN ĐI",
    footerNote: "KAT Journey — Bản tin & Tổng kết chuyến đi",
    page: "Trang",
    part1: "Phần 1 — Thông tin khái quát",
    tripName: "Tên chuyến đi",
    duration: "Thời gian",
    dayTrip: "Đi trong ngày",
    days: "ngày",
    nights: "đêm",
    location: "Địa điểm",
    status: "Trạng thái",
    description: "Mô tả",
    membersList: "Thành viên tham gia",
    member: "Thành viên",
    role: "Vai trò",
    phone: "Số điện thoại",
    prepProgress: "Tiến độ chuẩn bị",
    luggage: "Hành lý",
    todo: "Việc cần làm",
    totalExpense: "Tổng chi phí",
    part2: "Phần 2 — Lịch trình chi tiết",
    date: "Ngày",
    time: "Giờ",
    activity: "Hoạt động",
    noActivity: "Không có hoạt động nào.",
    part3: "Phần 3 — Chi tiết chi phí",
    type: "Loại",
    amount: "Số tiền",
    payer: "Người trả",
    note: "Ghi chú",
    noExpense: "Không có chi phí nào.",
    sharedExpense: "Chi tiêu chung",
    personalExpense: "Chi tiêu cá nhân",
    grandTotal: "Tổng cộng",
    part4: "Phần 4 — Chuẩn bị & Tài liệu",
    docType: "Loại giấy tờ",
    quantity: "Số lượng",
    numMembers: "Số lượng thành viên",
    completed: "Đã hoàn thành",
    notCompleted: "Chưa hoàn thành",
    upcoming: "Sắp diễn ra",
    ongoing: "Đang diễn ra",
    ended: "Đã kết thúc",
    adults: "Người lớn",
    children: "Trẻ em",
    infants: "Em bé",
    overview: "Tổng quan",
    itinerary: "Lịch trình",
    expenses: "Chi phí",
    prepAndDocs: "Chuẩn bị & Tài liệu"
  },
  en: {
    reportTitle: "TRIP REPORT",
    footerNote: "KAT Journey — Newsletter & Trip Summary",
    page: "Page",
    part1: "Part 1 — General Information",
    tripName: "Trip Name",
    duration: "Duration",
    dayTrip: "Day Trip",
    days: "days",
    nights: "nights",
    location: "Location",
    status: "Status",
    description: "Description",
    membersList: "Participating Members",
    member: "Member",
    role: "Role",
    phone: "Phone Number",
    prepProgress: "Preparation Progress",
    luggage: "Luggage",
    todo: "To-do List",
    totalExpense: "Total Expense",
    part2: "Part 2 — Detailed Itinerary",
    date: "Date",
    time: "Time",
    activity: "Activity",
    noActivity: "No activities.",
    part3: "Part 3 — Expense Details",
    type: "Type",
    amount: "Amount",
    payer: "Paid By",
    note: "Note",
    noExpense: "No expenses.",
    sharedExpense: "Shared Expenses",
    personalExpense: "Personal Expenses",
    grandTotal: "Grand Total",
    part4: "Part 4 — Preparation & Documents",
    docType: "Document Type",
    quantity: "Quantity",
    numMembers: "Number of Members",
    completed: "Completed",
    notCompleted: "Not Completed",
    upcoming: "Upcoming",
    ongoing: "Ongoing",
    ended: "Ended",
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    overview: "Overview",
    itinerary: "Itinerary",
    expenses: "Expenses",
    prepAndDocs: "Preparation & Docs"
  },
  es: {
    reportTitle: "INFORME DEL VIAJE",
    footerNote: "KAT Journey — Boletín y Resumen del Viaje",
    page: "Página",
    part1: "Parte 1 — Información General",
    tripName: "Nombre del Viaje",
    duration: "Duración",
    dayTrip: "Viaje de un Día",
    days: "días",
    nights: "noches",
    location: "Ubicación",
    status: "Estado",
    description: "Descripción",
    membersList: "Miembros Participantes",
    member: "Miembro",
    role: "Rol",
    phone: "Teléfono",
    prepProgress: "Progreso de Preparación",
    luggage: "Equipaje",
    todo: "Lista de Tareas",
    totalExpense: "Gasto Total",
    part2: "Parte 2 — Itinerario Detallado",
    date: "Fecha",
    time: "Hora",
    activity: "Actividad",
    noActivity: "No hay actividades.",
    part3: "Parte 3 — Detalles de Gastos",
    type: "Tipo",
    amount: "Monto",
    payer: "Pagado Por",
    note: "Nota",
    noExpense: "No hay gastos.",
    sharedExpense: "Gastos Compartidos",
    personalExpense: "Gastos Personales",
    grandTotal: "Total General",
    part4: "Parte 4 — Preparación y Documentos",
    docType: "Tipo de Documento",
    quantity: "Cantidad",
    numMembers: "Número de Miembros",
    completed: "Completado",
    notCompleted: "No Completado",
    upcoming: "Próximo",
    ongoing: "En Curso",
    ended: "Finalizado",
    adults: "Adultos",
    children: "Niños",
    infants: "Bebés",
    overview: "Resumen",
    itinerary: "Itinerario",
    expenses: "Gastos",
    prepAndDocs: "Preparación y Doc."
  },
  ja: {
    reportTitle: "旅行レポート",
    footerNote: "KAT Journey — 旅行の概要",
    page: "ページ",
    part1: "パート1 — 基本情報",
    tripName: "旅行名",
    duration: "期間",
    dayTrip: "日帰り旅行",
    days: "日",
    nights: "泊",
    location: "場所",
    status: "ステータス",
    description: "説明",
    membersList: "参加メンバー",
    member: "メンバー",
    role: "役割",
    phone: "電話番号",
    prepProgress: "準備の進捗",
    luggage: "荷物",
    todo: "やることリスト",
    totalExpense: "合計費用",
    part2: "パート2 — 詳細なスケジュール",
    date: "日付",
    time: "時間",
    activity: "アクティビティ",
    noActivity: "アクティビティはありません。",
    part3: "パート3 — 費用の詳細",
    type: "タイプ",
    amount: "金額",
    payer: "支払人",
    note: "メモ",
    noExpense: "費用はありません。",
    sharedExpense: "共通の費用",
    personalExpense: "個人的な費用",
    grandTotal: "総計",
    part4: "パート4 — 準備と書類",
    docType: "書類タイプ",
    quantity: "数量",
    numMembers: "メンバー数",
    completed: "完了",
    notCompleted: "未完了",
    upcoming: "近日",
    ongoing: "進行中",
    ended: "終了",
    adults: "大人",
    children: "子供",
    infants: "幼児",
    overview: "概要",
    itinerary: "スケジュール",
    expenses: "費用",
    prepAndDocs: "準備と書類"
  },
  zh: {
    reportTitle: "旅行报告",
    footerNote: "KAT Journey — 旅行总结",
    page: "页",
    part1: "第一部分 — 基本信息",
    tripName: "旅行名称",
    duration: "持续时间",
    dayTrip: "一日游",
    days: "天",
    nights: "晚",
    location: "地点",
    status: "状态",
    description: "描述",
    membersList: "参与成员",
    member: "成员",
    role: "角色",
    phone: "电话号码",
    prepProgress: "准备进度",
    luggage: "行李",
    todo: "待办事项",
    totalExpense: "总费用",
    part2: "第二部分 — 详细行程",
    date: "日期",
    time: "时间",
    activity: "活动",
    noActivity: "没有活动。",
    part3: "第三部分 — 费用明细",
    type: "类型",
    amount: "金额",
    payer: "支付者",
    note: "备注",
    noExpense: "没有费用。",
    sharedExpense: "共同费用",
    personalExpense: "个人费用",
    grandTotal: "总计",
    part4: "第四部分 — 准备和文件",
    docType: "文件类型",
    quantity: "数量",
    numMembers: "成员数量",
    completed: "已完成",
    notCompleted: "未完成",
    upcoming: "即将进行",
    ongoing: "进行中",
    ended: "已结束",
    adults: "成人",
    children: "儿童",
    infants: "婴儿",
    overview: "概览",
    itinerary: "行程",
    expenses: "费用",
    prepAndDocs: "准备和文件"
  },
  ko: {
    reportTitle: "여행 보고서",
    footerNote: "KAT Journey — 여행 요약",
    page: "페이지",
    part1: "파트 1 — 기본 정보",
    tripName: "여행 이름",
    duration: "기간",
    dayTrip: "당일 여행",
    days: "일",
    nights: "박",
    location: "장소",
    status: "상태",
    description: "설명",
    membersList: "참가 멤버",
    member: "멤버",
    role: "역할",
    phone: "전화번호",
    prepProgress: "준비 진행 상황",
    luggage: "수하물",
    todo: "할 일 목록",
    totalExpense: "총 비용",
    part2: "파트 2 — 상세 일정",
    date: "날짜",
    time: "시간",
    activity: "활동",
    noActivity: "활동이 없습니다.",
    part3: "파트 3 — 비용 세부사항",
    type: "유형",
    amount: "금액",
    payer: "결제자",
    note: "메모",
    noExpense: "비용이 없습니다.",
    sharedExpense: "공동 비용",
    personalExpense: "개인 비용",
    grandTotal: "총계",
    part4: "파트 4 — 준비 및 문서",
    docType: "문서 유형",
    quantity: "수량",
    numMembers: "멤버 수",
    completed: "완료됨",
    notCompleted: "미완료",
    upcoming: "예정됨",
    ongoing: "진행 중",
    ended: "종료됨",
    adults: "성인",
    children: "어린이",
    infants: "유아",
    overview: "개요",
    itinerary: "일정",
    expenses: "비용",
    prepAndDocs: "준비 및 문서"
  },
  fr: {
    reportTitle: "RAPPORT DE VOYAGE",
    footerNote: "KAT Journey — Résumé du Voyage",
    page: "Page",
    part1: "Partie 1 — Informations Générales",
    tripName: "Nom du Voyage",
    duration: "Durée",
    dayTrip: "Voyage d'un Jour",
    days: "jours",
    nights: "nuits",
    location: "Lieu",
    status: "Statut",
    description: "Description",
    membersList: "Membres Participants",
    member: "Membre",
    role: "Rôle",
    phone: "Téléphone",
    prepProgress: "Progression",
    luggage: "Bagages",
    todo: "À Faire",
    totalExpense: "Dépense Totale",
    part2: "Partie 2 — Itinéraire Détaillé",
    date: "Date",
    time: "Heure",
    activity: "Activité",
    noActivity: "Aucune activité.",
    part3: "Partie 3 — Détails des Dépenses",
    type: "Type",
    amount: "Montant",
    payer: "Payé Par",
    note: "Note",
    noExpense: "Aucune dépense.",
    sharedExpense: "Dépenses Partagées",
    personalExpense: "Dépenses Personnelles",
    grandTotal: "Total Général",
    part4: "Partie 4 — Préparation & Documents",
    docType: "Type de Document",
    quantity: "Quantité",
    numMembers: "Nombre de Membres",
    completed: "Terminé",
    notCompleted: "Non Terminé",
    upcoming: "À Venir",
    ongoing: "En Cours",
    ended: "Terminé",
    adults: "Adultes",
    children: "Enfants",
    infants: "Bébés",
    overview: "Aperçu",
    itinerary: "Itinéraire",
    expenses: "Dépenses",
    prepAndDocs: "Préparation & Doc."
  }
};

const otherLangs = ['de', 'it', 'pt', 'id', 'th'];
for (const l of otherLangs) {
  translations[l] = translations.en;
}

for (const lang in translations) {
  const p = path.join(dir, `${lang}.json`);
  if (fs.existsSync(p)) {
    let content = JSON.parse(fs.readFileSync(p, 'utf8'));
    content.export = { ...content.export, ...translations[lang] };
    fs.writeFileSync(p, JSON.stringify(content, null, 2));
  }
}

console.log("Injected export strings into locales.");
