import json
import os

translations = {
    "en": {
        "pageTitle": "Expenses",
        "pageSubtitle": "Track spending, payments, and splitting during the trip.",
        "addExpense": "Add Expense",
        "totalTrip": "Total Trip Expenses",
        "sharedTrip": "Shared Expenses",
        "personalExpense": "Personal Expenses",
        "avgPerGroup": "Avg / Group",
        "avgPerPerson": "Avg / Person",
        "noCompanion": "No companions yet",
        "byCategory": "Expenses by Category",
        "sharePerMember": "Share per Person/Group",
        "addCompanionStats": "Add companions to see statistics.",
        "addCompanionShare": "Add companions to see individual shares.",
        "expenseList": "Expense List",
        "noExpenses": "No expenses yet",
        "noExpensesDesc": "Log your meals, transport, and tickets to automatically balance expenses after the trip.",
        "deleteTitle": "Delete this expense?",
        "deleteDesc": "This expense will be removed from the trip. This action cannot be undone.",
        "deleteConfirm": "Delete Expense",
        "settlementTitle": "Balance Settlement",
        "settlementBalanced": "Everyone is settled up. No one owes anything.",
        "settlementAddCompanion": "Add companions to calculate contributions or refunds.",
        "settlementNoExpense": "No shared expenses to balance yet.",
        "groupLabel": "(Group: {{group}})",
        "unnamed": "Unnamed Expense",
        "splitPersonal": "Personal",
        "splitPerGroup": "By Group",
        "splitShared": "Shared",
        "paidByOf": "Owner: {{name}}",
        "paidByPay": "Paid by: {{name}}",
        "paidByNone": "Unassigned",
        "personalLabel": "Personal",
        "forNPeople": "(for {{count}} people)",
        "options": "Options",
        "edit": "Edit",
        "delete": "Delete",
        "editExpense": "Edit Expense",
        "amount": "Amount",
        "selectCurrency": "Select Currency",
        "vnd": "VND (Vietnamese Dong)",
        "exchangeRate": "Rate: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Please enter an amount greater than 0.",
        "errPayer": "Please select a payer.",
        "errCategory": "Please enter a category name.",
        "dateLabel": "Date",
        "descLabel": "Description",
        "descPlaceholder": "e.g., Taxi, lunch, tickets...",
        "payerLabel": "Paid By",
        "payerPlaceholder": "Select payer",
        "noCompanionWarn": "No companions in the trip yet. Add companions to calculate splitting.",
        "personalOwner": "Whose expense is this?",
        "personalPlaceholder": "Select companion (optional)",
        "advanced": "Advanced Details",
        "categoryLabel": "Category",
        "customCatLabel": "Custom Category Name *",
        "customCatPlaceholder": "e.g., Souvenirs, Bike rental",
        "linkTimeline": "Link to Timeline (Optional)",
        "noLink": "Do not link (General expense)",
        "splitMethod": "Split Method",
        "splitSharedGroup": "Shared in group",
        "splitPersonalSelf": "Pay for self",
        "allPeople": "Everyone",
        "nParticipants": "{{count}} participants",
        "participateAll": "All",
        "participateN": "{{count}} people",
        "participate": "Participants",
        "close": "Close",
        "reselectAll": "Reselect All",
        "perPerson": "Per Person",
        "perGroup": "Per Family",
        "save": "Save",
        "add": "Add",
        "toastUpdated": "Expense updated",
        "toastAdded": "Expense added",
        "noCatYet": "No expense categories yet.",
        "noSharedAnalysis": "No shared expenses to analyze.",
        "noExpenseAnalysis": "No expenses to analyze.",
        "noExpenseList": "No expenses in the list yet",
        "noCompanionShared": "No companions yet. Choose \"Pay for self\" or suggest adding companions.",
        "sharedSuggest": "Suggest expenses to share equally and settle later.",
        "suggestOption": "Suggestion Options",
        "paidBy": "Paid by:",
        "savingNew": "Saving...",
        "suggestNew": "New Suggestion",
        "savingEdit": "Saving...",
        "suggestEdit": "Edit Suggestion",
        "deletingSugg": "Deleting...",
        "suggestDelete": "Delete Suggestion",
        "splitGroupLabel": "Shared in group",
        "personalSelfLabel": "Pay for self"
    },
    "es": {
        "pageTitle": "Gastos",
        "pageSubtitle": "Rastrea gastos, pagos y divisiones durante el viaje.",
        "addExpense": "Añadir Gasto",
        "totalTrip": "Gastos Totales del Viaje",
        "sharedTrip": "Gastos Compartidos",
        "personalExpense": "Gastos Personales",
        "avgPerGroup": "Prom. / Grupo",
        "avgPerPerson": "Prom. / Persona",
        "noCompanion": "Aún no hay compañeros",
        "byCategory": "Gastos por Categoría",
        "sharePerMember": "Cuota por Persona/Grupo",
        "addCompanionStats": "Añade compañeros para ver estadísticas.",
        "addCompanionShare": "Añade compañeros para ver la parte de cada uno.",
        "expenseList": "Lista de Gastos",
        "noExpenses": "Aún no hay gastos",
        "noExpensesDesc": "Registra comidas, transporte y entradas para equilibrar automáticamente tras el viaje.",
        "deleteTitle": "¿Eliminar este gasto?",
        "deleteDesc": "Este gasto se eliminará del viaje. No se puede deshacer.",
        "deleteConfirm": "Eliminar Gasto",
        "settlementTitle": "Equilibrio de Cuentas",
        "settlementBalanced": "Todos están al día. Nadie debe nada.",
        "settlementAddCompanion": "Añade compañeros para calcular aportes o reembolsos.",
        "settlementNoExpense": "No hay gastos compartidos para equilibrar aún.",
        "groupLabel": "(Grupo: {{group}})",
        "unnamed": "Gasto sin nombre",
        "splitPersonal": "Personal",
        "splitPerGroup": "Por Grupo",
        "splitShared": "Compartido",
        "paidByOf": "Dueño: {{name}}",
        "paidByPay": "Pagado por: {{name}}",
        "paidByNone": "No asignado",
        "personalLabel": "Personal",
        "forNPeople": "(para {{count}} personas)",
        "options": "Opciones",
        "edit": "Editar",
        "delete": "Eliminar",
        "editExpense": "Editar Gasto",
        "amount": "Monto",
        "selectCurrency": "Seleccionar Moneda",
        "vnd": "VND (Dong Vietnamita)",
        "exchangeRate": "Tasa: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Ingresa un monto mayor a 0.",
        "errPayer": "Selecciona un pagador.",
        "errCategory": "Ingresa un nombre de categoría.",
        "dateLabel": "Fecha",
        "descLabel": "Descripción",
        "descPlaceholder": "Ej: Taxi, almuerzo, entradas...",
        "payerLabel": "Pagado por",
        "payerPlaceholder": "Seleccionar pagador",
        "noCompanionWarn": "Sin compañeros en el viaje aún. Añade para calcular la división.",
        "personalOwner": "¿De quién es este gasto?",
        "personalPlaceholder": "Seleccionar compañero (opcional)",
        "advanced": "Detalles Avanzados",
        "categoryLabel": "Categoría",
        "customCatLabel": "Nombre de Categoría *",
        "customCatPlaceholder": "Ej: Recuerdos, Alquiler de moto",
        "linkTimeline": "Vincular a Itinerario (Opcional)",
        "noLink": "No vincular (Gasto general)",
        "splitMethod": "Método de División",
        "splitSharedGroup": "Compartido en grupo",
        "splitPersonalSelf": "Paga por sí mismo",
        "allPeople": "Todos",
        "nParticipants": "{{count}} participantes",
        "participateAll": "Todos",
        "participateN": "{{count}} personas",
        "participate": "Participan",
        "close": "Cerrar",
        "reselectAll": "Reseleccionar Todos",
        "perPerson": "Por Persona",
        "perGroup": "Por Familia",
        "save": "Guardar",
        "add": "Añadir",
        "toastUpdated": "Gasto actualizado",
        "toastAdded": "Gasto añadido",
        "noCatYet": "Aún no hay categorías.",
        "noSharedAnalysis": "No hay gastos compartidos para analizar.",
        "noExpenseAnalysis": "No hay gastos para analizar.",
        "noExpenseList": "Aún no hay gastos en la lista",
        "noCompanionShared": "Sin compañeros aún. Elige \"Paga por sí mismo\" o sugiere añadir compañeros.",
        "sharedSuggest": "Sugiere gastos para compartir por igual y liquidar después.",
        "suggestOption": "Opciones de sugerencia",
        "paidBy": "Pagado por:",
        "savingNew": "Guardando...",
        "suggestNew": "Nueva Sugerencia",
        "savingEdit": "Guardando...",
        "suggestEdit": "Editar Sugerencia",
        "deletingSugg": "Eliminando...",
        "suggestDelete": "Eliminar Sugerencia",
        "splitGroupLabel": "Compartido en grupo",
        "personalSelfLabel": "Paga por sí mismo"
    }
}

for lang in ["en", "es"]:
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    if "expenses" not in data:
        data["expenses"] = {}
        
    for k, v in translations[lang].items():
        data["expenses"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
