import json
import os

# 12 Languages: vi, en, ja, ko, zh, th, fr, es, de, it, pt, id

# Wrapped (more.*) strings
wrapped_translations = {
    "vi": {
        "featureWrapped": "Tổng kết hành trình",
        "wrappedSubtitle": "Nhìn lại những dấu ấn đáng nhớ trong chuyến đi của bạn.",
        "wrappedExportPdf": "Xuất PDF",
        "wrappedExporting": "Đang xuất...",
        "wrappedDayTrip": "Chuyến đi trong ngày",
        "wrappedDays": "Ngày hành trình",
        "wrappedEvents": "Mục lịch trình",
        "wrappedPacking": "Hành lý",
        "wrappedJournals": "Bài viết",
        "wrappedExpenseTitle": "CHI PHÍ CHUYẾN ĐI",
        "wrappedTotalExpense": "Tổng chi phí",
        "wrappedSharedExpense": "Chi chung chuyến đi",
        "wrappedPersonalExpense": "Chi cá nhân",
        "wrappedTopPayer": "Nhà tài trợ chính",
        "wrappedTopPayerDesc": "là người chi nhiều nhất với",
        "wrappedNoMembersExpense": "Chưa có người đồng hành để gợi ý cân đối chia tiền.",
        "wrappedNoExpenseData": "Chưa có dữ liệu chi phí cho chuyến đi này.",
        "wrappedMoodTitle": "DẤU ẤN CẢM XÚC",
        "wrappedMoodDesc": "Cảm xúc chủ đạo được ghi nhận từ các bài viết trong bản tin hành trình của bạn.",
        "wrappedNoMoodData": "Chưa có đủ bài viết để tổng kết cảm xúc chuyến đi.",
        "wrappedNoMoodDesc": "Đăng thêm bản tin để lưu lại cảm xúc và khoảnh khắc đáng nhớ.",
        "wrappedPostFirstJournal": "Đăng bài viết đầu tiên",
        "wrappedFirstMoment": "Dấu ấn đầu tiên",
        "wrappedNoFirstMoment": "Chưa có dấu ấn đầu tiên. Hãy thêm hoạt động hoặc đăng bài viết để lưu lại khoảnh khắc mở đầu.",
        "wrappedFirstMomentEvent1": "Bạn đã bắt đầu với",
        "wrappedFirstMomentEvent2": "vào ngày",
        "wrappedFirstMomentJournal1": "Kỷ niệm đầu tiên được ghi lại vào ngày",
        "wrappedBusiestDay": "Ngày nổi bật nhất",
        "wrappedBusiestDayDesc": "là ngày bận rộn nhất với",
        "wrappedBusiestDayDesc2": "hoạt động được ghi nhận.",
        "wrappedNoBusiestDay": "Chưa có ngày nào đủ dữ liệu để chọn làm ngày nổi bật.",
        "wrappedLocations": "Điểm đến đã ghé qua",
        "wrappedNoLocations": "Chưa có điểm đến cụ thể nào trong lịch trình."
    },
    "en": {
        "featureWrapped": "Trip Summary",
        "wrappedSubtitle": "Look back at the memorable moments of your trip.",
        "wrappedExportPdf": "Export PDF",
        "wrappedExporting": "Exporting...",
        "wrappedDayTrip": "Day trip",
        "wrappedDays": "Trip Days",
        "wrappedEvents": "Timeline Events",
        "wrappedPacking": "Packing",
        "wrappedJournals": "Journals",
        "wrappedExpenseTitle": "TRIP EXPENSES",
        "wrappedTotalExpense": "Total Expense",
        "wrappedSharedExpense": "Shared Expense",
        "wrappedPersonalExpense": "Personal Expense",
        "wrappedTopPayer": "Top Spender",
        "wrappedTopPayerDesc": "is the top spender with",
        "wrappedNoMembersExpense": "No companions to suggest expense balancing.",
        "wrappedNoExpenseData": "No expense data for this trip yet.",
        "wrappedMoodTitle": "TRIP MOOD",
        "wrappedMoodDesc": "The primary mood recorded from the journals in your trip.",
        "wrappedNoMoodData": "Not enough journals to summarize trip mood.",
        "wrappedNoMoodDesc": "Post more journals to save emotions and memorable moments.",
        "wrappedPostFirstJournal": "Post first journal",
        "wrappedFirstMoment": "First Moment",
        "wrappedNoFirstMoment": "No first moment yet. Add an activity or post a journal to save the opening moment.",
        "wrappedFirstMomentEvent1": "You started with",
        "wrappedFirstMomentEvent2": "on",
        "wrappedFirstMomentJournal1": "The first memory was recorded on",
        "wrappedBusiestDay": "Busiest Day",
        "wrappedBusiestDayDesc": "is the busiest day with",
        "wrappedBusiestDayDesc2": "activities recorded.",
        "wrappedNoBusiestDay": "No day has enough data to be selected as the busiest day.",
        "wrappedLocations": "Locations Visited",
        "wrappedNoLocations": "No specific destinations in the itinerary yet."
    },
    "ja": {
        "featureWrapped": "旅行のまとめ",
        "wrappedSubtitle": "旅行の思い出に残る瞬間を振り返りましょう。",
        "wrappedExportPdf": "PDFをエクスポート",
        "wrappedExporting": "エクスポート中...",
        "wrappedDayTrip": "日帰り旅行",
        "wrappedDays": "旅行日数",
        "wrappedEvents": "タイムラインイベント",
        "wrappedPacking": "持ち物",
        "wrappedJournals": "日記",
        "wrappedExpenseTitle": "旅行の費用",
        "wrappedTotalExpense": "総費用",
        "wrappedSharedExpense": "共同費用",
        "wrappedPersonalExpense": "個人費用",
        "wrappedTopPayer": "最大の支出者",
        "wrappedTopPayerDesc": "は次の金額で最大の支出者です",
        "wrappedNoMembersExpense": "費用のバランスを提案する同伴者がいません。",
        "wrappedNoExpenseData": "この旅行の費用データはまだありません。",
        "wrappedMoodTitle": "旅行の気分",
        "wrappedMoodDesc": "旅行中の日記から記録された主な気分です。",
        "wrappedNoMoodData": "旅行の気分をまとめるのに十分な日記がありません。",
        "wrappedNoMoodDesc": "感情や思い出に残る瞬間を保存するために、さらに日記を投稿してください。",
        "wrappedPostFirstJournal": "最初の日記を投稿",
        "wrappedFirstMoment": "最初の瞬間",
        "wrappedNoFirstMoment": "まだ最初の瞬間がありません。アクティビティを追加するか日記を投稿して保存してください。",
        "wrappedFirstMomentEvent1": "次から始めました",
        "wrappedFirstMomentEvent2": "日付：",
        "wrappedFirstMomentJournal1": "最初の思い出が記録されました：",
        "wrappedBusiestDay": "最も忙しい日",
        "wrappedBusiestDayDesc": "は最も忙しい日で、",
        "wrappedBusiestDayDesc2": "のアクティビティが記録されています。",
        "wrappedNoBusiestDay": "最も忙しい日として選択するのに十分なデータがありません。",
        "wrappedLocations": "訪れた場所",
        "wrappedNoLocations": "予定表に具体的な目的地がまだありません。"
    },
    "th": {
        "featureWrapped": "สรุปการเดินทาง",
        "wrappedSubtitle": "มองย้อนกลับไปในช่วงเวลาที่น่าจดจำของการเดินทางของคุณ",
        "wrappedExportPdf": "ส่งออก PDF",
        "wrappedExporting": "กำลังส่งออก...",
        "wrappedDayTrip": "ทริปวันเดียว",
        "wrappedDays": "วันเดินทาง",
        "wrappedEvents": "กิจกรรม",
        "wrappedPacking": "สัมภาระ",
        "wrappedJournals": "บันทึก",
        "wrappedExpenseTitle": "ค่าใช้จ่ายการเดินทาง",
        "wrappedTotalExpense": "ค่าใช้จ่ายทั้งหมด",
        "wrappedSharedExpense": "ค่าใช้จ่ายส่วนรวม",
        "wrappedPersonalExpense": "ค่าใช้จ่ายส่วนตัว",
        "wrappedTopPayer": "ผู้ใช้จ่ายสูงสุด",
        "wrappedTopPayerDesc": "คือผู้ใช้จ่ายสูงสุดด้วยจำนวนเงิน",
        "wrappedNoMembersExpense": "ไม่มีเพื่อนร่วมทางที่จะแนะนำการแบ่งปันค่าใช้จ่าย",
        "wrappedNoExpenseData": "ยังไม่มีข้อมูลค่าใช้จ่ายสำหรับการเดินทางนี้",
        "wrappedMoodTitle": "อารมณ์การเดินทาง",
        "wrappedMoodDesc": "อารมณ์หลักที่บันทึกจากวารสารในการเดินทางของคุณ",
        "wrappedNoMoodData": "วารสารไม่เพียงพอที่จะสรุปอารมณ์การเดินทาง",
        "wrappedNoMoodDesc": "โพสต์วารสารเพิ่มเติมเพื่อบันทึกอารมณ์และช่วงเวลาที่น่าจดจำ",
        "wrappedPostFirstJournal": "โพสต์บันทึกแรก",
        "wrappedFirstMoment": "ช่วงเวลาแรก",
        "wrappedNoFirstMoment": "ยังไม่มีช่วงเวลาแรก เพิ่มกิจกรรมหรือโพสต์บันทึกเพื่อบันทึกช่วงเวลาเริ่มต้น",
        "wrappedFirstMomentEvent1": "คุณเริ่มต้นด้วย",
        "wrappedFirstMomentEvent2": "ในวันที่",
        "wrappedFirstMomentJournal1": "ความทรงจำแรกถูกบันทึกเมื่อ",
        "wrappedBusiestDay": "วันที่ยุ่งที่สุด",
        "wrappedBusiestDayDesc": "คือวันที่ยุ่งที่สุดด้วย",
        "wrappedBusiestDayDesc2": "กิจกรรมที่บันทึกไว้",
        "wrappedNoBusiestDay": "ไม่มีวันที่ข้อมูลเพียงพอที่จะเลือกเป็นวันที่ยุ่งที่สุด",
        "wrappedLocations": "สถานที่ที่ไปเยือน",
        "wrappedNoLocations": "ยังไม่มีจุดหมายปลายทางที่เฉพาะเจาะจงในกำหนดการเดินทาง"
    },
    "ko": {
        "featureWrapped": "여행 요약",
        "wrappedSubtitle": "여행의 기억에 남는 순간을 되돌아보세요.",
        "wrappedExportPdf": "PDF 내보내기",
        "wrappedExporting": "내보내는 중...",
        "wrappedDayTrip": "당일 여행",
        "wrappedDays": "여행 일수",
        "wrappedEvents": "일정 이벤트",
        "wrappedPacking": "수하물",
        "wrappedJournals": "일기",
        "wrappedExpenseTitle": "여행 경비",
        "wrappedTotalExpense": "총 경비",
        "wrappedSharedExpense": "공동 경비",
        "wrappedPersonalExpense": "개인 경비",
        "wrappedTopPayer": "최고 지출자",
        "wrappedTopPayerDesc": "가장 많은 지출을 한 사람:",
        "wrappedNoMembersExpense": "경비 배분을 제안할 동반자가 없습니다.",
        "wrappedNoExpenseData": "아직 이 여행에 대한 경비 데이터가 없습니다.",
        "wrappedMoodTitle": "여행 기분",
        "wrappedMoodDesc": "여행 일기에서 기록된 주요 기분입니다.",
        "wrappedNoMoodData": "여행 기분을 요약할 만큼 일기가 충분하지 않습니다.",
        "wrappedNoMoodDesc": "감정과 기억에 남는 순간을 저장하려면 일기를 더 게시하세요.",
        "wrappedPostFirstJournal": "첫 일기 게시",
        "wrappedFirstMoment": "첫 순간",
        "wrappedNoFirstMoment": "아직 첫 순간이 없습니다. 시작하는 순간을 저장하려면 활동을 추가하거나 일기를 게시하세요.",
        "wrappedFirstMomentEvent1": "다음으로 시작했습니다:",
        "wrappedFirstMomentEvent2": "날짜:",
        "wrappedFirstMomentJournal1": "첫 번째 기억이 기록된 날짜:",
        "wrappedBusiestDay": "가장 바쁜 날",
        "wrappedBusiestDayDesc": "가장 바쁜 날이며,",
        "wrappedBusiestDayDesc2": "개의 활동이 기록되었습니다.",
        "wrappedNoBusiestDay": "가장 바쁜 날로 선택하기에 충분한 데이터가 없습니다.",
        "wrappedLocations": "방문한 장소",
        "wrappedNoLocations": "아직 일정에 특정 목적지가 없습니다."
    },
    "zh": {
        "featureWrapped": "旅行总结",
        "wrappedSubtitle": "回顾您旅行中难忘的时刻。",
        "wrappedExportPdf": "导出 PDF",
        "wrappedExporting": "正在导出...",
        "wrappedDayTrip": "一日游",
        "wrappedDays": "旅行天数",
        "wrappedEvents": "行程事件",
        "wrappedPacking": "行李",
        "wrappedJournals": "日记",
        "wrappedExpenseTitle": "旅行费用",
        "wrappedTotalExpense": "总费用",
        "wrappedSharedExpense": "共同费用",
        "wrappedPersonalExpense": "个人费用",
        "wrappedTopPayer": "最大开销者",
        "wrappedTopPayerDesc": "是最大的开销者，金额为",
        "wrappedNoMembersExpense": "没有同伴可以建议费用平衡。",
        "wrappedNoExpenseData": "本次旅行暂无费用数据。",
        "wrappedMoodTitle": "旅行心情",
        "wrappedMoodDesc": "从您的旅行日记中记录的主要心情。",
        "wrappedNoMoodData": "没有足够的日记来总结旅行心情。",
        "wrappedNoMoodDesc": "发布更多日记以保存情感和难忘时刻。",
        "wrappedPostFirstJournal": "发布第一篇日记",
        "wrappedFirstMoment": "第一个瞬间",
        "wrappedNoFirstMoment": "还没有第一个瞬间。添加活动或发布日记以保存开始的时刻。",
        "wrappedFirstMomentEvent1": "您开始于",
        "wrappedFirstMomentEvent2": "在日期",
        "wrappedFirstMomentJournal1": "第一个记忆记录于",
        "wrappedBusiestDay": "最忙的一天",
        "wrappedBusiestDayDesc": "是最忙的一天，有",
        "wrappedBusiestDayDesc2": "个活动被记录。",
        "wrappedNoBusiestDay": "没有足够的数据选择最忙的一天。",
        "wrappedLocations": "访问的地点",
        "wrappedNoLocations": "行程中尚无具体目的地。"
    },
    "fr": {
        "featureWrapped": "Résumé du voyage",
        "wrappedSubtitle": "Revenez sur les moments mémorables de votre voyage.",
        "wrappedExportPdf": "Exporter en PDF",
        "wrappedExporting": "Exportation...",
        "wrappedDayTrip": "Excursion d'un jour",
        "wrappedDays": "Jours de voyage",
        "wrappedEvents": "Événements",
        "wrappedPacking": "Bagages",
        "wrappedJournals": "Journaux",
        "wrappedExpenseTitle": "DÉPENSES DU VOYAGE",
        "wrappedTotalExpense": "Dépense totale",
        "wrappedSharedExpense": "Dépenses partagées",
        "wrappedPersonalExpense": "Dépenses personnelles",
        "wrappedTopPayer": "Le plus grand dépensier",
        "wrappedTopPayerDesc": "est le plus grand dépensier avec",
        "wrappedNoMembersExpense": "Pas de compagnons pour suggérer un équilibre des dépenses.",
        "wrappedNoExpenseData": "Pas encore de données de dépenses pour ce voyage.",
        "wrappedMoodTitle": "HUMEUR DU VOYAGE",
        "wrappedMoodDesc": "L'humeur principale enregistrée à partir des journaux de votre voyage.",
        "wrappedNoMoodData": "Pas assez de journaux pour résumer l'humeur du voyage.",
        "wrappedNoMoodDesc": "Publiez plus de journaux pour conserver les émotions et les moments mémorables.",
        "wrappedPostFirstJournal": "Publier le premier journal",
        "wrappedFirstMoment": "Premier moment",
        "wrappedNoFirstMoment": "Pas encore de premier moment. Ajoutez une activité ou publiez un journal pour sauvegarder le moment de départ.",
        "wrappedFirstMomentEvent1": "Vous avez commencé avec",
        "wrappedFirstMomentEvent2": "le",
        "wrappedFirstMomentJournal1": "Le premier souvenir a été enregistré le",
        "wrappedBusiestDay": "Jour le plus chargé",
        "wrappedBusiestDayDesc": "est le jour le plus chargé avec",
        "wrappedBusiestDayDesc2": "activités enregistrées.",
        "wrappedNoBusiestDay": "Aucun jour n'a assez de données pour être le jour le plus chargé.",
        "wrappedLocations": "Lieux visités",
        "wrappedNoLocations": "Pas encore de destinations spécifiques dans l'itinéraire."
    },
    "es": {
        "featureWrapped": "Resumen del viaje",
        "wrappedSubtitle": "Recuerda los momentos memorables de tu viaje.",
        "wrappedExportPdf": "Exportar PDF",
        "wrappedExporting": "Exportando...",
        "wrappedDayTrip": "Excursión de un día",
        "wrappedDays": "Días de viaje",
        "wrappedEvents": "Eventos",
        "wrappedPacking": "Equipaje",
        "wrappedJournals": "Diarios",
        "wrappedExpenseTitle": "GASTOS DEL VIAJE",
        "wrappedTotalExpense": "Gasto Total",
        "wrappedSharedExpense": "Gastos compartidos",
        "wrappedPersonalExpense": "Gastos personales",
        "wrappedTopPayer": "Mayor gastador",
        "wrappedTopPayerDesc": "es el mayor gastador con",
        "wrappedNoMembersExpense": "No hay compañeros para sugerir un equilibrio de gastos.",
        "wrappedNoExpenseData": "Aún no hay datos de gastos para este viaje.",
        "wrappedMoodTitle": "ESTADO DE ÁNIMO DEL VIAJE",
        "wrappedMoodDesc": "El estado de ánimo principal registrado en los diarios de su viaje.",
        "wrappedNoMoodData": "No hay suficientes diarios para resumir el estado de ánimo.",
        "wrappedNoMoodDesc": "Publica más diarios para guardar emociones y momentos.",
        "wrappedPostFirstJournal": "Publicar el primer diario",
        "wrappedFirstMoment": "Primer momento",
        "wrappedNoFirstMoment": "Aún no hay primer momento. Añade una actividad o publica un diario.",
        "wrappedFirstMomentEvent1": "Empezaste con",
        "wrappedFirstMomentEvent2": "el",
        "wrappedFirstMomentJournal1": "El primer recuerdo se registró el",
        "wrappedBusiestDay": "Día más ocupado",
        "wrappedBusiestDayDesc": "es el día más ocupado con",
        "wrappedBusiestDayDesc2": "actividades registradas.",
        "wrappedNoBusiestDay": "Ningún día tiene suficientes datos para ser el más ocupado.",
        "wrappedLocations": "Lugares visitados",
        "wrappedNoLocations": "Aún no hay destinos específicos en el itinerario."
    },
    "de": {
        "featureWrapped": "Reisezusammenfassung",
        "wrappedSubtitle": "Blicken Sie auf die unvergesslichen Momente Ihrer Reise zurück.",
        "wrappedExportPdf": "PDF exportieren",
        "wrappedExporting": "Exportieren...",
        "wrappedDayTrip": "Tagesausflug",
        "wrappedDays": "Reisetage",
        "wrappedEvents": "Ereignisse",
        "wrappedPacking": "Gepäck",
        "wrappedJournals": "Tagebücher",
        "wrappedExpenseTitle": "REISEKOSTEN",
        "wrappedTotalExpense": "Gesamtkosten",
        "wrappedSharedExpense": "Geteilte Kosten",
        "wrappedPersonalExpense": "Persönliche Kosten",
        "wrappedTopPayer": "Größter Ausgeber",
        "wrappedTopPayerDesc": "ist der größte Ausgeber mit",
        "wrappedNoMembersExpense": "Keine Begleiter, um einen Kostenausgleich vorzuschlagen.",
        "wrappedNoExpenseData": "Noch keine Kostendaten für diese Reise.",
        "wrappedMoodTitle": "REISESTIMMUNG",
        "wrappedMoodDesc": "Die wichtigste Stimmung, die in den Tagebüchern Ihrer Reise erfasst wurde.",
        "wrappedNoMoodData": "Nicht genug Tagebücher, um die Reisestimmung zusammenzufassen.",
        "wrappedNoMoodDesc": "Veröffentlichen Sie mehr Tagebücher, um Emotionen und Momente zu speichern.",
        "wrappedPostFirstJournal": "Erstes Tagebuch posten",
        "wrappedFirstMoment": "Erster Moment",
        "wrappedNoFirstMoment": "Noch kein erster Moment. Fügen Sie eine Aktivität hinzu oder posten Sie ein Tagebuch.",
        "wrappedFirstMomentEvent1": "Sie begannen mit",
        "wrappedFirstMomentEvent2": "am",
        "wrappedFirstMomentJournal1": "Die erste Erinnerung wurde aufgezeichnet am",
        "wrappedBusiestDay": "Beschäftigtster Tag",
        "wrappedBusiestDayDesc": "ist der beschäftigtste Tag mit",
        "wrappedBusiestDayDesc2": "aufgezeichneten Aktivitäten.",
        "wrappedNoBusiestDay": "Kein Tag hat genug Daten, um als der beschäftigtste ausgewählt zu werden.",
        "wrappedLocations": "Besuchte Orte",
        "wrappedNoLocations": "Noch keine spezifischen Ziele im Reiseplan."
    },
    "it": {
        "featureWrapped": "Riepilogo viaggio",
        "wrappedSubtitle": "Ripercorri i momenti memorabili del tuo viaggio.",
        "wrappedExportPdf": "Esporta PDF",
        "wrappedExporting": "Esportazione...",
        "wrappedDayTrip": "Gita di un giorno",
        "wrappedDays": "Giorni di viaggio",
        "wrappedEvents": "Eventi",
        "wrappedPacking": "Bagagli",
        "wrappedJournals": "Diari",
        "wrappedExpenseTitle": "SPESE DI VIAGGIO",
        "wrappedTotalExpense": "Spesa Totale",
        "wrappedSharedExpense": "Spese condivise",
        "wrappedPersonalExpense": "Spese personali",
        "wrappedTopPayer": "Maggior spendaccione",
        "wrappedTopPayerDesc": "è il maggior spendaccione con",
        "wrappedNoMembersExpense": "Nessun compagno per suggerire il bilanciamento delle spese.",
        "wrappedNoExpenseData": "Ancora nessun dato sulle spese per questo viaggio.",
        "wrappedMoodTitle": "UMORE DEL VIAGGIO",
        "wrappedMoodDesc": "L'umore principale registrato dai diari del tuo viaggio.",
        "wrappedNoMoodData": "Non ci sono abbastanza diari per riassumere l'umore del viaggio.",
        "wrappedNoMoodDesc": "Pubblica più diari per salvare emozioni e momenti memorabili.",
        "wrappedPostFirstJournal": "Pubblica il primo diario",
        "wrappedFirstMoment": "Primo momento",
        "wrappedNoFirstMoment": "Ancora nessun primo momento. Aggiungi un'attività o pubblica un diario.",
        "wrappedFirstMomentEvent1": "Hai iniziato con",
        "wrappedFirstMomentEvent2": "il",
        "wrappedFirstMomentJournal1": "Il primo ricordo è stato registrato il",
        "wrappedBusiestDay": "Giorno più impegnativo",
        "wrappedBusiestDayDesc": "è il giorno più impegnativo con",
        "wrappedBusiestDayDesc2": "attività registrate.",
        "wrappedNoBusiestDay": "Nessun giorno ha abbastanza dati per essere scelto come il più impegnativo.",
        "wrappedLocations": "Luoghi visitati",
        "wrappedNoLocations": "Ancora nessuna destinazione specifica nell'itinerario."
    },
    "pt": {
        "featureWrapped": "Resumo da viagem",
        "wrappedSubtitle": "Relembre os momentos memoráveis da sua viagem.",
        "wrappedExportPdf": "Exportar PDF",
        "wrappedExporting": "Exportando...",
        "wrappedDayTrip": "Viagem de um dia",
        "wrappedDays": "Dias de viagem",
        "wrappedEvents": "Eventos",
        "wrappedPacking": "Bagagem",
        "wrappedJournals": "Diários",
        "wrappedExpenseTitle": "DESPESAS DA VIAGEM",
        "wrappedTotalExpense": "Despesa Total",
        "wrappedSharedExpense": "Despesas compartilhadas",
        "wrappedPersonalExpense": "Despesas pessoais",
        "wrappedTopPayer": "Maior gastador",
        "wrappedTopPayerDesc": "é o maior gastador com",
        "wrappedNoMembersExpense": "Nenhum companheiro para sugerir um equilíbrio de despesas.",
        "wrappedNoExpenseData": "Ainda não há dados de despesas para esta viagem.",
        "wrappedMoodTitle": "HUMOR DA VIAGEM",
        "wrappedMoodDesc": "O humor principal registrado nos diários da sua viagem.",
        "wrappedNoMoodData": "Diários insuficientes para resumir o humor da viagem.",
        "wrappedNoMoodDesc": "Publique mais diários para salvar emoções e momentos memoráveis.",
        "wrappedPostFirstJournal": "Publicar o primeiro diário",
        "wrappedFirstMoment": "Primeiro momento",
        "wrappedNoFirstMoment": "Ainda não há primeiro momento. Adicione uma atividade ou publique um diário.",
        "wrappedFirstMomentEvent1": "Você começou com",
        "wrappedFirstMomentEvent2": "em",
        "wrappedFirstMomentJournal1": "A primeira memória foi registrada em",
        "wrappedBusiestDay": "Dia mais agitado",
        "wrappedBusiestDayDesc": "é o dia mais agitado com",
        "wrappedBusiestDayDesc2": "atividades registradas.",
        "wrappedNoBusiestDay": "Nenhum dia tem dados suficientes para ser o mais agitado.",
        "wrappedLocations": "Locais visitados",
        "wrappedNoLocations": "Nenhum destino específico no itinerário ainda."
    },
    "id": {
        "featureWrapped": "Ringkasan Perjalanan",
        "wrappedSubtitle": "Lihat kembali momen tak terlupakan dalam perjalanan Anda.",
        "wrappedExportPdf": "Ekspor PDF",
        "wrappedExporting": "Mengekspor...",
        "wrappedDayTrip": "Perjalanan satu hari",
        "wrappedDays": "Hari Perjalanan",
        "wrappedEvents": "Acara Timeline",
        "wrappedPacking": "Barang Bawaan",
        "wrappedJournals": "Jurnal",
        "wrappedExpenseTitle": "PENGELUARAN PERJALANAN",
        "wrappedTotalExpense": "Total Pengeluaran",
        "wrappedSharedExpense": "Pengeluaran Bersama",
        "wrappedPersonalExpense": "Pengeluaran Pribadi",
        "wrappedTopPayer": "Pembelanja Terbesar",
        "wrappedTopPayerDesc": "adalah pembelanja terbesar dengan",
        "wrappedNoMembersExpense": "Tidak ada teman untuk menyarankan keseimbangan pengeluaran.",
        "wrappedNoExpenseData": "Belum ada data pengeluaran untuk perjalanan ini.",
        "wrappedMoodTitle": "SUASANA PERJALANAN",
        "wrappedMoodDesc": "Suasana utama yang tercatat dari jurnal dalam perjalanan Anda.",
        "wrappedNoMoodData": "Jurnal tidak cukup untuk merangkum suasana perjalanan.",
        "wrappedNoMoodDesc": "Posting lebih banyak jurnal untuk menyimpan emosi dan momen kenangan.",
        "wrappedPostFirstJournal": "Posting jurnal pertama",
        "wrappedFirstMoment": "Momen Pertama",
        "wrappedNoFirstMoment": "Belum ada momen pertama. Tambahkan aktivitas atau posting jurnal.",
        "wrappedFirstMomentEvent1": "Anda mulai dengan",
        "wrappedFirstMomentEvent2": "pada",
        "wrappedFirstMomentJournal1": "Kenangan pertama tercatat pada",
        "wrappedBusiestDay": "Hari Tersibuk",
        "wrappedBusiestDayDesc": "adalah hari tersibuk dengan",
        "wrappedBusiestDayDesc2": "aktivitas tercatat.",
        "wrappedNoBusiestDay": "Belum ada hari dengan data yang cukup untuk menjadi hari tersibuk.",
        "wrappedLocations": "Lokasi Dikunjungi",
        "wrappedNoLocations": "Belum ada tujuan khusus di rencana perjalanan."
    }
}

documents_translations = {
    "vi": {
        "typeTicket": "Vé di chuyển",
        "typeHotel": "Đặt phòng",
        "typeBooking": "Mã đặt chỗ",
        "typeContact": "Liên hệ",
        "typeMap": "Bản đồ",
        "typeOther": "Khác",
        "editDocumentTitle": "Sửa giấy tờ & đặt chỗ",
        "addDocumentTitle": "Thêm giấy tờ & đặt chỗ",
        "titleRequired": "Vui lòng nhập tiêu đề.",
        "toastUpdated": "Đã cập nhật giấy tờ",
        "toastSaved": "Đã lưu giấy tờ mới",
        "toastError": "Có lỗi xảy ra khi lưu tài liệu",
        "saveBtn": "Lưu",
        "inputTitleLabel": "Tên mục *",
        "inputTitlePlaceholder": "VD: Vé máy bay khứ hồi, mã đặt phòng khách sạn...",
        "inputTypeLabel": "Phân loại",
        "inputPrivacyLabel": "Quyền chia sẻ",
        "privacyPrivate": "Riêng tư (Chỉ mình tôi)",
        "privacyGroup": "Chia sẻ với nhóm",
        "inputCodeLabel": "Mã / thông tin đặt chỗ",
        "inputCodePlaceholder": "VD: PNR ABC123, mã phòng, số vé...",
        "advancedInfoLabel": "Thông tin bổ sung",
        "inputDateLabel": "Ngày liên quan",
        "inputLinkLabel": "Đường dẫn liên quan",
        "inputLinkPlaceholder": "VD: Link vé điện tử, bản đồ, tệp đặt phòng...",
        "inputNoteLabel": "Ghi chú",
        "inputNotePlaceholder": "VD: Giờ nhận phòng, hành lý, số điện thoại liên hệ...",
        "inputAttachmentLabel": "Ảnh đính kèm (Vé/CCCD/...)",
        "uploadBtn": "Nhấn để tải ảnh lên",
        "uploadAcceptedFormats": "Chấp nhận PNG, JPG, WEBP",
        "editBtn": "Sửa",
        "deleteBtn": "Xóa",
        "optionsBtn": "Tùy chọn",
        "codeLabel": "Mã xác nhận / Code",
        "copyCodeBtn": "Sao chép mã",
        "relatedDateLabel": "Ngày liên quan:",
        "attachmentLabel": "Ảnh đính kèm",
        "openLinkBtn": "Mở liên kết trực tuyến",
        "featureTitle": "Giấy tờ & đặt chỗ",
        "featureDesc": "Lưu vé, mã đặt chỗ và thông tin quan trọng để tra cứu nhanh khi cần.",
        "addBtn": "Thêm giấy tờ",
        "filterAll": "Tất cả",
        "emptyAllTitle": "Chưa có giấy tờ nào",
        "emptyAllDesc": "Lưu vé, mã đặt chỗ, liên hệ quan trọng hoặc link bản đồ để tra cứu nhanh khi cần.",
        "emptyFilterTitle": "Không tìm thấy mục lưu trữ",
        "emptyFilterDesc": "Chọn bộ lọc khác hoặc thêm mới giấy tờ & đặt chỗ thuộc nhóm này.",
        "deleteModalTitle": "Xóa giấy tờ này?",
        "deleteModalDesc": "Mục giấy tờ hoặc đặt chỗ này sẽ bị xóa khỏi chuyến đi. Sau khi xóa, không thể hoàn tác.",
        "deleteModalConfirm": "Xóa giấy tờ",
        "toastDeleted": "Đã xóa thành công"
    },
    "en": {
        "typeTicket": "Transport Ticket",
        "typeHotel": "Hotel Booking",
        "typeBooking": "Booking Code",
        "typeContact": "Contact",
        "typeMap": "Map",
        "typeOther": "Other",
        "editDocumentTitle": "Edit Document",
        "addDocumentTitle": "Add Document",
        "titleRequired": "Please enter a title.",
        "toastUpdated": "Document updated",
        "toastSaved": "New document saved",
        "toastError": "Error saving document",
        "saveBtn": "Save",
        "inputTitleLabel": "Title *",
        "inputTitlePlaceholder": "e.g., Round-trip flight, hotel booking...",
        "inputTypeLabel": "Category",
        "inputPrivacyLabel": "Privacy",
        "privacyPrivate": "Private (Only me)",
        "privacyGroup": "Share with group",
        "inputCodeLabel": "Booking code / info",
        "inputCodePlaceholder": "e.g., PNR ABC123, room code...",
        "advancedInfoLabel": "Additional Info",
        "inputDateLabel": "Related Date",
        "inputLinkLabel": "Related Link",
        "inputLinkPlaceholder": "e.g., E-ticket link, map...",
        "inputNoteLabel": "Note",
        "inputNotePlaceholder": "e.g., Check-in time, contact number...",
        "inputAttachmentLabel": "Attachment",
        "uploadBtn": "Click to upload image",
        "uploadAcceptedFormats": "Accepts PNG, JPG, WEBP",
        "editBtn": "Edit",
        "deleteBtn": "Delete",
        "optionsBtn": "Options",
        "codeLabel": "Booking Code",
        "copyCodeBtn": "Copy Code",
        "relatedDateLabel": "Related Date:",
        "attachmentLabel": "Attachment",
        "openLinkBtn": "Open online link",
        "featureTitle": "Documents & Bookings",
        "featureDesc": "Save tickets, booking codes, and important info.",
        "addBtn": "Add Document",
        "filterAll": "All",
        "emptyAllTitle": "No documents yet",
        "emptyAllDesc": "Save tickets, booking codes, contacts or map links.",
        "emptyFilterTitle": "No items found",
        "emptyFilterDesc": "Select another filter or add a new document.",
        "deleteModalTitle": "Delete this document?",
        "deleteModalDesc": "This document will be removed from the trip.",
        "deleteModalConfirm": "Delete document",
        "toastDeleted": "Deleted successfully"
    },
    "ja": {
        "typeTicket": "交通チケット",
        "typeHotel": "ホテル予約",
        "typeBooking": "予約コード",
        "typeContact": "連絡先",
        "typeMap": "地図",
        "typeOther": "その他",
        "editDocumentTitle": "ドキュメント＆予約を編集",
        "addDocumentTitle": "ドキュメント＆予約を追加",
        "titleRequired": "タイトルを入力してください。",
        "toastUpdated": "更新しました",
        "toastSaved": "保存しました",
        "toastError": "エラーが発生しました",
        "saveBtn": "保存",
        "inputTitleLabel": "タイトル *",
        "inputTitlePlaceholder": "例：往復航空券...",
        "inputTypeLabel": "カテゴリー",
        "inputPrivacyLabel": "共有範囲",
        "privacyPrivate": "非公開（自分のみ）",
        "privacyGroup": "グループと共有",
        "inputCodeLabel": "予約コード",
        "inputCodePlaceholder": "例：PNR ABC123...",
        "advancedInfoLabel": "追加情報",
        "inputDateLabel": "関連日",
        "inputLinkLabel": "関連リンク",
        "inputLinkPlaceholder": "例：電子チケットのリンク...",
        "inputNoteLabel": "メモ",
        "inputNotePlaceholder": "例：チェックイン時間...",
        "inputAttachmentLabel": "添付ファイル",
        "uploadBtn": "画像をアップロード",
        "uploadAcceptedFormats": "PNG、JPG、WEBP",
        "editBtn": "編集",
        "deleteBtn": "削除",
        "optionsBtn": "オプション",
        "codeLabel": "予約コード",
        "copyCodeBtn": "コピー",
        "relatedDateLabel": "関連日:",
        "attachmentLabel": "添付ファイル",
        "openLinkBtn": "リンクを開く",
        "featureTitle": "ドキュメント＆予約",
        "featureDesc": "チケットや重要な情報を保存します。",
        "addBtn": "追加",
        "filterAll": "すべて",
        "emptyAllTitle": "ドキュメントなし",
        "emptyAllDesc": "チケットや予約コードを保存してください。",
        "emptyFilterTitle": "アイテムなし",
        "emptyFilterDesc": "新しいドキュメントを追加してください。",
        "deleteModalTitle": "削除しますか？",
        "deleteModalDesc": "このドキュメントは削除されます。",
        "deleteModalConfirm": "削除",
        "toastDeleted": "削除されました"
    },
    "th": {
        "typeTicket": "ตั๋วเดินทาง",
        "typeHotel": "จองโรงแรม",
        "typeBooking": "รหัสการจอง",
        "typeContact": "ติดต่อ",
        "typeMap": "แผนที่",
        "typeOther": "อื่นๆ",
        "editDocumentTitle": "แก้ไขเอกสาร",
        "addDocumentTitle": "เพิ่มเอกสาร",
        "titleRequired": "กรุณาใส่ชื่อ",
        "toastUpdated": "อัปเดตเอกสารแล้ว",
        "toastSaved": "บันทึกเอกสารแล้ว",
        "toastError": "เกิดข้อผิดพลาด",
        "saveBtn": "บันทึก",
        "inputTitleLabel": "ชื่อ *",
        "inputTitlePlaceholder": "เช่น ตั๋วเครื่องบิน...",
        "inputTypeLabel": "หมวดหมู่",
        "inputPrivacyLabel": "ความเป็นส่วนตัว",
        "privacyPrivate": "ส่วนตัว",
        "privacyGroup": "แชร์กับกลุ่ม",
        "inputCodeLabel": "รหัสการจอง",
        "inputCodePlaceholder": "เช่น PNR ABC123...",
        "advancedInfoLabel": "ข้อมูลเพิ่มเติม",
        "inputDateLabel": "วันที่เกี่ยวข้อง",
        "inputLinkLabel": "ลิงก์ที่เกี่ยวข้อง",
        "inputLinkPlaceholder": "เช่น ลิงก์ตั๋ว...",
        "inputNoteLabel": "หมายเหตุ",
        "inputNotePlaceholder": "เช่น เวลาเช็คอิน...",
        "inputAttachmentLabel": "ไฟล์แนบ",
        "uploadBtn": "อัปโหลดรูปภาพ",
        "uploadAcceptedFormats": "PNG, JPG, WEBP",
        "editBtn": "แก้ไข",
        "deleteBtn": "ลบ",
        "optionsBtn": "ตัวเลือก",
        "codeLabel": "รหัสการจอง",
        "copyCodeBtn": "คัดลอก",
        "relatedDateLabel": "วันที่เกี่ยวข้อง:",
        "attachmentLabel": "ไฟล์แนบ",
        "openLinkBtn": "เปิดลิงก์ออนไลน์",
        "featureTitle": "เอกสารและการจอง",
        "featureDesc": "บันทึกตั๋วและข้อมูลสำคัญ",
        "addBtn": "เพิ่มเอกสาร",
        "filterAll": "ทั้งหมด",
        "emptyAllTitle": "ยังไม่มีเอกสาร",
        "emptyAllDesc": "บันทึกตั๋ว รหัสการจอง...",
        "emptyFilterTitle": "ไม่พบรายการ",
        "emptyFilterDesc": "เพิ่มเอกสารใหม่ในหมวดหมู่นี้",
        "deleteModalTitle": "ลบเอกสารนี้หรือไม่?",
        "deleteModalDesc": "การกระทำนี้ไม่สามารถยกเลิกได้",
        "deleteModalConfirm": "ลบเอกสาร",
        "toastDeleted": "ลบสำเร็จแล้ว"
    },
    "ko": {
        "typeTicket": "교통 티켓",
        "typeHotel": "호텔 예약",
        "typeBooking": "예약 코드",
        "typeContact": "연락처",
        "typeMap": "지도",
        "typeOther": "기타",
        "editDocumentTitle": "문서 편집",
        "addDocumentTitle": "문서 추가",
        "titleRequired": "제목을 입력하세요.",
        "toastUpdated": "문서가 업데이트되었습니다",
        "toastSaved": "새 문서가 저장되었습니다",
        "toastError": "문서 저장 중 오류 발생",
        "saveBtn": "저장",
        "inputTitleLabel": "제목 *",
        "inputTitlePlaceholder": "예: 왕복 비행기, 호텔 예약...",
        "inputTypeLabel": "카테고리",
        "inputPrivacyLabel": "개인정보 보호",
        "privacyPrivate": "비공개 (나만)",
        "privacyGroup": "그룹과 공유",
        "inputCodeLabel": "예약 코드 / 정보",
        "inputCodePlaceholder": "예: PNR ABC123, 방 번호...",
        "advancedInfoLabel": "추가 정보",
        "inputDateLabel": "관련 날짜",
        "inputLinkLabel": "관련 링크",
        "inputLinkPlaceholder": "예: E-티켓 링크, 지도...",
        "inputNoteLabel": "메모",
        "inputNotePlaceholder": "예: 체크인 시간, 연락처...",
        "inputAttachmentLabel": "첨부파일",
        "uploadBtn": "이미지 업로드",
        "uploadAcceptedFormats": "PNG, JPG, WEBP 허용",
        "editBtn": "편집",
        "deleteBtn": "삭제",
        "optionsBtn": "옵션",
        "codeLabel": "예약 코드",
        "copyCodeBtn": "코드 복사",
        "relatedDateLabel": "관련 날짜:",
        "attachmentLabel": "첨부파일",
        "openLinkBtn": "온라인 링크 열기",
        "featureTitle": "문서 및 예약",
        "featureDesc": "티켓, 예약 코드 및 중요한 정보를 저장하세요.",
        "addBtn": "문서 추가",
        "filterAll": "모두",
        "emptyAllTitle": "아직 문서가 없습니다",
        "emptyAllDesc": "티켓, 예약 코드 등을 저장하세요.",
        "emptyFilterTitle": "항목을 찾을 수 없습니다",
        "emptyFilterDesc": "다른 필터를 선택하거나 새 문서를 추가하세요.",
        "deleteModalTitle": "이 문서를 삭제하시겠습니까?",
        "deleteModalDesc": "이 문서는 여행에서 삭제됩니다.",
        "deleteModalConfirm": "문서 삭제",
        "toastDeleted": "성공적으로 삭제되었습니다"
    },
    "zh": {
        "typeTicket": "交通票",
        "typeHotel": "酒店预订",
        "typeBooking": "预订代码",
        "typeContact": "联系方式",
        "typeMap": "地图",
        "typeOther": "其他",
        "editDocumentTitle": "编辑文件",
        "addDocumentTitle": "添加文件",
        "titleRequired": "请输入标题。",
        "toastUpdated": "文件已更新",
        "toastSaved": "新文件已保存",
        "toastError": "保存文件时出错",
        "saveBtn": "保存",
        "inputTitleLabel": "标题 *",
        "inputTitlePlaceholder": "例如：往返机票，酒店预订...",
        "inputTypeLabel": "类别",
        "inputPrivacyLabel": "隐私",
        "privacyPrivate": "私密 (仅自己)",
        "privacyGroup": "与群组共享",
        "inputCodeLabel": "预订代码 / 信息",
        "inputCodePlaceholder": "例如：PNR ABC123, 房间号...",
        "advancedInfoLabel": "附加信息",
        "inputDateLabel": "相关日期",
        "inputLinkLabel": "相关链接",
        "inputLinkPlaceholder": "例如：电子票链接，地图...",
        "inputNoteLabel": "备注",
        "inputNotePlaceholder": "例如：入住时间，联系电话...",
        "inputAttachmentLabel": "附件",
        "uploadBtn": "点击上传图片",
        "uploadAcceptedFormats": "接受 PNG, JPG, WEBP",
        "editBtn": "编辑",
        "deleteBtn": "删除",
        "optionsBtn": "选项",
        "codeLabel": "预订代码",
        "copyCodeBtn": "复制代码",
        "relatedDateLabel": "相关日期:",
        "attachmentLabel": "附件",
        "openLinkBtn": "打开在线链接",
        "featureTitle": "文件与预订",
        "featureDesc": "保存门票、预订代码及重要信息。",
        "addBtn": "添加文件",
        "filterAll": "全部",
        "emptyAllTitle": "暂无文件",
        "emptyAllDesc": "保存门票、预订代码等。",
        "emptyFilterTitle": "未找到项目",
        "emptyFilterDesc": "请选择其他过滤器或添加新文件。",
        "deleteModalTitle": "确定删除此文件吗？",
        "deleteModalDesc": "此文件将从旅行中删除。",
        "deleteModalConfirm": "删除文件",
        "toastDeleted": "已成功删除"
    },
    "fr": {
        "typeTicket": "Billet de transport",
        "typeHotel": "Réservation d'hôtel",
        "typeBooking": "Code de réservation",
        "typeContact": "Contact",
        "typeMap": "Carte",
        "typeOther": "Autre",
        "editDocumentTitle": "Modifier le document",
        "addDocumentTitle": "Ajouter un document",
        "titleRequired": "Veuillez entrer un titre.",
        "toastUpdated": "Document mis à jour",
        "toastSaved": "Nouveau document enregistré",
        "toastError": "Erreur lors de l'enregistrement",
        "saveBtn": "Enregistrer",
        "inputTitleLabel": "Titre *",
        "inputTitlePlaceholder": "Ex. Vol aller-retour, réservation d'hôtel...",
        "inputTypeLabel": "Catégorie",
        "inputPrivacyLabel": "Confidentialité",
        "privacyPrivate": "Privé (Seulement moi)",
        "privacyGroup": "Partager avec le groupe",
        "inputCodeLabel": "Code de réservation",
        "inputCodePlaceholder": "Ex. PNR ABC123, numéro de chambre...",
        "advancedInfoLabel": "Informations supplémentaires",
        "inputDateLabel": "Date liée",
        "inputLinkLabel": "Lien lié",
        "inputLinkPlaceholder": "Ex. Lien du billet électronique, carte...",
        "inputNoteLabel": "Note",
        "inputNotePlaceholder": "Ex. Heure d'arrivée, numéro de contact...",
        "inputAttachmentLabel": "Pièce jointe",
        "uploadBtn": "Cliquer pour télécharger",
        "uploadAcceptedFormats": "Accepte PNG, JPG, WEBP",
        "editBtn": "Modifier",
        "deleteBtn": "Supprimer",
        "optionsBtn": "Options",
        "codeLabel": "Code de réservation",
        "copyCodeBtn": "Copier",
        "relatedDateLabel": "Date liée:",
        "attachmentLabel": "Pièce jointe",
        "openLinkBtn": "Ouvrir le lien",
        "featureTitle": "Documents et réservations",
        "featureDesc": "Enregistrez vos billets et codes de réservation.",
        "addBtn": "Ajouter",
        "filterAll": "Tout",
        "emptyAllTitle": "Aucun document",
        "emptyAllDesc": "Enregistrez vos billets, codes ou contacts.",
        "emptyFilterTitle": "Aucun élément",
        "emptyFilterDesc": "Ajoutez un nouveau document à cette catégorie.",
        "deleteModalTitle": "Supprimer ce document?",
        "deleteModalDesc": "Ce document sera supprimé du voyage.",
        "deleteModalConfirm": "Supprimer",
        "toastDeleted": "Supprimé avec succès"
    },
    "es": {
        "typeTicket": "Billete de transporte",
        "typeHotel": "Reserva de hotel",
        "typeBooking": "Código de reserva",
        "typeContact": "Contacto",
        "typeMap": "Mapa",
        "typeOther": "Otro",
        "editDocumentTitle": "Editar documento",
        "addDocumentTitle": "Añadir documento",
        "titleRequired": "Por favor introduzca un título.",
        "toastUpdated": "Documento actualizado",
        "toastSaved": "Nuevo documento guardado",
        "toastError": "Error al guardar",
        "saveBtn": "Guardar",
        "inputTitleLabel": "Título *",
        "inputTitlePlaceholder": "Ej. Vuelo de ida y vuelta, reserva de hotel...",
        "inputTypeLabel": "Categoría",
        "inputPrivacyLabel": "Privacidad",
        "privacyPrivate": "Privado (Solo yo)",
        "privacyGroup": "Compartir con el grupo",
        "inputCodeLabel": "Código de reserva",
        "inputCodePlaceholder": "Ej. PNR ABC123, código de habitación...",
        "advancedInfoLabel": "Información adicional",
        "inputDateLabel": "Fecha relacionada",
        "inputLinkLabel": "Enlace relacionado",
        "inputLinkPlaceholder": "Ej. Enlace del billete electrónico, mapa...",
        "inputNoteLabel": "Nota",
        "inputNotePlaceholder": "Ej. Hora de entrada, número de contacto...",
        "inputAttachmentLabel": "Archivo adjunto",
        "uploadBtn": "Haz clic para subir imagen",
        "uploadAcceptedFormats": "Acepta PNG, JPG, WEBP",
        "editBtn": "Editar",
        "deleteBtn": "Eliminar",
        "optionsBtn": "Opciones",
        "codeLabel": "Código de reserva",
        "copyCodeBtn": "Copiar",
        "relatedDateLabel": "Fecha relacionada:",
        "attachmentLabel": "Archivo adjunto",
        "openLinkBtn": "Abrir enlace",
        "featureTitle": "Documentos y reservas",
        "featureDesc": "Guarda billetes y códigos de reserva.",
        "addBtn": "Añadir",
        "filterAll": "Todo",
        "emptyAllTitle": "No hay documentos",
        "emptyAllDesc": "Guarda billetes, códigos o contactos.",
        "emptyFilterTitle": "No se encontraron elementos",
        "emptyFilterDesc": "Añade un nuevo documento a esta categoría.",
        "deleteModalTitle": "¿Eliminar este documento?",
        "deleteModalDesc": "Este documento será eliminado del viaje.",
        "deleteModalConfirm": "Eliminar",
        "toastDeleted": "Eliminado con éxito"
    },
    "de": {
        "typeTicket": "Fahrkarte",
        "typeHotel": "Hotelbuchung",
        "typeBooking": "Buchungscode",
        "typeContact": "Kontakt",
        "typeMap": "Karte",
        "typeOther": "Andere",
        "editDocumentTitle": "Dokument bearbeiten",
        "addDocumentTitle": "Dokument hinzufügen",
        "titleRequired": "Bitte geben Sie einen Titel ein.",
        "toastUpdated": "Dokument aktualisiert",
        "toastSaved": "Neues Dokument gespeichert",
        "toastError": "Fehler beim Speichern",
        "saveBtn": "Speichern",
        "inputTitleLabel": "Titel *",
        "inputTitlePlaceholder": "Z.B. Hin- und Rückflug, Hotelbuchung...",
        "inputTypeLabel": "Kategorie",
        "inputPrivacyLabel": "Datenschutz",
        "privacyPrivate": "Privat (Nur ich)",
        "privacyGroup": "Mit der Gruppe teilen",
        "inputCodeLabel": "Buchungscode",
        "inputCodePlaceholder": "Z.B. PNR ABC123, Zimmercode...",
        "advancedInfoLabel": "Zusätzliche Infos",
        "inputDateLabel": "Verbundenes Datum",
        "inputLinkLabel": "Verbundenes Link",
        "inputLinkPlaceholder": "Z.B. E-Ticket-Link, Karte...",
        "inputNoteLabel": "Notiz",
        "inputNotePlaceholder": "Z.B. Check-in-Zeit, Kontaktnummer...",
        "inputAttachmentLabel": "Anhang",
        "uploadBtn": "Klicken zum Hochladen",
        "uploadAcceptedFormats": "Akzeptiert PNG, JPG, WEBP",
        "editBtn": "Bearbeiten",
        "deleteBtn": "Löschen",
        "optionsBtn": "Optionen",
        "codeLabel": "Buchungscode",
        "copyCodeBtn": "Kopieren",
        "relatedDateLabel": "Verbundenes Datum:",
        "attachmentLabel": "Anhang",
        "openLinkBtn": "Link öffnen",
        "featureTitle": "Dokumente & Buchungen",
        "featureDesc": "Speichern Sie Tickets und Buchungscodes.",
        "addBtn": "Hinzufügen",
        "filterAll": "Alle",
        "emptyAllTitle": "Keine Dokumente",
        "emptyAllDesc": "Speichern Sie Tickets, Codes oder Kontakte.",
        "emptyFilterTitle": "Keine Elemente",
        "emptyFilterDesc": "Fügen Sie ein neues Dokument hinzu.",
        "deleteModalTitle": "Dokument löschen?",
        "deleteModalDesc": "Dieses Dokument wird aus der Reise entfernt.",
        "deleteModalConfirm": "Löschen",
        "toastDeleted": "Erfolgreich gelöscht"
    },
    "it": {
        "typeTicket": "Biglietto di trasporto",
        "typeHotel": "Prenotazione hotel",
        "typeBooking": "Codice prenotazione",
        "typeContact": "Contatto",
        "typeMap": "Mappa",
        "typeOther": "Altro",
        "editDocumentTitle": "Modifica documento",
        "addDocumentTitle": "Aggiungi documento",
        "titleRequired": "Inserisci un titolo.",
        "toastUpdated": "Documento aggiornato",
        "toastSaved": "Nuovo documento salvato",
        "toastError": "Errore durante il salvataggio",
        "saveBtn": "Salva",
        "inputTitleLabel": "Titolo *",
        "inputTitlePlaceholder": "Es. Volo a/r, prenotazione hotel...",
        "inputTypeLabel": "Categoria",
        "inputPrivacyLabel": "Privacy",
        "privacyPrivate": "Privato (Solo io)",
        "privacyGroup": "Condividi con il gruppo",
        "inputCodeLabel": "Codice prenotazione",
        "inputCodePlaceholder": "Es. PNR ABC123, codice stanza...",
        "advancedInfoLabel": "Info aggiuntive",
        "inputDateLabel": "Data correlata",
        "inputLinkLabel": "Link correlato",
        "inputLinkPlaceholder": "Es. Link del biglietto, mappa...",
        "inputNoteLabel": "Nota",
        "inputNotePlaceholder": "Es. Orario check-in, numero di contatto...",
        "inputAttachmentLabel": "Allegato",
        "uploadBtn": "Clicca per caricare",
        "uploadAcceptedFormats": "Accetta PNG, JPG, WEBP",
        "editBtn": "Modifica",
        "deleteBtn": "Elimina",
        "optionsBtn": "Opzioni",
        "codeLabel": "Codice prenotazione",
        "copyCodeBtn": "Copia",
        "relatedDateLabel": "Data correlata:",
        "attachmentLabel": "Allegato",
        "openLinkBtn": "Apri link",
        "featureTitle": "Documenti e prenotazioni",
        "featureDesc": "Salva i biglietti e i codici di prenotazione.",
        "addBtn": "Aggiungi",
        "filterAll": "Tutto",
        "emptyAllTitle": "Nessun documento",
        "emptyAllDesc": "Salva biglietti, codici o contatti.",
        "emptyFilterTitle": "Nessun elemento",
        "emptyFilterDesc": "Aggiungi un nuovo documento.",
        "deleteModalTitle": "Eliminare questo documento?",
        "deleteModalDesc": "Questo documento verrà rimosso dal viaggio.",
        "deleteModalConfirm": "Elimina",
        "toastDeleted": "Eliminato con successo"
    },
    "pt": {
        "typeTicket": "Bilhete de transporte",
        "typeHotel": "Reserva de hotel",
        "typeBooking": "Código de reserva",
        "typeContact": "Contato",
        "typeMap": "Mapa",
        "typeOther": "Outro",
        "editDocumentTitle": "Editar documento",
        "addDocumentTitle": "Adicionar documento",
        "titleRequired": "Por favor, insira um título.",
        "toastUpdated": "Documento atualizado",
        "toastSaved": "Novo documento salvo",
        "toastError": "Erro ao salvar",
        "saveBtn": "Salvar",
        "inputTitleLabel": "Título *",
        "inputTitlePlaceholder": "Ex. Voo de ida e volta, reserva de hotel...",
        "inputTypeLabel": "Categoria",
        "inputPrivacyLabel": "Privacidade",
        "privacyPrivate": "Privado (Apenas eu)",
        "privacyGroup": "Compartilhar com o grupo",
        "inputCodeLabel": "Código de reserva",
        "inputCodePlaceholder": "Ex. PNR ABC123, código do quarto...",
        "advancedInfoLabel": "Informações adicionais",
        "inputDateLabel": "Data relacionada",
        "inputLinkLabel": "Link relacionado",
        "inputLinkPlaceholder": "Ex. Link do bilhete, mapa...",
        "inputNoteLabel": "Nota",
        "inputNotePlaceholder": "Ex. Horário de check-in, número de contato...",
        "inputAttachmentLabel": "Anexo",
        "uploadBtn": "Clique para enviar imagem",
        "uploadAcceptedFormats": "Aceita PNG, JPG, WEBP",
        "editBtn": "Editar",
        "deleteBtn": "Excluir",
        "optionsBtn": "Opções",
        "codeLabel": "Código de reserva",
        "copyCodeBtn": "Copiar",
        "relatedDateLabel": "Data relacionada:",
        "attachmentLabel": "Anexo",
        "openLinkBtn": "Abrir link",
        "featureTitle": "Documentos e reservas",
        "featureDesc": "Salve bilhetes e códigos de reserva.",
        "addBtn": "Adicionar",
        "filterAll": "Tudo",
        "emptyAllTitle": "Nenhum documento",
        "emptyAllDesc": "Salve bilhetes, códigos ou contatos.",
        "emptyFilterTitle": "Nenhum item encontrado",
        "emptyFilterDesc": "Adicione um novo documento a esta categoria.",
        "deleteModalTitle": "Excluir este documento?",
        "deleteModalDesc": "Este documento será removido da viagem.",
        "deleteModalConfirm": "Excluir",
        "toastDeleted": "Excluído com sucesso"
    },
    "id": {
        "typeTicket": "Tiket Transportasi",
        "typeHotel": "Pemesanan Hotel",
        "typeBooking": "Kode Pemesanan",
        "typeContact": "Kontak",
        "typeMap": "Peta",
        "typeOther": "Lainnya",
        "editDocumentTitle": "Edit Dokumen",
        "addDocumentTitle": "Tambah Dokumen",
        "titleRequired": "Harap masukkan judul.",
        "toastUpdated": "Dokumen diperbarui",
        "toastSaved": "Dokumen baru disimpan",
        "toastError": "Kesalahan saat menyimpan",
        "saveBtn": "Simpan",
        "inputTitleLabel": "Judul *",
        "inputTitlePlaceholder": "Mis. Penerbangan PP, pemesanan hotel...",
        "inputTypeLabel": "Kategori",
        "inputPrivacyLabel": "Privasi",
        "privacyPrivate": "Pribadi (Hanya saya)",
        "privacyGroup": "Bagikan dengan grup",
        "inputCodeLabel": "Kode pemesanan / info",
        "inputCodePlaceholder": "Mis. PNR ABC123, kode kamar...",
        "advancedInfoLabel": "Info Tambahan",
        "inputDateLabel": "Tanggal Terkait",
        "inputLinkLabel": "Tautan Terkait",
        "inputLinkPlaceholder": "Mis. Tautan E-tiket, peta...",
        "inputNoteLabel": "Catatan",
        "inputNotePlaceholder": "Mis. Waktu check-in, nomor kontak...",
        "inputAttachmentLabel": "Lampiran",
        "uploadBtn": "Klik untuk mengunggah",
        "uploadAcceptedFormats": "Menerima PNG, JPG, WEBP",
        "editBtn": "Edit",
        "deleteBtn": "Hapus",
        "optionsBtn": "Opsi",
        "codeLabel": "Kode Pemesanan",
        "copyCodeBtn": "Salin",
        "relatedDateLabel": "Tanggal Terkait:",
        "attachmentLabel": "Lampiran",
        "openLinkBtn": "Buka tautan",
        "featureTitle": "Dokumen & Pemesanan",
        "featureDesc": "Simpan tiket dan kode pemesanan.",
        "addBtn": "Tambah Dokumen",
        "filterAll": "Semua",
        "emptyAllTitle": "Belum ada dokumen",
        "emptyAllDesc": "Simpan tiket, kode, atau kontak.",
        "emptyFilterTitle": "Tidak ada item",
        "emptyFilterDesc": "Tambahkan dokumen baru.",
        "deleteModalTitle": "Hapus dokumen ini?",
        "deleteModalDesc": "Dokumen ini akan dihapus dari perjalanan.",
        "deleteModalConfirm": "Hapus",
        "toastDeleted": "Berhasil dihapus"
    }
}

for lang in wrapped_translations.keys():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        file_data = json.load(f)
        
    if "more" not in file_data:
        file_data["more"] = {}
    if "documents" not in file_data:
        file_data["documents"] = {}
        
    for k, v in wrapped_translations[lang].items():
        file_data["more"][k] = v
        
    for k, v in documents_translations[lang].items():
        file_data["documents"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(file_data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
