import json
import os

translations = {
    "ko": {
        "pageTitle": "짐 꾸리기",
        "pageSubtitle": "여행에 필요한 모든 물품을 준비하세요.",
        "progressTitle": "준비 진행률",
        "progressStatus": "{{completed}} / {{total}}개 완료",
        "progressPerfect": "훌륭합니다! 모든 짐을 꾸렸습니다.",
        "progressEmpty": "첫 번째 물품을 추가하여 시작하세요.",
        "addItem": "항목 추가",
        "itemName": "항목 이름 *",
        "itemNamePlaceholder": "항목 입력 (예: 여권, 자켓...)",
        "itemNameError": "항목 이름을 입력하세요.",
        "categoryLabel": "카테고리",
        "quantityLabel": "수량",
        "quantityDesc": "가져갈 수량",
        "assigneeLabel": "담당자",
        "noMembersTitle": "동행자 없음",
        "noMembersDesc": "담당자를 지정하려면 동행자를 추가하세요.",
        "priorityLabel": "중요도",
        "priorityNormal": "보통",
        "priorityImportant": "중요",
        "priorityRequired": "필수",
        "noteLabel": "메모",
        "notePlaceholder": "이 항목에 대한 메모...",
        "privateItem": "개인 물품",
        "privateItemDesc": "그룹과 공유하지 않음",
        "cancel": "취소",
        "save": "변경사항 저장",
        "add": "항목 추가",
        "deleteConfirmTitle": "이 항목을 삭제하시겠습니까?",
        "deleteConfirmDesc": "이 항목을 목록에서 삭제하시겠습니까?",
        "deleteButton": "삭제",
        "toastAdded": "새 항목이 추가되었습니다",
        "toastUpdated": "항목이 업데이트되었습니다",
        "catDocuments": "서류",
        "catClothing": "의류",
        "catPersonal": "개인용품",
        "catElectronics": "전자기기",
        "catMedical": "의약품",
        "catMoney": "돈 & 지갑",
        "catSnacks": "간식",
        "catOther": "기타"
    },
    "zh": {
        "pageTitle": "行李清单",
        "pageSubtitle": "准备好旅行所需的所有物品。",
        "progressTitle": "准备进度",
        "progressStatus": "已收拾 {{completed}} / {{total}} 件",
        "progressPerfect": "太棒了！行李已准备完毕。",
        "progressEmpty": "添加第一件物品开始准备。",
        "addItem": "添加物品",
        "itemName": "物品名称 *",
        "itemNamePlaceholder": "输入物品 (例：护照、外套...)",
        "itemNameError": "请输入物品名称。",
        "categoryLabel": "类别",
        "quantityLabel": "数量",
        "quantityDesc": "需要携带的数量",
        "assigneeLabel": "负责人",
        "noMembersTitle": "暂无同行者",
        "noMembersDesc": "添加同行者以分配任务。",
        "priorityLabel": "重要程度",
        "priorityNormal": "普通",
        "priorityImportant": "重要",
        "priorityRequired": "必需",
        "noteLabel": "备注",
        "notePlaceholder": "关于此物品的备注...",
        "privateItem": "个人物品",
        "privateItemDesc": "不与群组共享",
        "cancel": "取消",
        "save": "保存更改",
        "add": "添加物品",
        "deleteConfirmTitle": "删除此物品？",
        "deleteConfirmDesc": "确定要从清单中删除此物品吗？",
        "deleteButton": "删除",
        "toastAdded": "已添加新物品",
        "toastUpdated": "物品已更新",
        "catDocuments": "证件",
        "catClothing": "衣物",
        "catPersonal": "个人用品",
        "catElectronics": "电子产品",
        "catMedical": "药品",
        "catMoney": "钱包 & 钱",
        "catSnacks": "零食",
        "catOther": "其他"
    },
    "ja": {
        "pageTitle": "持ち物リスト",
        "pageSubtitle": "旅行に必要なものをすべて準備しましょう。",
        "progressTitle": "準備の進捗",
        "progressStatus": "{{completed}} / {{total}} 個完了",
        "progressPerfect": "完璧です！すべての準備が整いました。",
        "progressEmpty": "最初のアイテムを追加して開始してください。",
        "addItem": "アイテムを追加",
        "itemName": "アイテム名 *",
        "itemNamePlaceholder": "アイテムを入力 (例：パスポート、ジャケット...)",
        "itemNameError": "アイテム名を入力してください。",
        "categoryLabel": "カテゴリー",
        "quantityLabel": "数量",
        "quantityDesc": "持っていく数量",
        "assigneeLabel": "担当者",
        "noMembersTitle": "同行者なし",
        "noMembersDesc": "同行者を追加して担当を割り当てます。",
        "priorityLabel": "重要度",
        "priorityNormal": "普通",
        "priorityImportant": "重要",
        "priorityRequired": "必須",
        "noteLabel": "メモ",
        "notePlaceholder": "このアイテムについてのメモ...",
        "privateItem": "個人用品",
        "privateItemDesc": "グループと共有しない",
        "cancel": "キャンセル",
        "save": "変更を保存",
        "add": "アイテムを追加",
        "deleteConfirmTitle": "このアイテムを削除しますか？",
        "deleteConfirmDesc": "リストからこのアイテムを削除してもよろしいですか？",
        "deleteButton": "削除",
        "toastAdded": "新しいアイテムを追加しました",
        "toastUpdated": "アイテムを更新しました",
        "catDocuments": "書類",
        "catClothing": "衣類",
        "catPersonal": "日用品",
        "catElectronics": "電子機器",
        "catMedical": "医薬品",
        "catMoney": "お金・財布",
        "catSnacks": "軽食",
        "catOther": "その他"
    },
    "en": {
        "pageTitle": "Packing List",
        "pageSubtitle": "Pack everything you need for the trip.",
        "progressTitle": "Packing Progress",
        "progressStatus": "Packed {{completed}} / {{total}} items",
        "progressPerfect": "Awesome! Everything is packed.",
        "progressEmpty": "Add your first item to start packing.",
        "addItem": "Add item",
        "itemName": "Item name *",
        "itemNamePlaceholder": "Enter item (e.g. Passport, Jacket...)",
        "itemNameError": "Please enter an item name.",
        "categoryLabel": "Category",
        "quantityLabel": "Quantity",
        "quantityDesc": "Amount to bring",
        "assigneeLabel": "Assigned to",
        "noMembersTitle": "No companions",
        "noMembersDesc": "Add companions to assign items.",
        "priorityLabel": "Priority",
        "priorityNormal": "Normal",
        "priorityImportant": "Important",
        "priorityRequired": "Required",
        "noteLabel": "Note",
        "notePlaceholder": "Notes about this item...",
        "privateItem": "Private item",
        "privateItemDesc": "Do not share with the group",
        "cancel": "Cancel",
        "save": "Save changes",
        "add": "Add item",
        "deleteConfirmTitle": "Delete this item?",
        "deleteConfirmDesc": "Are you sure you want to remove this item from the list?",
        "deleteButton": "Delete",
        "toastAdded": "Added new item",
        "toastUpdated": "Updated item",
        "catDocuments": "Documents",
        "catClothing": "Clothing",
        "catPersonal": "Personal",
        "catElectronics": "Electronics",
        "catMedical": "Medical",
        "catMoney": "Money & Wallet",
        "catSnacks": "Snacks",
        "catOther": "Other"
    },
    "es": {
        "pageTitle": "Lista de equipaje",
        "pageSubtitle": "Empaca todo lo necesario para el viaje.",
        "progressTitle": "Progreso de equipaje",
        "progressStatus": "{{completed}} / {{total}} empacados",
        "progressPerfect": "¡Genial! Todo está empacado.",
        "progressEmpty": "Añade el primer artículo para empezar.",
        "addItem": "Añadir",
        "itemName": "Nombre del artículo *",
        "itemNamePlaceholder": "Ej: Pasaporte, Chaqueta...",
        "itemNameError": "Introduce el nombre del artículo.",
        "categoryLabel": "Categoría",
        "quantityLabel": "Cantidad",
        "quantityDesc": "Cantidad a llevar",
        "assigneeLabel": "Asignado a",
        "noMembersTitle": "Sin acompañantes",
        "noMembersDesc": "Añade acompañantes para asignar.",
        "priorityLabel": "Prioridad",
        "priorityNormal": "Normal",
        "priorityImportant": "Importante",
        "priorityRequired": "Requerido",
        "noteLabel": "Nota",
        "notePlaceholder": "Notas sobre este artículo...",
        "privateItem": "Artículo privado",
        "privateItemDesc": "No compartir con el grupo",
        "cancel": "Cancelar",
        "save": "Guardar cambios",
        "add": "Añadir",
        "deleteConfirmTitle": "¿Eliminar este artículo?",
        "deleteConfirmDesc": "¿Seguro que quieres eliminar este artículo?",
        "deleteButton": "Eliminar",
        "toastAdded": "Artículo añadido",
        "toastUpdated": "Artículo actualizado",
        "catDocuments": "Documentos",
        "catClothing": "Ropa",
        "catPersonal": "Personal",
        "catElectronics": "Electrónica",
        "catMedical": "Médico",
        "catMoney": "Dinero",
        "catSnacks": "Snacks",
        "catOther": "Otro"
    },
    "fr": {
        "pageTitle": "Liste de bagages",
        "pageSubtitle": "Préparez tout ce dont vous avez besoin.",
        "progressTitle": "Progression",
        "progressStatus": "{{completed}} / {{total}} emballés",
        "progressPerfect": "Génial ! Tout est prêt.",
        "progressEmpty": "Ajoutez un article pour commencer.",
        "addItem": "Ajouter",
        "itemName": "Nom de l'article *",
        "itemNamePlaceholder": "Ex: Passeport, Veste...",
        "itemNameError": "Entrez un nom d'article.",
        "categoryLabel": "Catégorie",
        "quantityLabel": "Quantité",
        "quantityDesc": "Nombre à apporter",
        "assigneeLabel": "Assigné à",
        "noMembersTitle": "Aucun compagnon",
        "noMembersDesc": "Ajoutez des membres pour assigner.",
        "priorityLabel": "Priorité",
        "priorityNormal": "Normal",
        "priorityImportant": "Important",
        "priorityRequired": "Requis",
        "noteLabel": "Note",
        "notePlaceholder": "Notes sur cet article...",
        "privateItem": "Article privé",
        "privateItemDesc": "Ne pas partager avec le groupe",
        "cancel": "Annuler",
        "save": "Enregistrer",
        "add": "Ajouter",
        "deleteConfirmTitle": "Supprimer cet article ?",
        "deleteConfirmDesc": "Voulez-vous vraiment supprimer cet article ?",
        "deleteButton": "Supprimer",
        "toastAdded": "Article ajouté",
        "toastUpdated": "Article mis à jour",
        "catDocuments": "Documents",
        "catClothing": "Vêtements",
        "catPersonal": "Personnel",
        "catElectronics": "Électronique",
        "catMedical": "Médical",
        "catMoney": "Argent",
        "catSnacks": "Snacks",
        "catOther": "Autre"
    },
    "de": {
        "pageTitle": "Packliste",
        "pageSubtitle": "Packen Sie alles ein, was Sie brauchen.",
        "progressTitle": "Packfortschritt",
        "progressStatus": "{{completed}} / {{total}} gepackt",
        "progressPerfect": "Klasse! Alles ist gepackt.",
        "progressEmpty": "Fügen Sie den ersten Artikel hinzu.",
        "addItem": "Hinzufügen",
        "itemName": "Artikelname *",
        "itemNamePlaceholder": "Z.B. Reisepass, Jacke...",
        "itemNameError": "Bitte Artikelnamen eingeben.",
        "categoryLabel": "Kategorie",
        "quantityLabel": "Anzahl",
        "quantityDesc": "Menge zum Mitnehmen",
        "assigneeLabel": "Zugewiesen an",
        "noMembersTitle": "Keine Begleiter",
        "noMembersDesc": "Begleiter hinzufügen zum Zuweisen.",
        "priorityLabel": "Priorität",
        "priorityNormal": "Normal",
        "priorityImportant": "Wichtig",
        "priorityRequired": "Erforderlich",
        "noteLabel": "Notiz",
        "notePlaceholder": "Notizen zu diesem Artikel...",
        "privateItem": "Privater Artikel",
        "privateItemDesc": "Nicht mit Gruppe teilen",
        "cancel": "Abbrechen",
        "save": "Speichern",
        "add": "Hinzufügen",
        "deleteConfirmTitle": "Diesen Artikel löschen?",
        "deleteConfirmDesc": "Möchten Sie diesen Artikel wirklich löschen?",
        "deleteButton": "Löschen",
        "toastAdded": "Artikel hinzugefügt",
        "toastUpdated": "Artikel aktualisiert",
        "catDocuments": "Dokumente",
        "catClothing": "Kleidung",
        "catPersonal": "Persönlich",
        "catElectronics": "Elektronik",
        "catMedical": "Medizin",
        "catMoney": "Geld & Wallet",
        "catSnacks": "Snacks",
        "catOther": "Sonstiges"
    },
    "it": {
        "pageTitle": "Lista bagagli",
        "pageSubtitle": "Prepara tutto il necessario per il viaggio.",
        "progressTitle": "Avanzamento",
        "progressStatus": "{{completed}} / {{total}} imballati",
        "progressPerfect": "Fantastico! Tutto pronto.",
        "progressEmpty": "Aggiungi il primo articolo per iniziare.",
        "addItem": "Aggiungi",
        "itemName": "Nome articolo *",
        "itemNamePlaceholder": "Es: Passaporto, Giacca...",
        "itemNameError": "Inserisci il nome dell'articolo.",
        "categoryLabel": "Categoria",
        "quantityLabel": "Quantità",
        "quantityDesc": "Quantità da portare",
        "assigneeLabel": "Assegnato a",
        "noMembersTitle": "Nessun compagno",
        "noMembersDesc": "Aggiungi compagni per assegnare.",
        "priorityLabel": "Priorità",
        "priorityNormal": "Normale",
        "priorityImportant": "Importante",
        "priorityRequired": "Richiesto",
        "noteLabel": "Nota",
        "notePlaceholder": "Note su questo articolo...",
        "privateItem": "Articolo privato",
        "privateItemDesc": "Non condividere col gruppo",
        "cancel": "Annulla",
        "save": "Salva modifiche",
        "add": "Aggiungi",
        "deleteConfirmTitle": "Eliminare questo articolo?",
        "deleteConfirmDesc": "Sei sicuro di voler eliminare questo articolo?",
        "deleteButton": "Elimina",
        "toastAdded": "Articolo aggiunto",
        "toastUpdated": "Articolo aggiornato",
        "catDocuments": "Documenti",
        "catClothing": "Abbigliamento",
        "catPersonal": "Personale",
        "catElectronics": "Elettronica",
        "catMedical": "Medico",
        "catMoney": "Denaro",
        "catSnacks": "Snack",
        "catOther": "Altro"
    },
    "pt": {
        "pageTitle": "Lista de Bagagem",
        "pageSubtitle": "Arrume tudo o que precisa para a viagem.",
        "progressTitle": "Progresso",
        "progressStatus": "{{completed}} / {{total}} na mala",
        "progressPerfect": "Excelente! Tudo pronto.",
        "progressEmpty": "Adicione o primeiro item para começar.",
        "addItem": "Adicionar",
        "itemName": "Nome do item *",
        "itemNamePlaceholder": "Ex: Passaporte, Casaco...",
        "itemNameError": "Insira o nome do item.",
        "categoryLabel": "Categoria",
        "quantityLabel": "Quantidade",
        "quantityDesc": "Quantidade a levar",
        "assigneeLabel": "Atribuído a",
        "noMembersTitle": "Sem companheiros",
        "noMembersDesc": "Adicione companheiros para atribuir.",
        "priorityLabel": "Prioridade",
        "priorityNormal": "Normal",
        "priorityImportant": "Importante",
        "priorityRequired": "Obrigatório",
        "noteLabel": "Nota",
        "notePlaceholder": "Notas sobre este item...",
        "privateItem": "Item privado",
        "privateItemDesc": "Não compartilhar com o grupo",
        "cancel": "Cancelar",
        "save": "Salvar",
        "add": "Adicionar",
        "deleteConfirmTitle": "Excluir este item?",
        "deleteConfirmDesc": "Tem certeza que deseja remover este item?",
        "deleteButton": "Excluir",
        "toastAdded": "Item adicionado",
        "toastUpdated": "Item atualizado",
        "catDocuments": "Documentos",
        "catClothing": "Roupas",
        "catPersonal": "Pessoal",
        "catElectronics": "Eletrônicos",
        "catMedical": "Médico",
        "catMoney": "Dinheiro",
        "catSnacks": "Lanches",
        "catOther": "Outro"
    },
    "th": {
        "pageTitle": "รายการสัมภาระ",
        "pageSubtitle": "เตรียมสิ่งของที่จำเป็นสำหรับการเดินทาง",
        "progressTitle": "ความคืบหน้า",
        "progressStatus": "จัดแล้ว {{completed}} / {{total}} ชิ้น",
        "progressPerfect": "ยอดเยี่ยม! จัดเตรียมเสร็จแล้ว",
        "progressEmpty": "เพิ่มรายการแรกเพื่อเริ่มจัดกระเป๋า",
        "addItem": "เพิ่มรายการ",
        "itemName": "ชื่อรายการ *",
        "itemNamePlaceholder": "เช่น พาสปอร์ต, เสื้อแจ็คเก็ต...",
        "itemNameError": "กรุณากรอกชื่อรายการ",
        "categoryLabel": "หมวดหมู่",
        "quantityLabel": "จำนวน",
        "quantityDesc": "จำนวนที่ต้องนำไป",
        "assigneeLabel": "มอบหมายให้",
        "noMembersTitle": "ไม่มีผู้ร่วมเดินทาง",
        "noMembersDesc": "เพิ่มผู้ร่วมเดินทางเพื่อมอบหมายงาน",
        "priorityLabel": "ความสำคัญ",
        "priorityNormal": "ปกติ",
        "priorityImportant": "สำคัญ",
        "priorityRequired": "จำเป็น",
        "noteLabel": "หมายเหตุ",
        "notePlaceholder": "บันทึกเพิ่มเติม...",
        "privateItem": "ของใช้ส่วนตัว",
        "privateItemDesc": "ไม่แชร์กับกลุ่ม",
        "cancel": "ยกเลิก",
        "save": "บันทึก",
        "add": "เพิ่ม",
        "deleteConfirmTitle": "ลบรายการนี้?",
        "deleteConfirmDesc": "แน่ใจหรือไม่ว่าต้องการลบรายการนี้?",
        "deleteButton": "ลบ",
        "toastAdded": "เพิ่มรายการใหม่แล้ว",
        "toastUpdated": "อัปเดตรายการแล้ว",
        "catDocuments": "เอกสาร",
        "catClothing": "เสื้อผ้า",
        "catPersonal": "ของใช้ส่วนตัว",
        "catElectronics": "อุปกรณ์อิเล็กทรอนิกส์",
        "catMedical": "ยา & สุขภาพ",
        "catMoney": "เงิน & กระเป๋าตังค์",
        "catSnacks": "ขนม",
        "catOther": "อื่นๆ"
    },
    "id": {
        "pageTitle": "Daftar Barang Bawaan",
        "pageSubtitle": "Siapkan semua yang Anda butuhkan.",
        "progressTitle": "Kemajuan",
        "progressStatus": "{{completed}} / {{total}} dikemas",
        "progressPerfect": "Bagus! Semuanya sudah siap.",
        "progressEmpty": "Tambahkan barang pertama untuk mulai.",
        "addItem": "Tambah",
        "itemName": "Nama barang *",
        "itemNamePlaceholder": "Mis: Paspor, Jaket...",
        "itemNameError": "Masukkan nama barang.",
        "categoryLabel": "Kategori",
        "quantityLabel": "Jumlah",
        "quantityDesc": "Jumlah yang dibawa",
        "assigneeLabel": "Ditugaskan ke",
        "noMembersTitle": "Tidak ada teman",
        "noMembersDesc": "Tambahkan pendamping untuk menugaskan.",
        "priorityLabel": "Prioritas",
        "priorityNormal": "Normal",
        "priorityImportant": "Penting",
        "priorityRequired": "Wajib",
        "noteLabel": "Catatan",
        "notePlaceholder": "Catatan tentang barang ini...",
        "privateItem": "Barang pribadi",
        "privateItemDesc": "Jangan bagikan dengan grup",
        "cancel": "Batal",
        "save": "Simpan",
        "add": "Tambah",
        "deleteConfirmTitle": "Hapus barang ini?",
        "deleteConfirmDesc": "Yakin ingin menghapus barang ini?",
        "deleteButton": "Hapus",
        "toastAdded": "Barang ditambahkan",
        "toastUpdated": "Barang diperbarui",
        "catDocuments": "Dokumen",
        "catClothing": "Pakaian",
        "catPersonal": "Pribadi",
        "catElectronics": "Elektronik",
        "catMedical": "Kesehatan",
        "catMoney": "Uang & Dompet",
        "catSnacks": "Camilan",
        "catOther": "Lainnya"
    },
    "vi": {
        "pageTitle": "Chuẩn bị hành lý",
        "pageSubtitle": "Chuẩn bị đủ những món cần mang theo cho chuyến đi.",
        "progressTitle": "Tiến độ chuẩn bị",
        "progressStatus": "Đã xếp {{completed}} / {{total}} món",
        "progressPerfect": "Tuyệt vời! Hành lý đã sẵn sàng.",
        "progressEmpty": "Thêm món đồ đầu tiên để bắt đầu chuẩn bị.",
        "addItem": "Thêm món",
        "itemName": "Tên món cần mang *",
        "itemNamePlaceholder": "Nhập tên món (vd: Hộ chiếu, áo khoác...)",
        "itemNameError": "Vui lòng nhập tên món cần mang.",
        "categoryLabel": "Nhóm hành lý",
        "quantityLabel": "Số lượng",
        "quantityDesc": "Số lượng cần mang theo",
        "assigneeLabel": "Người phụ trách",
        "noMembersTitle": "Chưa có người phụ trách",
        "noMembersDesc": "Thêm thành viên trong chuyến đi để giao việc.",
        "priorityLabel": "Mức độ cần thiết",
        "priorityNormal": "Bình thường",
        "priorityImportant": "Quan trọng",
        "priorityRequired": "Bắt buộc",
        "noteLabel": "Ghi chú",
        "notePlaceholder": "Ghi chú thêm về món đồ này...",
        "privateItem": "Vật dụng cá nhân",
        "privateItemDesc": "Không chia sẻ với đoàn khi ghép nhóm",
        "cancel": "Hủy",
        "save": "Lưu thay đổi",
        "add": "Thêm món",
        "deleteConfirmTitle": "Xóa món đồ này?",
        "deleteConfirmDesc": "Bạn có chắc muốn xóa món đồ này khỏi danh sách chuẩn bị?",
        "deleteButton": "Xóa",
        "toastAdded": "Đã thêm món đồ mới",
        "toastUpdated": "Đã cập nhật món đồ",
        "catDocuments": "Giấy tờ",
        "catClothing": "Quần áo",
        "catPersonal": "Đồ cá nhân",
        "catElectronics": "Thiết bị điện tử",
        "catMedical": "Thuốc & y tế",
        "catMoney": "Tiền & ví",
        "catSnacks": "Đồ ăn nhẹ",
        "catOther": "Khác"
    }
}

for lang, data_dict in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    if "packing" not in data:
        data["packing"] = {}
        
    for k, v in data_dict.items():
        data["packing"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
