import json
import os

translations = {
    "vi": {
        "title": "Bản tin hành trình",
        "subtitle": "Lưu lại cảm xúc, câu chuyện và những khoảnh khắc đáng nhớ.",
        "tabPosts": "Bản tin",
        "tabChat": "Trò chuyện",
        "postBtn": "Đăng bài viết",
        "statPosts": "Bài viết đã đăng",
        "statPostsCount": "bài viết",
        "statPostsEmpty": "Chưa có bài viết nào",
        "statMood": "Cảm xúc mới nhất",
        "statLastWrite": "Lần ghi gần nhất",
        "emptyDesc": "Ghi lại một khoảnh khắc để chuyến đi có câu chuyện riêng.",
        "formTitleAdd": "Đăng bài viết bản tin",
        "formTitleEdit": "Sửa bài viết bản tin",
        "cancel": "Hủy",
        "submit": "Đăng bài viết",
        "dateLabel": "Ngày ghi lại",
        "titleLabel": "Tiêu đề bài viết *",
        "titlePlaceholder": "VD: Một ngày đáng nhớ ở Vũng Tàu",
        "locLoading": "Đang lấy vị trí...",
        "locCurrent": "Đang ở",
        "locRemove": "Xóa vị trí",
        "locAttach": "Nhấn để đính kèm vị trí",
        "locUnknown": "Vị trí không xác định",
        "moodLabel": "Cảm xúc hôm nay",
        "contentLabel": "Câu chuyện của bạn *",
        "contentPlaceholder": "Ghi lại cảm xúc, câu chuyện, món ăn ngon hoặc khoảnh khắc đáng nhớ...",
        "imgUploading": "Đang tải ảnh...",
        "imgAttach": "Đính kèm hình ảnh",
        "promptTitle": "Gợi ý viết nhanh",
        "menuEdit": "Sửa",
        "menuDelete": "Xóa",
        "delConfirmTitle": "Xóa bài viết này?",
        "delConfirmDesc": "Bài viết sẽ không còn xuất hiện trên bản tin. Sau khi xóa, không thể hoàn tác.",
        "delConfirmBtn": "Xóa bài viết",
        "emptyTitle": "Chưa có bài viết nào",
        "emptySubtitle": "Bắt đầu bằng một cảm xúc, một nơi đã ghé qua hoặc một khoảnh khắc bạn muốn nhớ.",
        "writeNow": "Ghi lại ngay →",
        "reactionBtn": "Thả cảm xúc"
    },
    "en": {
        "title": "Journal",
        "subtitle": "Save your feelings, stories, and memorable moments.",
        "tabPosts": "Posts",
        "tabChat": "Chat",
        "postBtn": "Write a post",
        "statPosts": "Published Posts",
        "statPostsCount": "posts",
        "statPostsEmpty": "No posts yet",
        "statMood": "Latest Mood",
        "statLastWrite": "Last Written",
        "emptyDesc": "Record a moment to give your trip its own story.",
        "formTitleAdd": "Publish Journal Post",
        "formTitleEdit": "Edit Journal Post",
        "cancel": "Cancel",
        "submit": "Post",
        "dateLabel": "Date recorded",
        "titleLabel": "Post Title *",
        "titlePlaceholder": "Ex: A memorable day in Vung Tau",
        "locLoading": "Getting location...",
        "locCurrent": "Currently at",
        "locRemove": "Remove location",
        "locAttach": "Tap to attach location",
        "locUnknown": "Unknown location",
        "moodLabel": "Mood today",
        "contentLabel": "Your story *",
        "contentPlaceholder": "Record feelings, stories, delicious food, or memorable moments...",
        "imgUploading": "Uploading image...",
        "imgAttach": "Attach image",
        "promptTitle": "Quick writing suggestions",
        "menuEdit": "Edit",
        "menuDelete": "Delete",
        "delConfirmTitle": "Delete this post?",
        "delConfirmDesc": "The post will no longer appear on the journal. This action cannot be undone.",
        "delConfirmBtn": "Delete post",
        "emptyTitle": "No posts yet",
        "emptySubtitle": "Start with a feeling, a place you visited, or a moment you want to remember.",
        "writeNow": "Write now →",
        "reactionBtn": "React"
    },
    "zh": {
        "title": "行程日记",
        "subtitle": "保存您的感受、故事和难忘时刻。",
        "tabPosts": "帖子",
        "tabChat": "聊天",
        "postBtn": "写帖子",
        "statPosts": "已发布帖子",
        "statPostsCount": "篇帖子",
        "statPostsEmpty": "暂无帖子",
        "statMood": "最新心情",
        "statLastWrite": "最后记录",
        "emptyDesc": "记录一个时刻，给您的行程留下故事。",
        "formTitleAdd": "发布日记帖子",
        "formTitleEdit": "编辑日记帖子",
        "cancel": "取消",
        "submit": "发布",
        "dateLabel": "记录日期",
        "titleLabel": "帖子标题 *",
        "titlePlaceholder": "例如：头顿难忘的一天",
        "locLoading": "获取位置中...",
        "locCurrent": "当前位于",
        "locRemove": "删除位置",
        "locAttach": "点击以附加位置",
        "locUnknown": "未知位置",
        "moodLabel": "今天的心情",
        "contentLabel": "您的故事 *",
        "contentPlaceholder": "记录感受、故事、美食或难忘的时刻...",
        "imgUploading": "正在上传图片...",
        "imgAttach": "附加图片",
        "promptTitle": "快速写作建议",
        "menuEdit": "编辑",
        "menuDelete": "删除",
        "delConfirmTitle": "删除此帖子？",
        "delConfirmDesc": "帖子将不再显示在日记中。此操作无法撤消。",
        "delConfirmBtn": "删除帖子",
        "emptyTitle": "暂无帖子",
        "emptySubtitle": "从一种感觉、一个去过的地方或一个想记住的时刻开始。",
        "writeNow": "立即记录 →",
        "reactionBtn": "回应"
    },
    "es": {
        "title": "Diario",
        "subtitle": "Guarde sus sentimientos, historias y momentos memorables.",
        "tabPosts": "Publicaciones",
        "tabChat": "Chat",
        "postBtn": "Escribir publicación",
        "statPosts": "Publicadas",
        "statPostsCount": "publicaciones",
        "statPostsEmpty": "Aún no hay publicaciones",
        "statMood": "Último estado",
        "statLastWrite": "Último escrito",
        "emptyDesc": "Registre un momento para darle a su viaje su propia historia.",
        "formTitleAdd": "Publicar en diario",
        "formTitleEdit": "Editar en diario",
        "cancel": "Cancelar",
        "submit": "Publicar",
        "dateLabel": "Fecha registrada",
        "titleLabel": "Título de la publicación *",
        "titlePlaceholder": "Ej: Un día memorable en Vung Tau",
        "locLoading": "Obteniendo ubicación...",
        "locCurrent": "Actualmente en",
        "locRemove": "Eliminar ubicación",
        "locAttach": "Toca para adjuntar ubicación",
        "locUnknown": "Ubicación desconocida",
        "moodLabel": "Estado de ánimo hoy",
        "contentLabel": "Tu historia *",
        "contentPlaceholder": "Registra sentimientos, historias, comida deliciosa o momentos...",
        "imgUploading": "Subiendo imagen...",
        "imgAttach": "Adjuntar imagen",
        "promptTitle": "Sugerencias de escritura rápida",
        "menuEdit": "Editar",
        "menuDelete": "Eliminar",
        "delConfirmTitle": "¿Eliminar esta publicación?",
        "delConfirmDesc": "La publicación ya no aparecerá en el diario. Esta acción no se puede deshacer.",
        "delConfirmBtn": "Eliminar publicación",
        "emptyTitle": "Aún no hay publicaciones",
        "emptySubtitle": "Comienza con un sentimiento, un lugar que visitaste o un momento.",
        "writeNow": "Escribir ahora →",
        "reactionBtn": "Reaccionar"
    },
    "ja": {
        "title": "ジャーナル",
        "subtitle": "あなたの感情、物語、思い出に残る瞬間を保存します。",
        "tabPosts": "投稿",
        "tabChat": "チャット",
        "postBtn": "投稿する",
        "statPosts": "公開済みの投稿",
        "statPostsCount": "件の投稿",
        "statPostsEmpty": "まだ投稿がありません",
        "statMood": "最新の気分",
        "statLastWrite": "最後に書いた",
        "emptyDesc": "旅に独自のストーリーを与えるために瞬間を記録します。",
        "formTitleAdd": "投稿を追加",
        "formTitleEdit": "投稿を編集",
        "cancel": "キャンセル",
        "submit": "投稿",
        "dateLabel": "記録日",
        "titleLabel": "タイトル *",
        "titlePlaceholder": "例：ブンタウでの思い出の日",
        "locLoading": "場所を取得中...",
        "locCurrent": "現在地",
        "locRemove": "場所を削除",
        "locAttach": "タップして場所を添付",
        "locUnknown": "不明な場所",
        "moodLabel": "今日の気分",
        "contentLabel": "あなたの物語 *",
        "contentPlaceholder": "感情、物語、おいしい食べ物、思い出の瞬間を記録します...",
        "imgUploading": "画像をアップロード中...",
        "imgAttach": "画像を添付",
        "promptTitle": "クイックライティングの提案",
        "menuEdit": "編集",
        "menuDelete": "削除",
        "delConfirmTitle": "この投稿を削除しますか？",
        "delConfirmDesc": "投稿はジャーナルに表示されなくなります。元に戻すことはできません。",
        "delConfirmBtn": "投稿を削除",
        "emptyTitle": "投稿なし",
        "emptySubtitle": "感情、訪れた場所、思い出したい瞬間から始めましょう。",
        "writeNow": "今すぐ書く →",
        "reactionBtn": "反応する"
    },
    "pt": {
        "title": "Diário",
        "subtitle": "Guarde seus sentimentos, histórias e momentos memoráveis.",
        "tabPosts": "Postagens",
        "tabChat": "Bate-papo",
        "postBtn": "Escrever postagem",
        "statPosts": "Postagens",
        "statPostsCount": "postagens",
        "statPostsEmpty": "Nenhuma postagem ainda",
        "statMood": "Último humor",
        "statLastWrite": "Último escrito",
        "emptyDesc": "Grave um momento para dar à sua viagem sua própria história.",
        "formTitleAdd": "Publicar no diário",
        "formTitleEdit": "Editar no diário",
        "cancel": "Cancelar",
        "submit": "Publicar",
        "dateLabel": "Data registrada",
        "titleLabel": "Título da postagem *",
        "titlePlaceholder": "Ex: Um dia memorável em Vung Tau",
        "locLoading": "Obtendo localização...",
        "locCurrent": "Atualmente em",
        "locRemove": "Remover localização",
        "locAttach": "Toque para anexar localização",
        "locUnknown": "Localização desconhecida",
        "moodLabel": "Humor de hoje",
        "contentLabel": "Sua história *",
        "contentPlaceholder": "Grave sentimentos, histórias, comida deliciosa ou momentos...",
        "imgUploading": "Enviando imagem...",
        "imgAttach": "Anexar imagem",
        "promptTitle": "Sugestões de escrita rápida",
        "menuEdit": "Editar",
        "menuDelete": "Excluir",
        "delConfirmTitle": "Excluir esta postagem?",
        "delConfirmDesc": "A postagem não aparecerá mais no diário. Não pode ser desfeito.",
        "delConfirmBtn": "Excluir postagem",
        "emptyTitle": "Nenhuma postagem ainda",
        "emptySubtitle": "Comece com um sentimento, um lugar que visitou ou um momento.",
        "writeNow": "Escrever agora →",
        "reactionBtn": "Reagir"
    },
    "ko": {
        "title": "저널",
        "subtitle": "당신의 감정, 이야기, 기억에 남는 순간을 저장하세요.",
        "tabPosts": "게시물",
        "tabChat": "채팅",
        "postBtn": "게시물 작성",
        "statPosts": "게시물 수",
        "statPostsCount": "게시물",
        "statPostsEmpty": "게시물 없음",
        "statMood": "최근 기분",
        "statLastWrite": "최근 기록",
        "emptyDesc": "여행의 이야기를 남기기 위해 순간을 기록하세요.",
        "formTitleAdd": "게시물 작성",
        "formTitleEdit": "게시물 수정",
        "cancel": "취소",
        "submit": "게시",
        "dateLabel": "기록 날짜",
        "titleLabel": "제목 *",
        "titlePlaceholder": "예: 붕따우에서의 기억에 남는 하루",
        "locLoading": "위치 가져오는 중...",
        "locCurrent": "현재 위치",
        "locRemove": "위치 삭제",
        "locAttach": "탭하여 위치 첨부",
        "locUnknown": "알 수 없는 위치",
        "moodLabel": "오늘의 기분",
        "contentLabel": "당신의 이야기 *",
        "contentPlaceholder": "감정, 이야기, 맛있는 음식, 기억에 남는 순간을 기록하세요...",
        "imgUploading": "이미지 업로드 중...",
        "imgAttach": "이미지 첨부",
        "promptTitle": "빠른 글쓰기 제안",
        "menuEdit": "수정",
        "menuDelete": "삭제",
        "delConfirmTitle": "이 게시물을 삭제하시겠습니까?",
        "delConfirmDesc": "게시물이 더 이상 저널에 표시되지 않습니다. 이 작업은 취소할 수 없습니다.",
        "delConfirmBtn": "게시물 삭제",
        "emptyTitle": "게시물 없음",
        "emptySubtitle": "느낌, 방문한 장소, 또는 기억하고 싶은 순간으로 시작하세요.",
        "writeNow": "지금 쓰기 →",
        "reactionBtn": "반응 남기기"
    },
    "th": {
        "title": "ไดอารี่",
        "subtitle": "บันทึกความรู้สึก เรื่องราว และช่วงเวลาที่น่าจดจำ",
        "tabPosts": "โพสต์",
        "tabChat": "แชท",
        "postBtn": "เขียนโพสต์",
        "statPosts": "โพสต์ทั้งหมด",
        "statPostsCount": "โพสต์",
        "statPostsEmpty": "ยังไม่มีโพสต์",
        "statMood": "อารมณ์ล่าสุด",
        "statLastWrite": "เขียนล่าสุด",
        "emptyDesc": "บันทึกช่วงเวลาเพื่อให้ทริปของคุณมีเรื่องราวของตัวเอง",
        "formTitleAdd": "สร้างโพสต์",
        "formTitleEdit": "แก้ไขโพสต์",
        "cancel": "ยกเลิก",
        "submit": "โพสต์",
        "dateLabel": "วันที่บันทึก",
        "titleLabel": "หัวข้อโพสต์ *",
        "titlePlaceholder": "เช่น วันที่น่าจดจำในหวุงเต่า",
        "locLoading": "กำลังค้นหาตำแหน่ง...",
        "locCurrent": "ขณะนี้อยู่ที่",
        "locRemove": "ลบตำแหน่ง",
        "locAttach": "แตะเพื่อแนบตำแหน่ง",
        "locUnknown": "ไม่ทราบตำแหน่ง",
        "moodLabel": "อารมณ์วันนี้",
        "contentLabel": "เรื่องราวของคุณ *",
        "contentPlaceholder": "บันทึกความรู้สึก เรื่องราว อาหารอร่อย หรือช่วงเวลา...",
        "imgUploading": "กำลังอัปโหลดรูปภาพ...",
        "imgAttach": "แนบรูปภาพ",
        "promptTitle": "ข้อเสนอแนะในการเขียน",
        "menuEdit": "แก้ไข",
        "menuDelete": "ลบ",
        "delConfirmTitle": "ลบโพสต์นี้หรือไม่",
        "delConfirmDesc": "โพสต์จะไม่ปรากฏในไดอารี่อีกต่อไป การดำเนินการนี้ไม่สามารถยกเลิกได้",
        "delConfirmBtn": "ลบโพสต์",
        "emptyTitle": "ยังไม่มีโพสต์",
        "emptySubtitle": "เริ่มต้นด้วยความรู้สึก สถานที่ที่ไป หรือช่วงเวลาที่คุณต้องการจดจำ",
        "writeNow": "เขียนเลย →",
        "reactionBtn": "แสดงความรู้สึก"
    },
    "de": {
        "title": "Tagebuch",
        "subtitle": "Speichern Sie Gefühle, Geschichten und unvergessliche Momente.",
        "tabPosts": "Beiträge",
        "tabChat": "Chat",
        "postBtn": "Beitrag schreiben",
        "statPosts": "Veröffentlicht",
        "statPostsCount": "Beiträge",
        "statPostsEmpty": "Noch keine Beiträge",
        "statMood": "Letzte Stimmung",
        "statLastWrite": "Zuletzt geschrieben",
        "emptyDesc": "Halten Sie einen Moment fest, um Ihrer Reise eine eigene Geschichte zu geben.",
        "formTitleAdd": "Beitrag veröffentlichen",
        "formTitleEdit": "Beitrag bearbeiten",
        "cancel": "Abbrechen",
        "submit": "Veröffentlichen",
        "dateLabel": "Aufgezeichnet am",
        "titleLabel": "Titel *",
        "titlePlaceholder": "Z.B.: Ein unvergesslicher Tag in Vung Tau",
        "locLoading": "Ort wird ermittelt...",
        "locCurrent": "Aktuell in",
        "locRemove": "Ort entfernen",
        "locAttach": "Tippen, um Ort hinzuzufügen",
        "locUnknown": "Unbekannter Ort",
        "moodLabel": "Stimmung heute",
        "contentLabel": "Ihre Geschichte *",
        "contentPlaceholder": "Gefühle, Geschichten, leckeres Essen oder Momente aufzeichnen...",
        "imgUploading": "Bild wird hochgeladen...",
        "imgAttach": "Bild anhängen",
        "promptTitle": "Schreibvorschläge",
        "menuEdit": "Bearbeiten",
        "menuDelete": "Löschen",
        "delConfirmTitle": "Diesen Beitrag löschen?",
        "delConfirmDesc": "Der Beitrag wird nicht mehr im Tagebuch angezeigt. Dies kann nicht rückgängig gemacht werden.",
        "delConfirmBtn": "Beitrag löschen",
        "emptyTitle": "Noch keine Beiträge",
        "emptySubtitle": "Beginnen Sie mit einem Gefühl, einem besuchten Ort oder einem Moment.",
        "writeNow": "Jetzt schreiben →",
        "reactionBtn": "Reagieren"
    },
    "fr": {
        "title": "Journal",
        "subtitle": "Sauvegardez vos sentiments, histoires et moments mémorables.",
        "tabPosts": "Publications",
        "tabChat": "Discussion",
        "postBtn": "Écrire",
        "statPosts": "Publications",
        "statPostsCount": "publications",
        "statPostsEmpty": "Aucune publication",
        "statMood": "Dernière humeur",
        "statLastWrite": "Dernier écrit",
        "emptyDesc": "Enregistrez un moment pour donner à votre voyage sa propre histoire.",
        "formTitleAdd": "Publier dans le journal",
        "formTitleEdit": "Modifier la publication",
        "cancel": "Annuler",
        "submit": "Publier",
        "dateLabel": "Date enregistrée",
        "titleLabel": "Titre *",
        "titlePlaceholder": "Ex: Une journée mémorable à Vung Tau",
        "locLoading": "Obtention de l'emplacement...",
        "locCurrent": "Actuellement à",
        "locRemove": "Supprimer l'emplacement",
        "locAttach": "Appuyez pour ajouter l'emplacement",
        "locUnknown": "Emplacement inconnu",
        "moodLabel": "Humeur aujourd'hui",
        "contentLabel": "Votre histoire *",
        "contentPlaceholder": "Enregistrez des sentiments, des histoires, de la nourriture...",
        "imgUploading": "Téléchargement d'image...",
        "imgAttach": "Joindre l'image",
        "promptTitle": "Suggestions d'écriture",
        "menuEdit": "Modifier",
        "menuDelete": "Supprimer",
        "delConfirmTitle": "Supprimer cette publication ?",
        "delConfirmDesc": "La publication n'apparaîtra plus dans le journal. Irréversible.",
        "delConfirmBtn": "Supprimer",
        "emptyTitle": "Aucune publication",
        "emptySubtitle": "Commencez par un sentiment, un lieu visité ou un moment.",
        "writeNow": "Écrire maintenant →",
        "reactionBtn": "Réagir"
    },
    "ru": {
        "title": "Дневник",
        "subtitle": "Сохраняйте свои чувства, истории и памятные моменты.",
        "tabPosts": "Посты",
        "tabChat": "Чат",
        "postBtn": "Написать пост",
        "statPosts": "Опубликовано",
        "statPostsCount": "постов",
        "statPostsEmpty": "Пока нет постов",
        "statMood": "Настроение",
        "statLastWrite": "Последняя запись",
        "emptyDesc": "Запишите момент, чтобы у вашей поездки была своя история.",
        "formTitleAdd": "Опубликовать пост",
        "formTitleEdit": "Редактировать пост",
        "cancel": "Отмена",
        "submit": "Опубликовать",
        "dateLabel": "Дата записи",
        "titleLabel": "Заголовок *",
        "titlePlaceholder": "Например: Памятный день в Вунгтау",
        "locLoading": "Определение местоположения...",
        "locCurrent": "Сейчас в",
        "locRemove": "Удалить место",
        "locAttach": "Нажмите, чтобы добавить место",
        "locUnknown": "Неизвестное место",
        "moodLabel": "Настроение сегодня",
        "contentLabel": "Ваша история *",
        "contentPlaceholder": "Запишите чувства, истории, вкусную еду или моменты...",
        "imgUploading": "Загрузка изображения...",
        "imgAttach": "Прикрепить изображение",
        "promptTitle": "Быстрые подсказки для письма",
        "menuEdit": "Изменить",
        "menuDelete": "Удалить",
        "delConfirmTitle": "Удалить этот пост?",
        "delConfirmDesc": "Пост больше не будет отображаться в дневнике. Это нельзя отменить.",
        "delConfirmBtn": "Удалить пост",
        "emptyTitle": "Пока нет постов",
        "emptySubtitle": "Начните с чувства, места, которое вы посетили, или момента.",
        "writeNow": "Написать сейчас →",
        "reactionBtn": "Реагировать"
    },
    "ar": {
        "title": "يوميات",
        "subtitle": "احفظ مشاعرك وقصصك ولحظاتك التي لا تنسى.",
        "tabPosts": "المنشورات",
        "tabChat": "دردشة",
        "postBtn": "كتابة منشور",
        "statPosts": "المنشورات",
        "statPostsCount": "منشورات",
        "statPostsEmpty": "لا توجد منشورات",
        "statMood": "آخر مزاج",
        "statLastWrite": "آخر كتابة",
        "emptyDesc": "سجل لحظة لتمنح رحلتك قصتها الخاصة.",
        "formTitleAdd": "نشر في اليوميات",
        "formTitleEdit": "تعديل المنشور",
        "cancel": "إلغاء",
        "submit": "نشر",
        "dateLabel": "تاريخ التسجيل",
        "titleLabel": "عنوان المنشور *",
        "titlePlaceholder": "مثال: يوم لا ينسى في فونج تاو",
        "locLoading": "الحصول على الموقع...",
        "locCurrent": "حاليا في",
        "locRemove": "إزالة الموقع",
        "locAttach": "اضغط لإرفاق الموقع",
        "locUnknown": "موقع غير معروف",
        "moodLabel": "المزاج اليوم",
        "contentLabel": "قصتك *",
        "contentPlaceholder": "سجل مشاعرك أو قصصك أو الطعام اللذيذ أو اللحظات...",
        "imgUploading": "جاري رفع الصورة...",
        "imgAttach": "إرفاق صورة",
        "promptTitle": "اقتراحات الكتابة السريعة",
        "menuEdit": "تعديل",
        "menuDelete": "حذف",
        "delConfirmTitle": "حذف هذا المنشور؟",
        "delConfirmDesc": "لن يظهر المنشور في اليوميات بعد الآن. لا يمكن التراجع عن هذا الإجراء.",
        "delConfirmBtn": "حذف المنشور",
        "emptyTitle": "لا توجد منشورات",
        "emptySubtitle": "ابدأ بشعور أو مكان زرته أو لحظة.",
        "writeNow": "اكتب الآن →",
        "reactionBtn": "تفاعل"
    }
}

def translate_journal():
    locales_dir = "src/locales"
    for lang, trans in translations.items():
        filepath = os.path.join(locales_dir, f"{lang}.json")
        if not os.path.exists(filepath):
            # Fallback to english if language doesn't exist
            trans = translations["en"]
            
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
                
            if "journal" not in data:
                data["journal"] = {}
                
            for k, v in trans.items():
                data["journal"][k] = v
                
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Error on {lang}: {e}")

if __name__ == "__main__":
    translate_journal()
