import json
import os

locales_dir = 'src/locales'
translations = {
    "vi": {
        "toast": {
            "invalidFileFormat": "Định dạng file KAT Journey không hợp lệ.",
            "cantReadFile": "Không thể đọc file. Đảm bảo đây là file .katjourney.",
            "importSuccess": "Nhập chuyến đi thành công!",
            "importError": "Không thể nhập file: {{message}}",
            "pushNotifEnabled": "Đã bật thông báo đẩy thành công!",
            "pushNotifDenied": "Từ chối quyền thông báo. Vui lòng bật trong cài đặt trình duyệt.",
            "inAppNotifEnabled": "Đã bật thông báo trong ứng dụng.",
            "inAppNotifDisabled": "Đã tắt thông báo trong ứng dụng.",
            "gpsAutoEnabled": "Đã bật tự động truy cập GPS.",
            "gpsAutoDisabled": "Đã tắt tự động truy cập GPS.",
            "expenseDeleted": "Đã xóa chi phí",
            "supabaseNotConfigured": "Chưa cấu hình Supabase. Vui lòng kiểm tra biến môi trường.",
            "supabaseError": "Không thể kết nối Supabase: {{message}}",
            "shareLinkCreateError": "Lỗi tạo link chia sẻ. Vui lòng thử lại sau.",
            "syncSuccess": "Đã đồng bộ dữ liệu chia sẻ.",
            "syncError": "Lỗi đồng bộ dữ liệu. Vui lòng thử lại sau.",
            "shareLinkDisabled": "Đã tắt link chia sẻ.",
            "shareLinkDisableError": "Lỗi tắt link chia sẻ. Vui lòng thử lại sau.",
            "deleteDataSuccess": "Xóa dữ liệu thành công. Đang tải lại trang...",
            "deleteDataError": "Đã xảy ra lỗi khi xóa dữ liệu.",
            "changesApplied": "Đã áp dụng thay đổi vào chuyến đi.",
            "approveError": "Lỗi đồng ý: {{message}}",
            "requestRejected": "Đã từ chối yêu cầu chỉnh sửa.",
            "rejectError": "Lỗi từ chối: {{message}}",
            "allAppliedSuccess": "Đã áp dụng thành công {{successCount}} thay đổi vào chuyến đi.",
            "partialApplied": "Đã áp dụng {{successCount}} thay đổi. Lỗi {{failCount}} yêu cầu.",
            "allRejectedSuccess": "Đã từ chối thành công tất cả {{successCount}} yêu cầu chỉnh sửa.",
            "partialRejected": "Đã từ chối {{successCount}} yêu cầu. Lỗi {{failCount}} yêu cầu.",
            "activityRequireName": "Vui lòng nhập tên hoạt động và chọn ngày.",
            "updateError": "Lỗi cập nhật: {{message}}",
            "submitRequestError": "Lỗi gửi yêu cầu: {{message}}",
            "directDelete": "Đã xóa trực tiếp!",
            "requestSent": "Đã gửi yêu cầu. Chủ chuyến đi sẽ xem xét và phản hồi.",
            "deleteError": "Lỗi xóa: {{message}}",
            "backupRequireName": "Vui lòng nhập tên phương án dự phòng",
            "statusUpdated": "Đã cập nhật trạng thái!",
            "errorMsg": "Lỗi: {{message}}",
            "tripNotFound": "Lỗi: Không tìm thấy chuyến đi",
            "personalPreparationUpdated": "Đã cập nhật chuẩn bị cá nhân!",
            "personalPreparationAdded": "Đã thêm chuẩn bị cá nhân!",
            "saveError": "Lỗi khi lưu: {{message}}",
            "personalDocUpdated": "Đã cập nhật giấy tờ cá nhân",
            "personalDocAdded": "Đã thêm giấy tờ cá nhân",
            "personalDocDeleted": "Đã xóa giấy tờ cá nhân!",
            "uploadError": "Lỗi tải ảnh lên. Vui lòng thử lại.",
            "locationError": "Không thể lấy vị trí.",
            "postDeleted": "Đã xóa bài viết.",
            "requireRole": "Vui lòng chọn vai trò mới.",
            "roleRequestSent": "Đã gửi yêu cầu đổi vai trò. Trưởng nhóm sẽ duyệt.",
            "memberAddRequestSent": "Đã gửi yêu cầu thêm thành viên. Trưởng nhóm sẽ duyệt.",
            "memberDeleteRequestSent": "Đã gửi yêu cầu xóa thành viên."
        }
    },
    "es": {
        "toast": {
            "invalidFileFormat": "Formato de archivo de KAT Journey no válido.",
            "cantReadFile": "No se puede leer el archivo. Asegúrese de que sea un archivo .katjourney.",
            "importSuccess": "¡Viaje importado exitosamente!",
            "importError": "No se puede importar el archivo: {{message}}",
            "pushNotifEnabled": "¡Notificaciones push habilitadas exitosamente!",
            "pushNotifDenied": "Permiso de notificación denegado. Habilítelo en la configuración del navegador.",
            "inAppNotifEnabled": "Notificaciones en la aplicación habilitadas.",
            "inAppNotifDisabled": "Notificaciones en la aplicación deshabilitadas.",
            "gpsAutoEnabled": "Acceso automático al GPS habilitado.",
            "gpsAutoDisabled": "Acceso automático al GPS deshabilitado.",
            "expenseDeleted": "Gasto eliminado",
            "supabaseNotConfigured": "Supabase no configurado. Verifique las variables de entorno.",
            "supabaseError": "No se puede conectar a Supabase: {{message}}",
            "shareLinkCreateError": "Error al crear el enlace para compartir. Inténtelo de nuevo más tarde.",
            "syncSuccess": "Datos compartidos sincronizados.",
            "syncError": "Error al sincronizar datos. Inténtelo de nuevo más tarde.",
            "shareLinkDisabled": "Enlace para compartir deshabilitado.",
            "shareLinkDisableError": "Error al deshabilitar el enlace para compartir. Inténtelo de nuevo más tarde.",
            "deleteDataSuccess": "Datos eliminados exitosamente. Recargando la página...",
            "deleteDataError": "Ocurrió un error al eliminar los datos.",
            "changesApplied": "Cambios aplicados al viaje.",
            "approveError": "Error al aprobar: {{message}}",
            "requestRejected": "Solicitud de edición rechazada.",
            "rejectError": "Error al rechazar: {{message}}",
            "allAppliedSuccess": "Se aplicaron con éxito todos los {{successCount}} cambios al viaje.",
            "partialApplied": "Se aplicaron {{successCount}} cambios. Fallaron {{failCount}} solicitudes.",
            "allRejectedSuccess": "Se rechazaron con éxito todas las {{successCount}} solicitudes de edición.",
            "partialRejected": "Se rechazaron {{successCount}} solicitudes. Fallaron {{failCount}} solicitudes.",
            "activityRequireName": "Por favor ingrese el nombre de la actividad y seleccione la fecha.",
            "updateError": "Error de actualización: {{message}}",
            "submitRequestError": "Error al enviar la solicitud: {{message}}",
            "directDelete": "¡Eliminado directamente!",
            "requestSent": "Solicitud enviada. El propietario del viaje la revisará y responderá.",
            "deleteError": "Error de eliminación: {{message}}",
            "backupRequireName": "Por favor ingrese el nombre del plan de respaldo",
            "statusUpdated": "¡Estado actualizado!",
            "errorMsg": "Error: {{message}}",
            "tripNotFound": "Error: Viaje no encontrado",
            "personalPreparationUpdated": "¡Preparación personal actualizada!",
            "personalPreparationAdded": "¡Preparación personal agregada!",
            "saveError": "Error al guardar: {{message}}",
            "personalDocUpdated": "Documento personal actualizado",
            "personalDocAdded": "Documento personal agregado",
            "personalDocDeleted": "¡Documento personal eliminado!",
            "uploadError": "Error al subir la imagen. Inténtelo de nuevo.",
            "locationError": "No se pudo obtener la ubicación.",
            "postDeleted": "Publicación eliminada.",
            "requireRole": "Por favor, seleccione un nuevo rol.",
            "roleRequestSent": "Solicitud de cambio de rol enviada. El líder del grupo la aprobará.",
            "memberAddRequestSent": "Solicitud para agregar miembro enviada. El líder del grupo la aprobará.",
            "memberDeleteRequestSent": "Solicitud para eliminar miembro enviada."
        }
    },
    "fr": {
        "toast": {
            "invalidFileFormat": "Format de fichier KAT Journey non valide.",
            "cantReadFile": "Impossible de lire le fichier. Assurez-vous qu'il s'agit d'un fichier .katjourney.",
            "importSuccess": "Voyage importé avec succès !",
            "importError": "Impossible d'importer le fichier : {{message}}",
            "pushNotifEnabled": "Notifications push activées avec succès !",
            "pushNotifDenied": "Autorisation de notification refusée. Veuillez l'activer dans les paramètres du navigateur.",
            "inAppNotifEnabled": "Notifications dans l'application activées.",
            "inAppNotifDisabled": "Notifications dans l'application désactivées.",
            "gpsAutoEnabled": "Accès GPS automatique activé.",
            "gpsAutoDisabled": "Accès GPS automatique désactivé.",
            "expenseDeleted": "Dépense supprimée",
            "supabaseNotConfigured": "Supabase non configuré. Veuillez vérifier les variables d'environnement.",
            "supabaseError": "Impossible de se connecter à Supabase : {{message}}",
            "shareLinkCreateError": "Erreur lors de la création du lien de partage. Veuillez réessayer plus tard.",
            "syncSuccess": "Données partagées synchronisées.",
            "syncError": "Erreur lors de la synchronisation des données. Veuillez réessayer plus tard.",
            "shareLinkDisabled": "Lien de partage désactivé.",
            "shareLinkDisableError": "Erreur lors de la désactivation du lien de partage. Veuillez réessayer plus tard.",
            "deleteDataSuccess": "Données supprimées avec succès. Rechargement de la page...",
            "deleteDataError": "Une erreur est survenue lors de la suppression des données.",
            "changesApplied": "Modifications appliquées au voyage.",
            "approveError": "Erreur lors de l'approbation : {{message}}",
            "requestRejected": "Demande de modification rejetée.",
            "rejectError": "Erreur lors du rejet : {{message}}",
            "allAppliedSuccess": "{{successCount}} modifications appliquées avec succès au voyage.",
            "partialApplied": "{{successCount}} modifications appliquées. {{failCount}} demandes ont échoué.",
            "allRejectedSuccess": "{{successCount}} demandes de modification rejetées avec succès.",
            "partialRejected": "{{successCount}} demandes rejetées. {{failCount}} demandes ont échoué.",
            "activityRequireName": "Veuillez entrer le nom de l'activité et sélectionner la date.",
            "updateError": "Erreur de mise à jour : {{message}}",
            "submitRequestError": "Erreur lors de la soumission de la demande : {{message}}",
            "directDelete": "Supprimé directement !",
            "requestSent": "Demande envoyée. Le propriétaire du voyage l'examinera et répondra.",
            "deleteError": "Erreur de suppression : {{message}}",
            "backupRequireName": "Veuillez entrer le nom du plan de secours",
            "statusUpdated": "Statut mis à jour !",
            "errorMsg": "Erreur : {{message}}",
            "tripNotFound": "Erreur : Voyage introuvable",
            "personalPreparationUpdated": "Préparation personnelle mise à jour !",
            "personalPreparationAdded": "Préparation personnelle ajoutée !",
            "saveError": "Erreur lors de l'enregistrement : {{message}}",
            "personalDocUpdated": "Document personnel mis à jour",
            "personalDocAdded": "Document personnel ajouté",
            "personalDocDeleted": "Document personnel supprimé !",
            "uploadError": "Erreur lors du téléchargement de l'image. Veuillez réessayer.",
            "locationError": "Impossible d'obtenir l'emplacement.",
            "postDeleted": "Publication supprimée.",
            "requireRole": "Veuillez sélectionner un nouveau rôle.",
            "roleRequestSent": "Demande de changement de rôle envoyée. Le chef de groupe l'approuvera.",
            "memberAddRequestSent": "Demande d'ajout de membre envoyée. Le chef de groupe l'approuvera.",
            "memberDeleteRequestSent": "Demande de suppression de membre envoyée."
        }
    },
    "de": {
        "toast": {
            "invalidFileFormat": "Ungültiges Dateiformat für KAT Journey.",
            "cantReadFile": "Datei kann nicht gelesen werden. Stellen Sie sicher, dass es sich um eine .katjourney-Datei handelt.",
            "importSuccess": "Reise erfolgreich importiert!",
            "importError": "Datei kann nicht importiert werden: {{message}}",
            "pushNotifEnabled": "Push-Benachrichtigungen erfolgreich aktiviert!",
            "pushNotifDenied": "Benachrichtigungsberechtigung verweigert. Bitte aktivieren Sie diese in den Browsereinstellungen.",
            "inAppNotifEnabled": "In-App-Benachrichtigungen aktiviert.",
            "inAppNotifDisabled": "In-App-Benachrichtigungen deaktiviert.",
            "gpsAutoEnabled": "Automatischer GPS-Zugriff aktiviert.",
            "gpsAutoDisabled": "Automatischer GPS-Zugriff deaktiviert.",
            "expenseDeleted": "Ausgabe gelöscht",
            "supabaseNotConfigured": "Supabase nicht konfiguriert. Bitte überprüfen Sie die Umgebungsvariablen.",
            "supabaseError": "Verbindung zu Supabase kann nicht hergestellt werden: {{message}}",
            "shareLinkCreateError": "Fehler beim Erstellen des Freigabelinks. Bitte versuchen Sie es später noch einmal.",
            "syncSuccess": "Geteilte Daten synchronisiert.",
            "syncError": "Fehler beim Synchronisieren der Daten. Bitte versuchen Sie es später noch einmal.",
            "shareLinkDisabled": "Freigabelink deaktiviert.",
            "shareLinkDisableError": "Fehler beim Deaktivieren des Freigabelinks. Bitte versuchen Sie es später noch einmal.",
            "deleteDataSuccess": "Daten erfolgreich gelöscht. Seite wird neu geladen...",
            "deleteDataError": "Beim Löschen der Daten ist ein Fehler aufgetreten.",
            "changesApplied": "Änderungen an der Reise übernommen.",
            "approveError": "Fehler beim Genehmigen: {{message}}",
            "requestRejected": "Bearbeitungsanfrage abgelehnt.",
            "rejectError": "Fehler beim Ablehnen: {{message}}",
            "allAppliedSuccess": "Alle {{successCount}} Änderungen erfolgreich auf die Reise angewendet.",
            "partialApplied": "{{successCount}} Änderungen angewendet. {{failCount}} Anfragen fehlgeschlagen.",
            "allRejectedSuccess": "Alle {{successCount}} Bearbeitungsanfragen erfolgreich abgelehnt.",
            "partialRejected": "{{successCount}} Anfragen abgelehnt. {{failCount}} Anfragen fehlgeschlagen.",
            "activityRequireName": "Bitte geben Sie den Namen der Aktivität ein und wählen Sie ein Datum aus.",
            "updateError": "Aktualisierungsfehler: {{message}}",
            "submitRequestError": "Fehler beim Senden der Anfrage: {{message}}",
            "directDelete": "Direkt gelöscht!",
            "requestSent": "Anfrage gesendet. Der Reiseveranstalter wird diese prüfen und antworten.",
            "deleteError": "Löschfehler: {{message}}",
            "backupRequireName": "Bitte geben Sie den Namen des Backup-Plans ein",
            "statusUpdated": "Status aktualisiert!",
            "errorMsg": "Fehler: {{message}}",
            "tripNotFound": "Fehler: Reise nicht gefunden",
            "personalPreparationUpdated": "Persönliche Vorbereitung aktualisiert!",
            "personalPreparationAdded": "Persönliche Vorbereitung hinzugefügt!",
            "saveError": "Fehler beim Speichern: {{message}}",
            "personalDocUpdated": "Persönliches Dokument aktualisiert",
            "personalDocAdded": "Persönliches Dokument hinzugefügt",
            "personalDocDeleted": "Persönliches Dokument gelöscht!",
            "uploadError": "Fehler beim Hochladen des Bildes. Bitte versuchen Sie es erneut.",
            "locationError": "Standort konnte nicht ermittelt werden.",
            "postDeleted": "Beitrag gelöscht.",
            "requireRole": "Bitte wählen Sie eine neue Rolle.",
            "roleRequestSent": "Anfrage zur Rollenänderung gesendet. Der Gruppenleiter wird dies genehmigen.",
            "memberAddRequestSent": "Anfrage zum Hinzufügen eines Mitglieds gesendet. Der Gruppenleiter wird dies genehmigen.",
            "memberDeleteRequestSent": "Anfrage zum Löschen eines Mitglieds gesendet."
        }
    },
    "it": {
        "toast": {
            "invalidFileFormat": "Formato file KAT Journey non valido.",
            "cantReadFile": "Impossibile leggere il file. Assicurati che sia un file .katjourney.",
            "importSuccess": "Viaggio importato con successo!",
            "importError": "Impossibile importare il file: {{message}}",
            "pushNotifEnabled": "Notifiche push abilitate con successo!",
            "pushNotifDenied": "Permesso di notifica negato. Abilitalo nelle impostazioni del browser.",
            "inAppNotifEnabled": "Notifiche in-app abilitate.",
            "inAppNotifDisabled": "Notifiche in-app disabilitate.",
            "gpsAutoEnabled": "Accesso automatico al GPS abilitato.",
            "gpsAutoDisabled": "Accesso automatico al GPS disabilitato.",
            "expenseDeleted": "Spesa eliminata",
            "supabaseNotConfigured": "Supabase non configurato. Controlla le variabili d'ambiente.",
            "supabaseError": "Impossibile connettersi a Supabase: {{message}}",
            "shareLinkCreateError": "Errore durante la creazione del link di condivisione. Riprova più tardi.",
            "syncSuccess": "Dati condivisi sincronizzati.",
            "syncError": "Errore durante la sincronizzazione dei dati. Riprova più tardi.",
            "shareLinkDisabled": "Link di condivisione disabilitato.",
            "shareLinkDisableError": "Errore durante la disabilitazione del link di condivisione. Riprova più tardi.",
            "deleteDataSuccess": "Dati eliminati con successo. Ricaricamento della pagina...",
            "deleteDataError": "Si è verificato un errore durante l'eliminazione dei dati.",
            "changesApplied": "Modifiche applicate al viaggio.",
            "approveError": "Errore durante l'approvazione: {{message}}",
            "requestRejected": "Richiesta di modifica rifiutata.",
            "rejectError": "Errore durante il rifiuto: {{message}}",
            "allAppliedSuccess": "Tutte le {{successCount}} modifiche applicate con successo al viaggio.",
            "partialApplied": "Applicate {{successCount}} modifiche. {{failCount}} richieste non riuscite.",
            "allRejectedSuccess": "Tutte le {{successCount}} richieste di modifica rifiutate con successo.",
            "partialRejected": "{{successCount}} richieste rifiutate. {{failCount}} richieste non riuscite.",
            "activityRequireName": "Inserisci il nome dell'attività e seleziona la data.",
            "updateError": "Errore di aggiornamento: {{message}}",
            "submitRequestError": "Errore durante l'invio della richiesta: {{message}}",
            "directDelete": "Eliminato direttamente!",
            "requestSent": "Richiesta inviata. L'organizzatore del viaggio esaminerà e risponderà.",
            "deleteError": "Errore di eliminazione: {{message}}",
            "backupRequireName": "Inserisci il nome del piano di riserva",
            "statusUpdated": "Stato aggiornato!",
            "errorMsg": "Errore: {{message}}",
            "tripNotFound": "Errore: Viaggio non trovato",
            "personalPreparationUpdated": "Preparazione personale aggiornata!",
            "personalPreparationAdded": "Preparazione personale aggiunta!",
            "saveError": "Errore durante il salvataggio: {{message}}",
            "personalDocUpdated": "Documento personale aggiornato",
            "personalDocAdded": "Documento personale aggiunto",
            "personalDocDeleted": "Documento personale eliminato!",
            "uploadError": "Errore durante il caricamento dell'immagine. Riprova.",
            "locationError": "Impossibile ottenere la posizione.",
            "postDeleted": "Post eliminato.",
            "requireRole": "Seleziona un nuovo ruolo.",
            "roleRequestSent": "Richiesta di cambio ruolo inviata. Il capogruppo approverà.",
            "memberAddRequestSent": "Richiesta di aggiunta membro inviata. Il capogruppo approverà.",
            "memberDeleteRequestSent": "Richiesta di eliminazione membro inviata."
        }
    },
    "pt": {
        "toast": {
            "invalidFileFormat": "Formato de arquivo KAT Journey inválido.",
            "cantReadFile": "Não foi possível ler o arquivo. Certifique-se de que é um arquivo .katjourney.",
            "importSuccess": "Viagem importada com sucesso!",
            "importError": "Não foi possível importar o arquivo: {{message}}",
            "pushNotifEnabled": "Notificações push ativadas com sucesso!",
            "pushNotifDenied": "Permissão de notificação negada. Habilite-a nas configurações do navegador.",
            "inAppNotifEnabled": "Notificações no aplicativo ativadas.",
            "inAppNotifDisabled": "Notificações no aplicativo desativadas.",
            "gpsAutoEnabled": "Acesso automático ao GPS ativado.",
            "gpsAutoDisabled": "Acesso automático ao GPS desativado.",
            "expenseDeleted": "Despesa excluída",
            "supabaseNotConfigured": "Supabase não configurado. Verifique as variáveis de ambiente.",
            "supabaseError": "Não foi possível conectar ao Supabase: {{message}}",
            "shareLinkCreateError": "Erro ao criar link de compartilhamento. Tente novamente mais tarde.",
            "syncSuccess": "Dados compartilhados sincronizados.",
            "syncError": "Erro ao sincronizar dados. Tente novamente mais tarde.",
            "shareLinkDisabled": "Link de compartilhamento desativado.",
            "shareLinkDisableError": "Erro ao desativar link de compartilhamento. Tente novamente mais tarde.",
            "deleteDataSuccess": "Dados excluídos com sucesso. Recarregando a página...",
            "deleteDataError": "Ocorreu um erro ao excluir os dados.",
            "changesApplied": "Alterações aplicadas à viagem.",
            "approveError": "Erro ao aprovar: {{message}}",
            "requestRejected": "Solicitação de edição rejeitada.",
            "rejectError": "Erro ao rejeitar: {{message}}",
            "allAppliedSuccess": "Todas as {{successCount}} alterações aplicadas com sucesso à viagem.",
            "partialApplied": "{{successCount}} alterações aplicadas. {{failCount}} solicitações falharam.",
            "allRejectedSuccess": "Todas as {{successCount}} solicitações de edição rejeitadas com sucesso.",
            "partialRejected": "{{successCount}} solicitações rejeitadas. {{failCount}} solicitações falharam.",
            "activityRequireName": "Por favor, insira o nome da atividade e selecione a data.",
            "updateError": "Erro de atualização: {{message}}",
            "submitRequestError": "Erro ao enviar solicitação: {{message}}",
            "directDelete": "Excluído diretamente!",
            "requestSent": "Solicitação enviada. O proprietário da viagem revisará e responderá.",
            "deleteError": "Erro de exclusão: {{message}}",
            "backupRequireName": "Por favor, insira o nome do plano de backup",
            "statusUpdated": "Status atualizado!",
            "errorMsg": "Erro: {{message}}",
            "tripNotFound": "Erro: Viagem não encontrada",
            "personalPreparationUpdated": "Preparação pessoal atualizada!",
            "personalPreparationAdded": "Preparação pessoal adicionada!",
            "saveError": "Erro ao salvar: {{message}}",
            "personalDocUpdated": "Documento pessoal atualizado",
            "personalDocAdded": "Documento pessoal adicionado",
            "personalDocDeleted": "Documento pessoal excluído!",
            "uploadError": "Erro ao enviar imagem. Tente novamente.",
            "locationError": "Não foi possível obter a localização.",
            "postDeleted": "Postagem excluída.",
            "requireRole": "Por favor, selecione uma nova função.",
            "roleRequestSent": "Solicitação de alteração de função enviada. O líder do grupo aprovará.",
            "memberAddRequestSent": "Solicitação de adição de membro enviada. O líder do grupo aprovará.",
            "memberDeleteRequestSent": "Solicitação de exclusão de membro enviada."
        }
    },
    "id": {
        "toast": {
            "invalidFileFormat": "Format file KAT Journey tidak valid.",
            "cantReadFile": "Tidak dapat membaca file. Pastikan ini adalah file .katjourney.",
            "importSuccess": "Perjalanan berhasil diimpor!",
            "importError": "Tidak dapat mengimpor file: {{message}}",
            "pushNotifEnabled": "Notifikasi push berhasil diaktifkan!",
            "pushNotifDenied": "Izin notifikasi ditolak. Harap aktifkan di pengaturan browser.",
            "inAppNotifEnabled": "Notifikasi dalam aplikasi diaktifkan.",
            "inAppNotifDisabled": "Notifikasi dalam aplikasi dinonaktifkan.",
            "gpsAutoEnabled": "Akses GPS otomatis diaktifkan.",
            "gpsAutoDisabled": "Akses GPS otomatis dinonaktifkan.",
            "expenseDeleted": "Pengeluaran dihapus",
            "supabaseNotConfigured": "Supabase tidak dikonfigurasi. Harap periksa variabel lingkungan.",
            "supabaseError": "Tidak dapat terhubung ke Supabase: {{message}}",
            "shareLinkCreateError": "Kesalahan membuat tautan berbagi. Silakan coba lagi nanti.",
            "syncSuccess": "Data bersama disinkronkan.",
            "syncError": "Kesalahan menyinkronkan data. Silakan coba lagi nanti.",
            "shareLinkDisabled": "Tautan berbagi dinonaktifkan.",
            "shareLinkDisableError": "Kesalahan menonaktifkan tautan berbagi. Silakan coba lagi nanti.",
            "deleteDataSuccess": "Data berhasil dihapus. Memuat ulang halaman...",
            "deleteDataError": "Terjadi kesalahan saat menghapus data.",
            "changesApplied": "Perubahan diterapkan ke perjalanan.",
            "approveError": "Kesalahan saat menyetujui: {{message}}",
            "requestRejected": "Permintaan edit ditolak.",
            "rejectError": "Kesalahan saat menolak: {{message}}",
            "allAppliedSuccess": "Berhasil menerapkan semua {{successCount}} perubahan ke perjalanan.",
            "partialApplied": "Menerapkan {{successCount}} perubahan. Gagal {{failCount}} permintaan.",
            "allRejectedSuccess": "Berhasil menolak semua {{successCount}} permintaan edit.",
            "partialRejected": "Menolak {{successCount}} permintaan. Gagal {{failCount}} permintaan.",
            "activityRequireName": "Harap masukkan nama aktivitas dan pilih tanggal.",
            "updateError": "Kesalahan pembaruan: {{message}}",
            "submitRequestError": "Kesalahan mengirimkan permintaan: {{message}}",
            "directDelete": "Dihapus secara langsung!",
            "requestSent": "Permintaan dikirim. Pemilik perjalanan akan meninjau dan merespons.",
            "deleteError": "Kesalahan penghapusan: {{message}}",
            "backupRequireName": "Harap masukkan nama rencana cadangan",
            "statusUpdated": "Status diperbarui!",
            "errorMsg": "Kesalahan: {{message}}",
            "tripNotFound": "Kesalahan: Perjalanan tidak ditemukan",
            "personalPreparationUpdated": "Persiapan pribadi diperbarui!",
            "personalPreparationAdded": "Persiapan pribadi ditambahkan!",
            "saveError": "Kesalahan menyimpan: {{message}}",
            "personalDocUpdated": "Dokumen pribadi diperbarui",
            "personalDocAdded": "Dokumen pribadi ditambahkan",
            "personalDocDeleted": "Dokumen pribadi dihapus!",
            "uploadError": "Kesalahan mengunggah gambar. Silakan coba lagi.",
            "locationError": "Tidak bisa mendapatkan lokasi.",
            "postDeleted": "Postingan dihapus.",
            "requireRole": "Harap pilih peran baru.",
            "roleRequestSent": "Permintaan perubahan peran terkirim. Ketua grup akan menyetujui.",
            "memberAddRequestSent": "Permintaan penambahan anggota terkirim. Ketua grup akan menyetujui.",
            "memberDeleteRequestSent": "Permintaan penghapusan anggota terkirim."
        }
    },
    "ja": {
        "toast": {
            "invalidFileFormat": "無効なKAT Journeyファイル形式です。",
            "cantReadFile": "ファイルを読み込めません。.katjourneyファイルであることを確認してください。",
            "importSuccess": "旅行が正常にインポートされました！",
            "importError": "ファイルをインポートできません: {{message}}",
            "pushNotifEnabled": "プッシュ通知が正常に有効になりました！",
            "pushNotifDenied": "通知の許可が拒否されました。ブラウザの設定で有効にしてください。",
            "inAppNotifEnabled": "アプリ内通知が有効になりました。",
            "inAppNotifDisabled": "アプリ内通知が無効になりました。",
            "gpsAutoEnabled": "自動GPSアクセスが有効になりました。",
            "gpsAutoDisabled": "自動GPSアクセスが無効になりました。",
            "expenseDeleted": "経費が削除されました",
            "supabaseNotConfigured": "Supabaseが構成されていません。環境変数を確認してください。",
            "supabaseError": "Supabaseに接続できません: {{message}}",
            "shareLinkCreateError": "共有リンクの作成中にエラーが発生しました。後でもう一度お試しください。",
            "syncSuccess": "共有データが同期されました。",
            "syncError": "データの同期中にエラーが発生しました。後でもう一度お試しください。",
            "shareLinkDisabled": "共有リンクが無効になりました。",
            "shareLinkDisableError": "共有リンクの無効化中にエラーが発生しました。後でもう一度お試しください。",
            "deleteDataSuccess": "データが正常に削除されました。ページをリロードしています...",
            "deleteDataError": "データの削除中にエラーが発生しました。",
            "changesApplied": "旅行に変更が適用されました。",
            "approveError": "承認中のエラー: {{message}}",
            "requestRejected": "編集リクエストが拒否されました。",
            "rejectError": "拒否中のエラー: {{message}}",
            "allAppliedSuccess": "{{successCount}}個の変更すべてが正常に旅行に適用されました。",
            "partialApplied": "{{successCount}}個の変更が適用されました。{{failCount}}個のリクエストに失敗しました。",
            "allRejectedSuccess": "{{successCount}}個の編集リクエストすべてが正常に拒否されました。",
            "partialRejected": "{{successCount}}個のリクエストが拒否されました。{{failCount}}個のリクエストに失敗しました。",
            "activityRequireName": "アクティビティ名を入力し、日付を選択してください。",
            "updateError": "更新エラー: {{message}}",
            "submitRequestError": "リクエストの送信中にエラーが発生しました: {{message}}",
            "directDelete": "直接削除されました！",
            "requestSent": "リクエストが送信されました。旅行の所有者が確認して返信します。",
            "deleteError": "削除エラー: {{message}}",
            "backupRequireName": "バックアッププラン名を入力してください",
            "statusUpdated": "ステータスが更新されました！",
            "errorMsg": "エラー: {{message}}",
            "tripNotFound": "エラー: 旅行が見つかりません",
            "personalPreparationUpdated": "個人の準備が更新されました！",
            "personalPreparationAdded": "個人の準備が追加されました！",
            "saveError": "保存中のエラー: {{message}}",
            "personalDocUpdated": "個人のドキュメントが更新されました",
            "personalDocAdded": "個人のドキュメントが追加されました",
            "personalDocDeleted": "個人のドキュメントが削除されました！",
            "uploadError": "画像のアップロード中にエラーが発生しました。もう一度お試しください。",
            "locationError": "現在地を取得できませんでした。",
            "postDeleted": "投稿が削除されました。",
            "requireRole": "新しい役割を選択してください。",
            "roleRequestSent": "役割変更リクエストが送信されました。グループリーダーが承認します。",
            "memberAddRequestSent": "メンバー追加リクエストが送信されました。グループリーダーが承認します。",
            "memberDeleteRequestSent": "メンバー削除リクエストが送信されました。"
        }
    },
    "ko": {
        "toast": {
            "invalidFileFormat": "잘못된 KAT Journey 파일 형식입니다.",
            "cantReadFile": "파일을 읽을 수 없습니다. .katjourney 파일인지 확인하세요.",
            "importSuccess": "여행이 성공적으로 가져와졌습니다!",
            "importError": "파일을 가져올 수 없습니다: {{message}}",
            "pushNotifEnabled": "푸시 알림이 성공적으로 활성화되었습니다!",
            "pushNotifDenied": "알림 권한이 거부되었습니다. 브라우저 설정에서 활성화하세요.",
            "inAppNotifEnabled": "앱 내 알림이 활성화되었습니다.",
            "inAppNotifDisabled": "앱 내 알림이 비활성화되었습니다.",
            "gpsAutoEnabled": "자동 GPS 액세스가 활성화되었습니다.",
            "gpsAutoDisabled": "자동 GPS 액세스가 비활성화되었습니다.",
            "expenseDeleted": "비용이 삭제되었습니다",
            "supabaseNotConfigured": "Supabase가 구성되지 않았습니다. 환경 변수를 확인하세요.",
            "supabaseError": "Supabase에 연결할 수 없습니다: {{message}}",
            "shareLinkCreateError": "공유 링크를 생성하는 중 오류가 발생했습니다. 나중에 다시 시도하세요.",
            "syncSuccess": "공유 데이터가 동기화되었습니다.",
            "syncError": "데이터를 동기화하는 중 오류가 발생했습니다. 나중에 다시 시도하세요.",
            "shareLinkDisabled": "공유 링크가 비활성화되었습니다.",
            "shareLinkDisableError": "공유 링크를 비활성화하는 중 오류가 발생했습니다. 나중에 다시 시도하세요.",
            "deleteDataSuccess": "데이터가 성공적으로 삭제되었습니다. 페이지를 다시 로드하는 중...",
            "deleteDataError": "데이터를 삭제하는 중 오류가 발생했습니다.",
            "changesApplied": "여행에 변경 사항이 적용되었습니다.",
            "approveError": "승인 중 오류 발생: {{message}}",
            "requestRejected": "편집 요청이 거부되었습니다.",
            "rejectError": "거부 중 오류 발생: {{message}}",
            "allAppliedSuccess": "{{successCount}}개의 변경 사항이 모두 여행에 성공적으로 적용되었습니다.",
            "partialApplied": "{{successCount}}개의 변경 사항이 적용되었습니다. {{failCount}}개의 요청이 실패했습니다.",
            "allRejectedSuccess": "{{successCount}}개의 편집 요청이 모두 성공적으로 거부되었습니다.",
            "partialRejected": "{{successCount}}개의 요청이 거부되었습니다. {{failCount}}개의 요청이 실패했습니다.",
            "activityRequireName": "활동 이름을 입력하고 날짜를 선택하세요.",
            "updateError": "업데이트 오류: {{message}}",
            "submitRequestError": "요청 제출 중 오류 발생: {{message}}",
            "directDelete": "직접 삭제되었습니다!",
            "requestSent": "요청이 전송되었습니다. 여행 소유자가 확인하고 답변할 것입니다.",
            "deleteError": "삭제 오류: {{message}}",
            "backupRequireName": "백업 계획 이름을 입력하세요",
            "statusUpdated": "상태가 업데이트되었습니다!",
            "errorMsg": "오류: {{message}}",
            "tripNotFound": "오류: 여행을 찾을 수 없습니다",
            "personalPreparationUpdated": "개인 준비가 업데이트되었습니다!",
            "personalPreparationAdded": "개인 준비가 추가되었습니다!",
            "saveError": "저장 중 오류 발생: {{message}}",
            "personalDocUpdated": "개인 문서가 업데이트되었습니다",
            "personalDocAdded": "개인 문서가 추가되었습니다",
            "personalDocDeleted": "개인 문서가 삭제되었습니다!",
            "uploadError": "이미지를 업로드하는 중 오류가 발생했습니다. 다시 시도하세요.",
            "locationError": "위치를 가져올 수 없습니다.",
            "postDeleted": "게시물이 삭제되었습니다.",
            "requireRole": "새로운 역할을 선택하세요.",
            "roleRequestSent": "역할 변경 요청이 전송되었습니다. 그룹 리더가 승인할 것입니다.",
            "memberAddRequestSent": "멤버 추가 요청이 전송되었습니다. 그룹 리더가 승인할 것입니다.",
            "memberDeleteRequestSent": "멤버 삭제 요청이 전송되었습니다."
        }
    },
    "th": {
        "toast": {
            "invalidFileFormat": "รูปแบบไฟล์ KAT Journey ไม่ถูกต้อง",
            "cantReadFile": "ไม่สามารถอ่านไฟล์ได้ ตรวจสอบให้แน่ใจว่าเป็นไฟล์ .katjourney",
            "importSuccess": "นำเข้าการเดินทางสำเร็จ!",
            "importError": "ไม่สามารถนำเข้าไฟล์: {{message}}",
            "pushNotifEnabled": "เปิดใช้งานการแจ้งเตือนแบบพุชสำเร็จ!",
            "pushNotifDenied": "สิทธิ์การแจ้งเตือนถูกปฏิเสธ โปรดเปิดใช้งานในการตั้งค่าเบราว์เซอร์",
            "inAppNotifEnabled": "เปิดใช้งานการแจ้งเตือนในแอปแล้ว",
            "inAppNotifDisabled": "ปิดใช้งานการแจ้งเตือนในแอปแล้ว",
            "gpsAutoEnabled": "เปิดใช้งานการเข้าถึง GPS อัตโนมัติแล้ว",
            "gpsAutoDisabled": "ปิดใช้งานการเข้าถึง GPS อัตโนมัติแล้ว",
            "expenseDeleted": "ลบค่าใช้จ่ายแล้ว",
            "supabaseNotConfigured": "ไม่ได้กำหนดค่า Supabase โปรดตรวจสอบตัวแปรสภาพแวดล้อม",
            "supabaseError": "ไม่สามารถเชื่อมต่อกับ Supabase: {{message}}",
            "shareLinkCreateError": "เกิดข้อผิดพลาดในการสร้างลิงก์ที่ใช้ร่วมกัน โปรดลองอีกครั้งในภายหลัง",
            "syncSuccess": "ซิงโครไนซ์ข้อมูลที่ใช้ร่วมกันแล้ว",
            "syncError": "เกิดข้อผิดพลาดในการซิงโครไนซ์ข้อมูล โปรดลองอีกครั้งในภายหลัง",
            "shareLinkDisabled": "ปิดใช้งานลิงก์ที่ใช้ร่วมกันแล้ว",
            "shareLinkDisableError": "เกิดข้อผิดพลาดในการปิดใช้งานลิงก์ที่ใช้ร่วมกัน โปรดลองอีกครั้งในภายหลัง",
            "deleteDataSuccess": "ลบข้อมูลสำเร็จ กำลังโหลดหน้าซ้ำ...",
            "deleteDataError": "เกิดข้อผิดพลาดขณะลบข้อมูล",
            "changesApplied": "นำการเปลี่ยนแปลงไปใช้กับการเดินทางแล้ว",
            "approveError": "ข้อผิดพลาดในการอนุมัติ: {{message}}",
            "requestRejected": "คำขอแก้ไขถูกปฏิเสธ",
            "rejectError": "ข้อผิดพลาดในการปฏิเสธ: {{message}}",
            "allAppliedSuccess": "นำการเปลี่ยนแปลงทั้ง {{successCount}} รายการไปใช้กับการเดินทางสำเร็จแล้ว",
            "partialApplied": "นำการเปลี่ยนแปลง {{successCount}} รายการไปใช้ ล้มเหลว {{failCount}} คำขอ",
            "allRejectedSuccess": "ปฏิเสธคำขอแก้ไขทั้ง {{successCount}} รายการสำเร็จแล้ว",
            "partialRejected": "ปฏิเสธคำขอ {{successCount}} รายการ ล้มเหลว {{failCount}} คำขอ",
            "activityRequireName": "โปรดป้อนชื่อกิจกรรมและเลือกวันที่",
            "updateError": "ข้อผิดพลาดในการอัปเดต: {{message}}",
            "submitRequestError": "ข้อผิดพลาดในการส่งคำขอ: {{message}}",
            "directDelete": "ลบโดยตรงแล้ว!",
            "requestSent": "ส่งคำขอแล้ว เจ้าของการเดินทางจะตรวจสอบและตอบกลับ",
            "deleteError": "ข้อผิดพลาดในการลบ: {{message}}",
            "backupRequireName": "โปรดป้อนชื่อแผนสำรอง",
            "statusUpdated": "อัปเดตสถานะแล้ว!",
            "errorMsg": "ข้อผิดพลาด: {{message}}",
            "tripNotFound": "ข้อผิดพลาด: ไม่พบการเดินทาง",
            "personalPreparationUpdated": "อัปเดตการเตรียมส่วนตัวแล้ว!",
            "personalPreparationAdded": "เพิ่มการเตรียมส่วนตัวแล้ว!",
            "saveError": "ข้อผิดพลาดในการบันทึก: {{message}}",
            "personalDocUpdated": "อัปเดตเอกสารส่วนตัวแล้ว",
            "personalDocAdded": "เพิ่มเอกสารส่วนตัวแล้ว",
            "personalDocDeleted": "ลบเอกสารส่วนตัวแล้ว!",
            "uploadError": "ข้อผิดพลาดในการอัปโหลดรูปภาพ โปรดลองอีกครั้ง",
            "locationError": "ไม่สามารถรับตำแหน่งได้",
            "postDeleted": "ลบโพสต์แล้ว",
            "requireRole": "โปรดเลือกบทบาทใหม่",
            "roleRequestSent": "ส่งคำขอเปลี่ยนบทบาทแล้ว หัวหน้ากลุ่มจะอนุมัติ",
            "memberAddRequestSent": "ส่งคำขอเพิ่มสมาชิกแล้ว หัวหน้ากลุ่มจะอนุมัติ",
            "memberDeleteRequestSent": "ส่งคำขอลบสมาชิกแล้ว"
        }
    },
    "zh": {
        "toast": {
            "invalidFileFormat": "KAT Journey 文件格式无效。",
            "cantReadFile": "无法读取文件。请确保它是 .katjourney 文件。",
            "importSuccess": "成功导入行程！",
            "importError": "无法导入文件：{{message}}",
            "pushNotifEnabled": "成功启用推送通知！",
            "pushNotifDenied": "通知权限被拒绝。请在浏览器设置中启用它。",
            "inAppNotifEnabled": "应用内通知已启用。",
            "inAppNotifDisabled": "应用内通知已禁用。",
            "gpsAutoEnabled": "自动 GPS 访问已启用。",
            "gpsAutoDisabled": "自动 GPS 访问已禁用。",
            "expenseDeleted": "费用已删除",
            "supabaseNotConfigured": "未配置 Supabase。请检查环境变量。",
            "supabaseError": "无法连接到 Supabase：{{message}}",
            "shareLinkCreateError": "创建共享链接时出错。请稍后再试。",
            "syncSuccess": "共享数据已同步。",
            "syncError": "同步数据时出错。请稍后再试。",
            "shareLinkDisabled": "共享链接已禁用。",
            "shareLinkDisableError": "禁用共享链接时出错。请稍后再试。",
            "deleteDataSuccess": "成功删除数据。正在重新加载页面...",
            "deleteDataError": "删除数据时出错。",
            "changesApplied": "更改已应用到行程。",
            "approveError": "批准时出错：{{message}}",
            "requestRejected": "编辑请求被拒绝。",
            "rejectError": "拒绝时出错：{{message}}",
            "allAppliedSuccess": "成功将所有 {{successCount}} 个更改应用到行程。",
            "partialApplied": "已应用 {{successCount}} 个更改。{{failCount}} 个请求失败。",
            "allRejectedSuccess": "成功拒绝所有 {{successCount}} 个编辑请求。",
            "partialRejected": "已拒绝 {{successCount}} 个请求。{{failCount}} 个请求失败。",
            "activityRequireName": "请输入活动名称并选择日期。",
            "updateError": "更新错误：{{message}}",
            "submitRequestError": "提交请求时出错：{{message}}",
            "directDelete": "已直接删除！",
            "requestSent": "请求已发送。行程所有者将审核并回复。",
            "deleteError": "删除错误：{{message}}",
            "backupRequireName": "请输入备用计划名称",
            "statusUpdated": "状态已更新！",
            "errorMsg": "错误：{{message}}",
            "tripNotFound": "错误：未找到行程",
            "personalPreparationUpdated": "个人准备已更新！",
            "personalPreparationAdded": "已添加个人准备！",
            "saveError": "保存时出错：{{message}}",
            "personalDocUpdated": "个人文档已更新",
            "personalDocAdded": "个人文档已添加",
            "personalDocDeleted": "个人文档已删除！",
            "uploadError": "上传图片时出错。请重试。",
            "locationError": "无法获取位置。",
            "postDeleted": "帖子已删除。",
            "requireRole": "请选择一个新角色。",
            "roleRequestSent": "角色更改请求已发送。组长将批准。",
            "memberAddRequestSent": "成员添加请求已发送。组长将批准。",
            "memberDeleteRequestSent": "成员删除请求已发送。"
        }
    }
}

for lang, trans in translations.items():
    filepath = os.path.join(locales_dir, f"{lang}.json")
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Enforce all keys
        if "toast" not in data:
            data["toast"] = {}
        data["toast"].update(trans["toast"])
            
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print("Injected translated toast notifications for all 12 languages")
