import json
import os

translations = {
    "vi": {
        "typeTicket": "Vé di chuyển",
        "typeHotel": "Đặt phòng",
        "typeBooking": "Mã đặt chỗ",
        "typeContact": "Liên hệ",
        "typeMap": "Bản đồ",
        "typeOther": "Khác",
        "editDocumentTitle": "Sửa giấy tờ & đặt chỗ",
        "addDocumentTitle": "Thêm giấy tờ & đặt chỗ",
        "titleRequired": "Vui lòng nhập tiêu đề.",
        "toastUpdated": "Đã cập nhật giấy tờ",
        "toastSaved": "Đã lưu giấy tờ mới",
        "toastError": "Có lỗi xảy ra khi lưu tài liệu",
        "saveBtn": "Lưu",
        "inputTitleLabel": "Tên mục *",
        "inputTitlePlaceholder": "VD: Vé máy bay khứ hồi, mã đặt phòng khách sạn...",
        "inputTypeLabel": "Phân loại",
        "inputPrivacyLabel": "Quyền chia sẻ",
        "privacyPrivate": "Riêng tư (Chỉ mình tôi)",
        "privacyGroup": "Chia sẻ với nhóm",
        "inputCodeLabel": "Mã / thông tin đặt chỗ",
        "inputCodePlaceholder": "VD: PNR ABC123, mã phòng, số vé...",
        "advancedInfoLabel": "Thông tin bổ sung",
        "inputDateLabel": "Ngày liên quan",
        "inputLinkLabel": "Đường dẫn liên quan",
        "inputLinkPlaceholder": "VD: Link vé điện tử, bản đồ, tệp đặt phòng...",
        "inputNoteLabel": "Ghi chú",
        "inputNotePlaceholder": "VD: Giờ nhận phòng, hành lý, số điện thoại liên hệ...",
        "inputAttachmentLabel": "Ảnh đính kèm (Vé/CCCD/...)",
        "uploadBtn": "Nhấn để tải ảnh lên",
        "uploadAcceptedFormats": "Chấp nhận PNG, JPG, WEBP",
        "editBtn": "Sửa",
        "deleteBtn": "Xóa",
        "optionsBtn": "Tùy chọn",
        "codeLabel": "Mã xác nhận / Code",
        "copyCodeBtn": "Sao chép mã",
        "relatedDateLabel": "Ngày liên quan:",
        "attachmentLabel": "Ảnh đính kèm",
        "openLinkBtn": "Mở liên kết trực tuyến",
        "featureTitle": "Giấy tờ & đặt chỗ",
        "featureDesc": "Lưu vé, mã đặt chỗ và thông tin quan trọng để tra cứu nhanh khi cần.",
        "addBtn": "Thêm giấy tờ",
        "filterAll": "Tất cả",
        "emptyAllTitle": "Chưa có giấy tờ nào",
        "emptyAllDesc": "Lưu vé, mã đặt chỗ, liên hệ quan trọng hoặc link bản đồ để tra cứu nhanh khi cần.",
        "emptyFilterTitle": "Không tìm thấy mục lưu trữ",
        "emptyFilterDesc": "Chọn bộ lọc khác hoặc thêm mới giấy tờ & đặt chỗ thuộc nhóm này.",
        "deleteModalTitle": "Xóa giấy tờ này?",
        "deleteModalDesc": "Mục giấy tờ hoặc đặt chỗ này sẽ bị xóa khỏi chuyến đi. Sau khi xóa, không thể hoàn tác.",
        "deleteModalConfirm": "Xóa giấy tờ",
        "toastDeleted": "Đã xóa thành công"
    },
    "en": {
        "typeTicket": "Transport Ticket",
        "typeHotel": "Hotel Booking",
        "typeBooking": "Booking Code",
        "typeContact": "Contact",
        "typeMap": "Map",
        "typeOther": "Other",
        "editDocumentTitle": "Edit Document & Booking",
        "addDocumentTitle": "Add Document & Booking",
        "titleRequired": "Please enter a title.",
        "toastUpdated": "Document updated",
        "toastSaved": "New document saved",
        "toastError": "Error saving document",
        "saveBtn": "Save",
        "inputTitleLabel": "Title *",
        "inputTitlePlaceholder": "e.g., Round-trip flight, hotel booking code...",
        "inputTypeLabel": "Category",
        "inputPrivacyLabel": "Privacy",
        "privacyPrivate": "Private (Only me)",
        "privacyGroup": "Share with group",
        "inputCodeLabel": "Booking code / info",
        "inputCodePlaceholder": "e.g., PNR ABC123, room code, ticket number...",
        "advancedInfoLabel": "Additional Information",
        "inputDateLabel": "Related Date",
        "inputLinkLabel": "Related Link",
        "inputLinkPlaceholder": "e.g., E-ticket link, map, booking file...",
        "inputNoteLabel": "Note",
        "inputNotePlaceholder": "e.g., Check-in time, baggage, contact number...",
        "inputAttachmentLabel": "Attachment (Ticket/ID/...)",
        "uploadBtn": "Click to upload image",
        "uploadAcceptedFormats": "Accepts PNG, JPG, WEBP",
        "editBtn": "Edit",
        "deleteBtn": "Delete",
        "optionsBtn": "Options",
        "codeLabel": "Booking Code",
        "copyCodeBtn": "Copy Code",
        "relatedDateLabel": "Related Date:",
        "attachmentLabel": "Attachment",
        "openLinkBtn": "Open online link",
        "featureTitle": "Documents & Bookings",
        "featureDesc": "Save tickets, booking codes, and important info for quick access.",
        "addBtn": "Add Document",
        "filterAll": "All",
        "emptyAllTitle": "No documents yet",
        "emptyAllDesc": "Save tickets, booking codes, important contacts or map links for quick access.",
        "emptyFilterTitle": "No items found",
        "emptyFilterDesc": "Select another filter or add a new document to this category.",
        "deleteModalTitle": "Delete this document?",
        "deleteModalDesc": "This document or booking will be removed from the trip. This action cannot be undone.",
        "deleteModalConfirm": "Delete document",
        "toastDeleted": "Deleted successfully"
    },
    "ja": {
        "typeTicket": "交通チケット",
        "typeHotel": "ホテル予約",
        "typeBooking": "予約コード",
        "typeContact": "連絡先",
        "typeMap": "地図",
        "typeOther": "その他",
        "editDocumentTitle": "ドキュメント＆予約を編集",
        "addDocumentTitle": "ドキュメント＆予約を追加",
        "titleRequired": "タイトルを入力してください。",
        "toastUpdated": "ドキュメントを更新しました",
        "toastSaved": "新しいドキュメントを保存しました",
        "toastError": "ドキュメントの保存中にエラーが発生しました",
        "saveBtn": "保存",
        "inputTitleLabel": "タイトル *",
        "inputTitlePlaceholder": "例：往復航空券、ホテル予約コード...",
        "inputTypeLabel": "カテゴリー",
        "inputPrivacyLabel": "共有範囲",
        "privacyPrivate": "非公開（自分のみ）",
        "privacyGroup": "グループと共有",
        "inputCodeLabel": "予約コード / 情報",
        "inputCodePlaceholder": "例：PNR ABC123、部屋コード、チケット番号...",
        "advancedInfoLabel": "追加情報",
        "inputDateLabel": "関連日",
        "inputLinkLabel": "関連リンク",
        "inputLinkPlaceholder": "例：電子チケットのリンク、地図、予約ファイル...",
        "inputNoteLabel": "メモ",
        "inputNotePlaceholder": "例：チェックイン時間、手荷物、連絡先番号...",
        "inputAttachmentLabel": "添付ファイル（チケット/身分証/...）",
        "uploadBtn": "タップして画像をアップロード",
        "uploadAcceptedFormats": "PNG、JPG、WEBPを受け付けます",
        "editBtn": "編集",
        "deleteBtn": "削除",
        "optionsBtn": "オプション",
        "codeLabel": "予約コード",
        "copyCodeBtn": "コードをコピー",
        "relatedDateLabel": "関連日:",
        "attachmentLabel": "添付ファイル",
        "openLinkBtn": "オンラインリンクを開く",
        "featureTitle": "ドキュメント＆予約",
        "featureDesc": "チケット、予約コード、重要な情報を保存してすばやくアクセスします。",
        "addBtn": "ドキュメントを追加",
        "filterAll": "すべて",
        "emptyAllTitle": "ドキュメントはまだありません",
        "emptyAllDesc": "チケット、予約コード、重要な連絡先、地図のリンクなどを保存してすばやくアクセスします。",
        "emptyFilterTitle": "アイテムが見つかりません",
        "emptyFilterDesc": "別のフィルターを選択するか、このカテゴリーに新しいドキュメントを追加してください。",
        "deleteModalTitle": "このドキュメントを削除しますか？",
        "deleteModalDesc": "このドキュメントまたは予約は旅行から削除されます。この操作は元に戻せません。",
        "deleteModalConfirm": "ドキュメントを削除",
        "toastDeleted": "正常に削除されました"
    },
    "th": {
        "typeTicket": "ตั๋วเดินทาง",
        "typeHotel": "จองโรงแรม",
        "typeBooking": "รหัสการจอง",
        "typeContact": "ติดต่อ",
        "typeMap": "แผนที่",
        "typeOther": "อื่นๆ",
        "editDocumentTitle": "แก้ไขเอกสารและการจอง",
        "addDocumentTitle": "เพิ่มเอกสารและการจอง",
        "titleRequired": "กรุณาใส่ชื่อ",
        "toastUpdated": "อัปเดตเอกสารแล้ว",
        "toastSaved": "บันทึกเอกสารใหม่แล้ว",
        "toastError": "เกิดข้อผิดพลาดในการบันทึกเอกสาร",
        "saveBtn": "บันทึก",
        "inputTitleLabel": "ชื่อ *",
        "inputTitlePlaceholder": "เช่น ตั๋วเครื่องบินไปกลับ, รหัสจองโรงแรม...",
        "inputTypeLabel": "หมวดหมู่",
        "inputPrivacyLabel": "ความเป็นส่วนตัว",
        "privacyPrivate": "ส่วนตัว (เฉพาะฉัน)",
        "privacyGroup": "แชร์กับกลุ่ม",
        "inputCodeLabel": "รหัสการจอง / ข้อมูล",
        "inputCodePlaceholder": "เช่น PNR ABC123, รหัสห้อง, หมายเลขตั๋ว...",
        "advancedInfoLabel": "ข้อมูลเพิ่มเติม",
        "inputDateLabel": "วันที่เกี่ยวข้อง",
        "inputLinkLabel": "ลิงก์ที่เกี่ยวข้อง",
        "inputLinkPlaceholder": "เช่น ลิงก์ E-ticket, แผนที่, ไฟล์การจอง...",
        "inputNoteLabel": "หมายเหตุ",
        "inputNotePlaceholder": "เช่น เวลาเช็คอิน, สัมภาระ, เบอร์ติดต่อ...",
        "inputAttachmentLabel": "ไฟล์แนบ (ตั๋ว/บัตรประจำตัว/...)",
        "uploadBtn": "แตะเพื่ออัปโหลดรูปภาพ",
        "uploadAcceptedFormats": "รับรอง PNG, JPG, WEBP",
        "editBtn": "แก้ไข",
        "deleteBtn": "ลบ",
        "optionsBtn": "ตัวเลือก",
        "codeLabel": "รหัสการจอง",
        "copyCodeBtn": "คัดลอกรหัส",
        "relatedDateLabel": "วันที่เกี่ยวข้อง:",
        "attachmentLabel": "ไฟล์แนบ",
        "openLinkBtn": "เปิดลิงก์ออนไลน์",
        "featureTitle": "เอกสารและการจอง",
        "featureDesc": "บันทึกตั๋ว รหัสการจอง และข้อมูลสำคัญเพื่อให้เข้าถึงได้ง่าย",
        "addBtn": "เพิ่มเอกสาร",
        "filterAll": "ทั้งหมด",
        "emptyAllTitle": "ยังไม่มีเอกสาร",
        "emptyAllDesc": "บันทึกตั๋ว รหัสการจอง ข้อมูลติดต่อสำคัญ หรือลิงก์แผนที่เพื่อให้เข้าถึงได้ง่าย",
        "emptyFilterTitle": "ไม่พบรายการ",
        "emptyFilterDesc": "เลือกตัวกรองอื่นหรือเพิ่มเอกสารใหม่ในหมวดหมู่นี้",
        "deleteModalTitle": "ลบเอกสารนี้หรือไม่?",
        "deleteModalDesc": "เอกสารหรือการจองนี้จะถูกลบออกจากการเดินทาง การกระทำนี้ไม่สามารถยกเลิกได้",
        "deleteModalConfirm": "ลบเอกสาร",
        "toastDeleted": "ลบสำเร็จแล้ว"
    }
}

# Fallback for missing languages
translations["ko"] = translations["en"]
translations["zh"] = translations["en"]
translations["pt"] = translations["en"]
translations["fr"] = translations["en"]
translations["es"] = translations["en"]
translations["de"] = translations["en"]
translations["it"] = translations["en"]
translations["id"] = translations["en"]

for lang, data in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        file_data = json.load(f)
        
    if "documents" not in file_data:
        file_data["documents"] = {}
        
    for k, v in data.items():
        file_data["documents"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(file_data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
