import json
import os

share_translations = {
    "vi": {
        "shareSubtitle": "Tạo link để người khác xem lịch trình và thông tin chuyến đi.",
        "includeExpenses": "Bao gồm chi phí",
        "includeJournals": "Bao gồm bản tin",
        "includeChecklist": "Bao gồm danh sách chuẩn bị",
        "includeBackup": "Bao gồm phương án dự phòng",
        "includeDocs": "Bao gồm giấy tờ & đặt chỗ",
        "docWarning": "Giấy tờ có thể chứa mã đặt chỗ, vé, số điện thoại hoặc liên kết riêng tư. Chỉ bật nếu bạn thực sự tin tưởng người nhận link.",
        "pinProtect": "Bảo vệ bằng mã PIN",
        "pinDesc": "Người xem cần nhập đúng PIN để mở",
        "enterPin": "Nhập mã PIN 4 chữ số:",
        "pinReady": "Mã PIN đã sẵn sàng",
        "pinError": "Vui lòng nhập đủ 4 chữ số",
        "close": "Đóng",
        "creatingLink": "Đang tạo link...",
        "createLink": "Tạo link chia sẻ",
        "linkCreated": "Đã tạo link chia sẻ",
        "joinTrip": "Tham gia chuyến đi \"{{trip}}\" cùng tôi trên KAT Journey!",
        "syncingChanges": "Đang tự động đồng bộ các thay đổi mới nhất...",
        "autoSyncLast": "Tự động đồng bộ khi có thay đổi. Lần cuối:",
        "justNow": "Vừa xong",
        "syncing": "Đang đồng bộ...",
        "syncData": "Đồng bộ dữ liệu",
        "turningOff": "Đang tắt...",
        "turnOff": "Tắt chia sẻ"
    },
    "en": {
        "shareSubtitle": "Create a link for others to view the itinerary and trip information.",
        "includeExpenses": "Include expenses",
        "includeJournals": "Include journals",
        "includeChecklist": "Include checklist",
        "includeBackup": "Include backup plans",
        "includeDocs": "Include documents & bookings",
        "docWarning": "Documents may contain booking codes, tickets, phone numbers, or private links. Only enable if you truly trust the recipient.",
        "pinProtect": "Protect with PIN",
        "pinDesc": "Viewers must enter the correct PIN to open",
        "enterPin": "Enter 4-digit PIN:",
        "pinReady": "PIN is ready",
        "pinError": "Please enter exactly 4 digits",
        "close": "Close",
        "creatingLink": "Creating link...",
        "createLink": "Create share link",
        "linkCreated": "Share link created",
        "joinTrip": "Join the trip \"{{trip}}\" with me on KAT Journey!",
        "syncingChanges": "Auto-syncing latest changes...",
        "autoSyncLast": "Auto-syncs when changed. Last:",
        "justNow": "Just now",
        "syncing": "Syncing...",
        "syncData": "Sync data",
        "turningOff": "Turning off...",
        "turnOff": "Turn off sharing"
    },
    "zh": {
        "shareSubtitle": "创建链接以便他人查看行程和旅行信息。",
        "includeExpenses": "包括费用",
        "includeJournals": "包括日志",
        "includeChecklist": "包括检查清单",
        "includeBackup": "包括备用计划",
        "includeDocs": "包括文件和预订",
        "docWarning": "文件可能包含预订代码、机票、电话号码或私人链接。如果您不信任接收者，请勿启用。",
        "pinProtect": "使用 PIN 码保护",
        "pinDesc": "查看者必须输入正确的 PIN 码才能打开",
        "enterPin": "输入 4 位 PIN 码:",
        "pinReady": "PIN 码已准备就绪",
        "pinError": "请输入正好 4 位数字",
        "close": "关闭",
        "creatingLink": "正在创建链接...",
        "createLink": "创建分享链接",
        "linkCreated": "已创建分享链接",
        "joinTrip": "在 KAT Journey 上与我一起参加“{{trip}}”旅行！",
        "syncingChanges": "正在自动同步最新更改...",
        "autoSyncLast": "更改时自动同步。上次:",
        "justNow": "刚刚",
        "syncing": "正在同步...",
        "syncData": "同步数据",
        "turningOff": "正在关闭...",
        "turnOff": "关闭分享"
    },
    "es": {
        "shareSubtitle": "Crea un enlace para que otros vean el itinerario y la información del viaje.",
        "includeExpenses": "Incluir gastos",
        "includeJournals": "Incluir diarios",
        "includeChecklist": "Incluir lista de verificación",
        "includeBackup": "Incluir planes de respaldo",
        "includeDocs": "Incluir documentos y reservas",
        "docWarning": "Los documentos pueden contener códigos de reserva, boletos, números de teléfono o enlaces privados. Solo habilita si realmente confías en el destinatario.",
        "pinProtect": "Proteger con PIN",
        "pinDesc": "Los espectadores deben ingresar el PIN correcto para abrir",
        "enterPin": "Ingresa PIN de 4 dígitos:",
        "pinReady": "El PIN está listo",
        "pinError": "Ingresa exactamente 4 dígitos",
        "close": "Cerrar",
        "creatingLink": "Creando enlace...",
        "createLink": "Crear enlace para compartir",
        "linkCreated": "Enlace de compartir creado",
        "joinTrip": "¡Únete al viaje \"{{trip}}\" conmigo en KAT Journey!",
        "syncingChanges": "Sincronizando los últimos cambios...",
        "autoSyncLast": "Se sincroniza al cambiar. Último:",
        "justNow": "Justo ahora",
        "syncing": "Sincronizando...",
        "syncData": "Sincronizar datos",
        "turningOff": "Apagando...",
        "turnOff": "Desactivar compartir"
    },
    "ja": {
        "shareSubtitle": "他の人が旅程や旅行情報を閲覧するためのリンクを作成します。",
        "includeExpenses": "費用を含める",
        "includeJournals": "日記を含める",
        "includeChecklist": "持ち物リストを含める",
        "includeBackup": "バックアッププランを含める",
        "includeDocs": "書類と予約を含める",
        "docWarning": "書類には予約コード、チケット、電話番号、非公開リンクが含まれる場合があります。受信者を本当に信頼している場合のみ有効にしてください。",
        "pinProtect": "PINで保護",
        "pinDesc": "閲覧者は開くために正しいPINを入力する必要があります",
        "enterPin": "4桁のPINを入力:",
        "pinReady": "PINの準備完了",
        "pinError": "4桁の数字を入力してください",
        "close": "閉じる",
        "creatingLink": "リンクを作成中...",
        "createLink": "共有リンクを作成",
        "linkCreated": "共有リンクが作成されました",
        "joinTrip": "KAT Journeyで私と一緒に「{{trip}}」の旅行に参加しましょう！",
        "syncingChanges": "最新の変更を自動同期中...",
        "autoSyncLast": "変更時に自動同期。最終:",
        "justNow": "たった今",
        "syncing": "同期中...",
        "syncData": "データを同期",
        "turningOff": "オフにしています...",
        "turnOff": "共有をオフにする"
    },
    "pt": {
        "shareSubtitle": "Crie um link para que outros vejam o itinerário e informações da viagem.",
        "includeExpenses": "Incluir despesas",
        "includeJournals": "Incluir diários",
        "includeChecklist": "Incluir lista de verificação",
        "includeBackup": "Incluir planos de backup",
        "includeDocs": "Incluir documentos e reservas",
        "docWarning": "Os documentos podem conter códigos de reserva, bilhetes, números de telefone ou links privados. Só ative se realmente confiar no destinatário.",
        "pinProtect": "Proteger com PIN",
        "pinDesc": "Os espectadores devem inserir o PIN correto para abrir",
        "enterPin": "Insira o PIN de 4 dígitos:",
        "pinReady": "O PIN está pronto",
        "pinError": "Por favor, insira exatamente 4 dígitos",
        "close": "Fechar",
        "creatingLink": "Criando link...",
        "createLink": "Criar link de compartilhamento",
        "linkCreated": "Link de compartilhamento criado",
        "joinTrip": "Junte-se à viagem \"{{trip}}\" comigo no KAT Journey!",
        "syncingChanges": "Sincronizando últimas alterações...",
        "autoSyncLast": "Sincroniza quando alterado. Último:",
        "justNow": "Agora mesmo",
        "syncing": "Sincronizando...",
        "syncData": "Sincronizar dados",
        "turningOff": "Desativando...",
        "turnOff": "Desativar compartilhamento"
    },
    "ko": {
        "shareSubtitle": "다른 사람이 일정 및 여행 정보를 볼 수 있도록 링크를 생성합니다.",
        "includeExpenses": "비용 포함",
        "includeJournals": "일지 포함",
        "includeChecklist": "준비물 목록 포함",
        "includeBackup": "대비책 포함",
        "includeDocs": "문서 및 예약 포함",
        "docWarning": "문서에 예약 코드, 티켓, 전화번호 또는 비공개 링크가 포함될 수 있습니다. 링크 수신자를 정말로 신뢰하는 경우에만 활성화하세요.",
        "pinProtect": "PIN으로 보호",
        "pinDesc": "열려면 정확한 PIN을 입력해야 합니다",
        "enterPin": "4자리 PIN 입력:",
        "pinReady": "PIN 준비 완료",
        "pinError": "정확히 4자리를 입력하세요",
        "close": "닫기",
        "creatingLink": "링크 생성 중...",
        "createLink": "공유 링크 생성",
        "linkCreated": "공유 링크 생성됨",
        "joinTrip": "KAT Journey에서 저와 함께 \"{{trip}}\" 여행에 참여하세요!",
        "syncingChanges": "최신 변경 사항 자동 동기화 중...",
        "autoSyncLast": "변경 시 자동 동기화. 최근:",
        "justNow": "방금 전",
        "syncing": "동기화 중...",
        "syncData": "데이터 동기화",
        "turningOff": "끄는 중...",
        "turnOff": "공유 끄기"
    },
    "th": {
        "shareSubtitle": "สร้างลิงก์ให้ผู้อื่นดูแผนการเดินทางและข้อมูลการเดินทาง",
        "includeExpenses": "รวมค่าใช้จ่าย",
        "includeJournals": "รวมบันทึกประจำวัน",
        "includeChecklist": "รวมรายการที่ต้องเตรียม",
        "includeBackup": "รวมแผนสำรอง",
        "includeDocs": "รวมเอกสารและการจอง",
        "docWarning": "เอกสารอาจมีรหัสการจอง ตั๋ว หมายเลขโทรศัพท์ หรือลิงก์ส่วนตัว โปรดเปิดใช้งานเฉพาะเมื่อคุณเชื่อใจผู้รับลิงก์เท่านั้น",
        "pinProtect": "ป้องกันด้วย PIN",
        "pinDesc": "ผู้ดูต้องป้อน PIN ที่ถูกต้องเพื่อเปิด",
        "enterPin": "ป้อน PIN 4 หลัก:",
        "pinReady": "PIN พร้อมแล้ว",
        "pinError": "โปรดป้อนตัวเลข 4 หลักให้ครบถ้วน",
        "close": "ปิด",
        "creatingLink": "กำลังสร้างลิงก์...",
        "createLink": "สร้างลิงก์แชร์",
        "linkCreated": "สร้างลิงก์แชร์แล้ว",
        "joinTrip": "เข้าร่วมทริป \"{{trip}}\" กับฉันบน KAT Journey!",
        "syncingChanges": "กำลังซิงค์การเปลี่ยนแปลงล่าสุด...",
        "autoSyncLast": "ซิงค์อัตโนมัติเมื่อมีการเปลี่ยนแปลง ล่าสุด:",
        "justNow": "เมื่อสักครู่นี้",
        "syncing": "กำลังซิงค์...",
        "syncData": "ซิงค์ข้อมูล",
        "turningOff": "กำลังปิด...",
        "turnOff": "ปิดการแชร์"
    },
    "de": {
        "shareSubtitle": "Erstellen Sie einen Link, damit andere die Reiseroute und Reiseinformationen sehen können.",
        "includeExpenses": "Ausgaben einschließen",
        "includeJournals": "Tagebücher einschließen",
        "includeChecklist": "Packliste einschließen",
        "includeBackup": "Ersatzpläne einschließen",
        "includeDocs": "Dokumente & Buchungen einschließen",
        "docWarning": "Dokumente können Buchungscodes, Tickets, Telefonnummern oder private Links enthalten. Nur aktivieren, wenn Sie dem Empfänger des Links vertrauen.",
        "pinProtect": "Mit PIN schützen",
        "pinDesc": "Betrachter müssen die richtige PIN eingeben, um sie zu öffnen",
        "enterPin": "4-stellige PIN eingeben:",
        "pinReady": "PIN ist bereit",
        "pinError": "Bitte genau 4 Ziffern eingeben",
        "close": "Schließen",
        "creatingLink": "Link wird erstellt...",
        "createLink": "Freigabelink erstellen",
        "linkCreated": "Freigabelink erstellt",
        "joinTrip": "Nimm mit mir auf KAT Journey an der Reise \"{{trip}}\" teil!",
        "syncingChanges": "Letzte Änderungen werden automatisch synchronisiert...",
        "autoSyncLast": "Automatische Synchronisierung bei Änderungen. Zuletzt:",
        "justNow": "Gerade eben",
        "syncing": "Synchronisieren...",
        "syncData": "Daten synchronisieren",
        "turningOff": "Wird deaktiviert...",
        "turnOff": "Freigabe deaktivieren"
    },
    "fr": {
        "shareSubtitle": "Créez un lien pour que d'autres puissent voir l'itinéraire et les informations de voyage.",
        "includeExpenses": "Inclure les dépenses",
        "includeJournals": "Inclure les journaux",
        "includeChecklist": "Inclure la liste de colisage",
        "includeBackup": "Inclure les plans de secours",
        "includeDocs": "Inclure les documents et réservations",
        "docWarning": "Les documents peuvent contenir des codes de réservation, des billets, des numéros de téléphone ou des liens privés. N'activez cette option que si vous faites confiance au destinataire du lien.",
        "pinProtect": "Protéger avec un code PIN",
        "pinDesc": "Les spectateurs doivent entrer le bon code PIN pour ouvrir",
        "enterPin": "Entrez un code PIN à 4 chiffres :",
        "pinReady": "Le code PIN est prêt",
        "pinError": "Veuillez entrer exactement 4 chiffres",
        "close": "Fermer",
        "creatingLink": "Création du lien...",
        "createLink": "Créer le lien de partage",
        "linkCreated": "Lien de partage créé",
        "joinTrip": "Rejoins le voyage \"{{trip}}\" avec moi sur KAT Journey !",
        "syncingChanges": "Synchronisation automatique des dernières modifications...",
        "autoSyncLast": "Synchronisation automatique. Dernière :",
        "justNow": "À l'instant",
        "syncing": "Synchronisation...",
        "syncData": "Synchroniser les données",
        "turningOff": "Désactivation...",
        "turnOff": "Désactiver le partage"
    },
    "ru": {
        "shareSubtitle": "Создайте ссылку, чтобы другие могли просматривать маршрут и информацию о поездке.",
        "includeExpenses": "Включить расходы",
        "includeJournals": "Включить дневники",
        "includeChecklist": "Включить список вещей",
        "includeBackup": "Включить запасные планы",
        "includeDocs": "Включить документы и бронирования",
        "docWarning": "Документы могут содержать коды бронирования, билеты, номера телефонов или частные ссылки. Включайте, только если доверяете получателю ссылки.",
        "pinProtect": "Защитить с помощью PIN-кода",
        "pinDesc": "Для открытия зрители должны ввести правильный PIN-код",
        "enterPin": "Введите 4-значный PIN-код:",
        "pinReady": "PIN-код готов",
        "pinError": "Пожалуйста, введите ровно 4 цифры",
        "close": "Закрыть",
        "creatingLink": "Создание ссылки...",
        "createLink": "Создать ссылку",
        "linkCreated": "Ссылка для поделиться создана",
        "joinTrip": "Присоединяйся к поездке \"{{trip}}\" со мной на KAT Journey!",
        "syncingChanges": "Авто-синхронизация последних изменений...",
        "autoSyncLast": "Авто-синхронизация при изменениях. Последняя:",
        "justNow": "Только что",
        "syncing": "Синхронизация...",
        "syncData": "Синхронизировать данные",
        "turningOff": "Отключение...",
        "turnOff": "Отключить общий доступ"
    },
    "ar": {
        "shareSubtitle": "قم بإنشاء رابط للآخرين لعرض مسار الرحلة ومعلومات الرحلة.",
        "includeExpenses": "تضمين النفقات",
        "includeJournals": "تضمين اليوميات",
        "includeChecklist": "تضمين قائمة التجهيزات",
        "includeBackup": "تضمين الخطط البديلة",
        "includeDocs": "تضمين المستندات والحجوزات",
        "docWarning": "قد تحتوي المستندات على رموز الحجز أو التذاكر أو أرقام الهواتف أو روابط خاصة. قم بتمكين ذلك فقط إذا كنت تثق بمستلم الرابط.",
        "pinProtect": "حماية برمز PIN",
        "pinDesc": "يجب على المشاهدين إدخال رمز PIN الصحيح للفتح",
        "enterPin": "أدخل رمز PIN من 4 أرقام:",
        "pinReady": "رمز PIN جاهز",
        "pinError": "يرجى إدخال 4 أرقام بالضبط",
        "close": "إغلاق",
        "creatingLink": "جاري إنشاء الرابط...",
        "createLink": "إنشاء رابط مشاركة",
        "linkCreated": "تم إنشاء رابط المشاركة",
        "joinTrip": "انضم إلى رحلة \"{{trip}}\" معي على KAT Journey!",
        "syncingChanges": "جاري المزامنة التلقائية لآخر التغييرات...",
        "autoSyncLast": "مزامنة تلقائية عند التغيير. الأخير:",
        "justNow": "الآن",
        "syncing": "جاري المزامنة...",
        "syncData": "مزامنة البيانات",
        "turningOff": "جاري إيقاف التشغيل...",
        "turnOff": "إيقاف المشاركة"
    }
}

def translate_share_modal():
    locales_dir = "src/locales"
    for lang, trans in share_translations.items():
        filepath = os.path.join(locales_dir, f"{lang}.json")
        if not os.path.exists(filepath):
            trans = share_translations["en"]
            
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
                
            if "share" not in data:
                data["share"] = {}
                
            for k, v in trans.items():
                data["share"][k] = v
                
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
        except Exception as e:
            pass

if __name__ == "__main__":
    translate_share_modal()
