import json
import os

translations = {
    "vi": {
        "wrappedSubtitle": "Nhìn lại những dấu ấn đáng nhớ trong chuyến đi của bạn.",
        "wrappedExportPdf": "Xuất PDF",
        "wrappedExporting": "Đang xuất...",
        "wrappedDayTrip": "Chuyến đi trong ngày",
        "wrappedDays": "Ngày hành trình",
        "wrappedEvents": "Mục lịch trình",
        "wrappedPacking": "Hành lý",
        "wrappedJournals": "Bài viết",
        "wrappedExpenseTitle": "CHI PHÍ CHUYẾN ĐI",
        "wrappedTotalExpense": "Tổng chi phí",
        "wrappedSharedExpense": "Chi chung chuyến đi",
        "wrappedPersonalExpense": "Chi cá nhân",
        "wrappedNoMembersExpense": "Chưa có người đồng hành để gợi ý cân đối chia tiền.",
        "wrappedTopPayer": "Nhà tài trợ chính",
        "wrappedTopPayerDesc": "là người chi nhiều nhất với",
        "wrappedNoExpenseData": "Chưa có dữ liệu chi phí cho chuyến đi này.",
        "wrappedMoodTitle": "DẤU ẤN CẢM XÚC",
        "wrappedMoodDesc": "Cảm xúc chủ đạo được ghi nhận từ các bài viết trong bản tin hành trình của bạn.",
        "wrappedNoMoodData": "Chưa có đủ bài viết để tổng kết cảm xúc chuyến đi.",
        "wrappedNoMoodDesc": "Đăng thêm bản tin để lưu lại cảm xúc và khoảnh khắc đáng nhớ.",
        "wrappedPostFirstJournal": "Đăng bài viết đầu tiên",
        "wrappedFirstMoment": "Dấu ấn đầu tiên",
        "wrappedNoFirstMoment": "Chưa có dấu ấn đầu tiên. Hãy thêm hoạt động hoặc đăng bài viết để lưu lại khoảnh khắc mở đầu.",
        "wrappedFirstMomentEvent1": "Bạn đã bắt đầu với",
        "wrappedFirstMomentEvent2": "vào ngày",
        "wrappedFirstMomentJournal1": "Kỷ niệm đầu tiên được ghi lại vào ngày",
        "wrappedBusiestDay": "Ngày nổi bật nhất",
        "wrappedBusiestDayDesc": "là ngày bận rộn nhất với",
        "wrappedBusiestDayDesc2": "hoạt động được ghi nhận.",
        "wrappedNoBusiestDay": "Chưa có ngày nào đủ dữ liệu để chọn làm ngày nổi bật.",
        "wrappedLocations": "Điểm đến đã ghé qua",
        "wrappedNoLocations": "Chưa có điểm đến cụ thể nào trong lịch trình."
    },
    "en": {
        "wrappedSubtitle": "Look back at the memorable moments of your trip.",
        "wrappedExportPdf": "Export PDF",
        "wrappedExporting": "Exporting...",
        "wrappedDayTrip": "Day Trip",
        "wrappedDays": "Trip Days",
        "wrappedEvents": "Timeline Events",
        "wrappedPacking": "Packing",
        "wrappedJournals": "Journals",
        "wrappedExpenseTitle": "TRIP EXPENSES",
        "wrappedTotalExpense": "Total Expense",
        "wrappedSharedExpense": "Shared Expense",
        "wrappedPersonalExpense": "Personal Expense",
        "wrappedNoMembersExpense": "No companions yet to suggest bill splitting.",
        "wrappedTopPayer": "Top Spender",
        "wrappedTopPayerDesc": "is the top spender with",
        "wrappedNoExpenseData": "No expense data for this trip yet.",
        "wrappedMoodTitle": "TRIP MOOD",
        "wrappedMoodDesc": "The primary mood recorded from the journals in your trip.",
        "wrappedNoMoodData": "Not enough journals to summarize trip mood.",
        "wrappedNoMoodDesc": "Post more journals to capture your feelings and moments.",
        "wrappedPostFirstJournal": "Post first journal",
        "wrappedFirstMoment": "First Moment",
        "wrappedNoFirstMoment": "No first moment yet. Add an activity or journal to save your beginning.",
        "wrappedFirstMomentEvent1": "You started with",
        "wrappedFirstMomentEvent2": "on",
        "wrappedFirstMomentJournal1": "The first memory was recorded on",
        "wrappedBusiestDay": "Busiest Day",
        "wrappedBusiestDayDesc": "is the busiest day with",
        "wrappedBusiestDayDesc2": "activities recorded.",
        "wrappedNoBusiestDay": "Not enough data to pick a busiest day.",
        "wrappedLocations": "Locations Visited",
        "wrappedNoLocations": "No specific locations in the timeline yet."
    },
    "ja": {
        "wrappedSubtitle": "旅行の思い出深い瞬間を振り返りましょう。",
        "wrappedExportPdf": "PDF出力",
        "wrappedExporting": "出力中...",
        "wrappedDayTrip": "日帰り旅行",
        "wrappedDays": "旅行日数",
        "wrappedEvents": "タイムライン数",
        "wrappedPacking": "持ち物",
        "wrappedJournals": "ジャーナル",
        "wrappedExpenseTitle": "旅行の費用",
        "wrappedTotalExpense": "総費用",
        "wrappedSharedExpense": "共有費用",
        "wrappedPersonalExpense": "個人費用",
        "wrappedNoMembersExpense": "割り勘を提案する同行者がまだいません。",
        "wrappedTopPayer": "最大の支出者",
        "wrappedTopPayerDesc": "最大の支出者で、その額は",
        "wrappedNoExpenseData": "この旅行の費用データはまだありません。",
        "wrappedMoodTitle": "旅行の気分",
        "wrappedMoodDesc": "旅行のジャーナルから記録された主な気分。",
        "wrappedNoMoodData": "気分をまとめるのに十分なジャーナルがありません。",
        "wrappedNoMoodDesc": "感情や瞬間を記録するためにジャーナルを追加してください。",
        "wrappedPostFirstJournal": "最初のジャーナルを投稿",
        "wrappedFirstMoment": "最初の瞬間",
        "wrappedNoFirstMoment": "まだ最初の瞬間がありません。活動やジャーナルを追加して始まりを記録してください。",
        "wrappedFirstMomentEvent1": "最初の活動は",
        "wrappedFirstMomentEvent2": "日付は",
        "wrappedFirstMomentJournal1": "最初の思い出が記録されたのは",
        "wrappedBusiestDay": "最も忙しい日",
        "wrappedBusiestDayDesc": "は最も忙しい日で",
        "wrappedBusiestDayDesc2": "件の活動が記録されました。",
        "wrappedNoBusiestDay": "最も忙しい日を選ぶのに十分なデータがありません。",
        "wrappedLocations": "訪れた場所",
        "wrappedNoLocations": "タイムラインにまだ具体的な場所がありません。"
    },
    "ko": {
        "wrappedSubtitle": "여행의 잊지 못할 순간을 돌아보세요.",
        "wrappedExportPdf": "PDF 내보내기",
        "wrappedExporting": "내보내는 중...",
        "wrappedDayTrip": "당일 여행",
        "wrappedDays": "여행 일수",
        "wrappedEvents": "타임라인 항목",
        "wrappedPacking": "짐싸기",
        "wrappedJournals": "저널",
        "wrappedExpenseTitle": "여행 경비",
        "wrappedTotalExpense": "총 경비",
        "wrappedSharedExpense": "공동 경비",
        "wrappedPersonalExpense": "개인 경비",
        "wrappedNoMembersExpense": "비용 분담을 제안할 동행인이 아직 없습니다.",
        "wrappedTopPayer": "최고 지출자",
        "wrappedTopPayerDesc": "최고 지출자이며 금액은",
        "wrappedNoExpenseData": "이 여행에 대한 지출 데이터가 아직 없습니다.",
        "wrappedMoodTitle": "여행 기분",
        "wrappedMoodDesc": "여행 저널에서 기록된 주요 기분입니다.",
        "wrappedNoMoodData": "여행 기분을 요약할 저널이 부족합니다.",
        "wrappedNoMoodDesc": "감정과 순간을 포착하려면 저널을 더 게시하세요.",
        "wrappedPostFirstJournal": "첫 저널 게시",
        "wrappedFirstMoment": "첫 번째 순간",
        "wrappedNoFirstMoment": "아직 첫 번째 순간이 없습니다. 활동이나 저널을 추가하여 시작을 저장하세요.",
        "wrappedFirstMomentEvent1": "첫 활동:",
        "wrappedFirstMomentEvent2": "날짜:",
        "wrappedFirstMomentJournal1": "첫 번째 추억이 기록된 날짜:",
        "wrappedBusiestDay": "가장 바쁜 날",
        "wrappedBusiestDayDesc": "은(는) 가장 바쁜 날로",
        "wrappedBusiestDayDesc2": "개의 활동이 기록되었습니다.",
        "wrappedNoBusiestDay": "가장 바쁜 날을 선택하기에 데이터가 부족합니다.",
        "wrappedLocations": "방문한 장소",
        "wrappedNoLocations": "타임라인에 아직 특정 장소가 없습니다."
    },
    "zh": {
        "wrappedSubtitle": "回顾您旅行中难忘的时刻。",
        "wrappedExportPdf": "导出 PDF",
        "wrappedExporting": "正在导出...",
        "wrappedDayTrip": "一日游",
        "wrappedDays": "旅行天数",
        "wrappedEvents": "时间表项目",
        "wrappedPacking": "行李",
        "wrappedJournals": "日志",
        "wrappedExpenseTitle": "旅行费用",
        "wrappedTotalExpense": "总费用",
        "wrappedSharedExpense": "共同费用",
        "wrappedPersonalExpense": "个人费用",
        "wrappedNoMembersExpense": "还没有同行者可以建议分摊费用。",
        "wrappedTopPayer": "最大支出者",
        "wrappedTopPayerDesc": "是最大支出者，金额为",
        "wrappedNoExpenseData": "本次旅行还没有费用数据。",
        "wrappedMoodTitle": "旅行心情",
        "wrappedMoodDesc": "从您的旅行日志中记录的主要心情。",
        "wrappedNoMoodData": "没有足够的日志来总结旅行心情。",
        "wrappedNoMoodDesc": "发布更多日志以捕捉您的感受和时刻。",
        "wrappedPostFirstJournal": "发布第一篇日志",
        "wrappedFirstMoment": "第一个瞬间",
        "wrappedNoFirstMoment": "还没有第一个瞬间。添加一个活动或日志以保存您的开始。",
        "wrappedFirstMomentEvent1": "第一个活动是",
        "wrappedFirstMomentEvent2": "日期是",
        "wrappedFirstMomentJournal1": "第一个回忆记录于",
        "wrappedBusiestDay": "最忙的一天",
        "wrappedBusiestDayDesc": "是最忙碌的一天，记录了",
        "wrappedBusiestDayDesc2": "个活动。",
        "wrappedNoBusiestDay": "数据不足以选出最忙碌的一天。",
        "wrappedLocations": "去过的地方",
        "wrappedNoLocations": "时间表中还没有具体的地点。"
    },
    "th": {
        "wrappedSubtitle": "มองย้อนกลับไปในช่วงเวลาที่น่าจดจำของการเดินทางของคุณ",
        "wrappedExportPdf": "ส่งออก PDF",
        "wrappedExporting": "กำลังส่งออก...",
        "wrappedDayTrip": "เที่ยววันเดียว",
        "wrappedDays": "จำนวนวัน",
        "wrappedEvents": "กิจกรรมไทม์ไลน์",
        "wrappedPacking": "จัดกระเป๋า",
        "wrappedJournals": "บันทึกการเดินทาง",
        "wrappedExpenseTitle": "ค่าใช้จ่ายการเดินทาง",
        "wrappedTotalExpense": "ค่าใช้จ่ายทั้งหมด",
        "wrappedSharedExpense": "ค่าใช้จ่ายส่วนรวม",
        "wrappedPersonalExpense": "ค่าใช้จ่ายส่วนตัว",
        "wrappedNoMembersExpense": "ยังไม่มีผู้ร่วมเดินทางเพื่อแนะนำการแบ่งจ่าย",
        "wrappedTopPayer": "ผู้ใช้จ่ายมากที่สุด",
        "wrappedTopPayerDesc": "คือผู้ใช้จ่ายมากที่สุดด้วยจำนวนเงิน",
        "wrappedNoExpenseData": "ยังไม่มีข้อมูลค่าใช้จ่ายสำหรับการเดินทางนี้",
        "wrappedMoodTitle": "อารมณ์การเดินทาง",
        "wrappedMoodDesc": "อารมณ์หลักที่บันทึกไว้จากบันทึกการเดินทางของคุณ",
        "wrappedNoMoodData": "ไม่มีบันทึกเพียงพอที่จะสรุปอารมณ์การเดินทาง",
        "wrappedNoMoodDesc": "โพสต์บันทึกเพิ่มเติมเพื่อเก็บความรู้สึกและช่วงเวลาของคุณ",
        "wrappedPostFirstJournal": "โพสต์บันทึกแรก",
        "wrappedFirstMoment": "ช่วงเวลาแรก",
        "wrappedNoFirstMoment": "ยังไม่มีช่วงเวลาแรก เพิ่มกิจกรรมหรือบันทึกเพื่อบันทึกการเริ่มต้นของคุณ",
        "wrappedFirstMomentEvent1": "คุณเริ่มต้นด้วย",
        "wrappedFirstMomentEvent2": "ในวันที่",
        "wrappedFirstMomentJournal1": "ความทรงจำแรกถูกบันทึกในวันที่",
        "wrappedBusiestDay": "วันที่ยุ่งที่สุด",
        "wrappedBusiestDayDesc": "เป็นวันที่ยุ่งที่สุดโดยมี",
        "wrappedBusiestDayDesc2": "กิจกรรมที่บันทึกไว้",
        "wrappedNoBusiestDay": "ข้อมูลไม่เพียงพอที่จะเลือกวันที่ยุ่งที่สุด",
        "wrappedLocations": "สถานที่ที่เยี่ยมชม",
        "wrappedNoLocations": "ยังไม่มีสถานที่เฉพาะเจาะจงในไทม์ไลน์"
    }
}

for lang, data in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        file_data = json.load(f)
        
    if "more" not in file_data:
        file_data["more"] = {}
        
    for k, v in data.items():
        file_data["more"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(file_data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
