import json
import os

locales_dir = 'src/locales'

# A dictionary for the translations of the missing backup-related share keys
translations = {
  "fr": {
    "backupPlanTitle": "Plan de secours",
    "backupPlanSubtitle": "Plan B pour les imprévus",
    "forActivity": "Pour l'activité",
    "planName": "Nom du plan *",
    "planNamePlaceholder": "ex : Restaurant près de l'hôtel, lieu couvert...",
    "planType": "Type de plan",
    "whenToUse": "Quand l'utiliser ?",
    "whenToUsePlaceholder": "ex : S'il pleut, si c'est fermé, trop de monde...",
    "additionalInfo": "Informations supplémentaires",
    "locationPlaceholder": "ex : Restaurant B près de l'hôtel",
    "googleMapsLink": "Lien Google Maps",
    "googleMapsPlaceholder": "ex : https://www.google.com/maps/dir/...",
    "estimatedCost": "Coût estimé",
    "estimatedCostPlaceholder": "ex : 200000",
    "notes": "Remarques",
    "notesPlaceholder": "ex : Appeler avant d'arriver, prendre un taxi...",
    "cancel": "Annuler",
    "savePlan": "Enregistrer",
    "sendProposal": "Envoyer la proposition",
    "noBackupPlanTitle": "Aucun plan de secours",
    "noBackupPlanDesc": "Ajoutez une alternative pour plus de flexibilité en cas d'imprévu.",
    "addFirstPlan": "Ajouter un premier plan",
    "proposeFirstPlan": "Proposer un premier plan",
    "newProposal": "Nouvelle proposition",
    "editProposal": "Modifier la proposition",
    "deleteProposal": "Supprimer la proposition",
    "loadingMap": "Chargement de la carte...",
    "viewTravelRoute": "Voir l'itinéraire",
    "openWithGoogleMaps": "Ouvrir avec Google Maps",
    "viewMap": "Voir la carte",
    "editPlan": "Modifier le plan",
    "deletePlan": "Supprimer le plan",
    "deletePlanConfirmTitle": "Supprimer ce plan de secours ?",
    "deletePlanConfirmDesc": "Ce plan n'apparaîtra plus dans le voyage. Cette action est irréversible.",
    "proposeDeletePlanTitle": "Proposer la suppression de ce plan ?",
    "proposeDeletePlanDesc": "Une proposition de suppression sera envoyée à l'organisateur.",
    "updatedDirectly": "Mis à jour directement !",
    "proposalSent": "Proposition envoyée. L'organisateur va l'examiner.",
    "typeFood": "Restauration",
    "typePlace": "Lieu alternatif",
    "typeTransport": "Transport",
    "typeHotel": "Hébergement",
    "typeIndoor": "En intérieur",
    "typeBadWeather": "Mauvais temps",
    "typeOther": "Autre",
    "delete": "Supprimer"
  },
  "es": {
    "backupPlanTitle": "Plan de respaldo",
    "backupPlanSubtitle": "Plan B para imprevistos",
    "forActivity": "Para la actividad",
    "planName": "Nombre del plan *",
    "planNamePlaceholder": "ej., Restaurante cerca del hotel, lugar cubierto...",
    "planType": "Tipo de plan",
    "whenToUse": "¿Cuándo usar?",
    "whenToUsePlaceholder": "ej., Si llueve, está cerrado, hay mucha gente...",
    "additionalInfo": "Información adicional",
    "locationPlaceholder": "ej., Restaurante B cerca del hotel",
    "googleMapsLink": "Enlace de Google Maps",
    "googleMapsPlaceholder": "ej., https://www.google.com/maps/dir/...",
    "estimatedCost": "Costo estimado",
    "estimatedCostPlaceholder": "ej., 200000",
    "notes": "Notas",
    "notesPlaceholder": "ej., Llamar antes de llegar, tomar un taxi...",
    "cancel": "Cancelar",
    "savePlan": "Guardar plan",
    "sendProposal": "Enviar propuesta",
    "noBackupPlanTitle": "Aún no hay planes de respaldo",
    "noBackupPlanDesc": "Añade una alternativa para dar flexibilidad al viaje ante imprevistos.",
    "addFirstPlan": "Añadir el primer plan",
    "proposeFirstPlan": "Proponer el primer plan",
    "newProposal": "Nueva propuesta",
    "editProposal": "Editar propuesta",
    "deleteProposal": "Eliminar propuesta",
    "loadingMap": "Cargando mapa...",
    "viewTravelRoute": "Ver ruta de viaje",
    "openWithGoogleMaps": "Abrir con Google Maps",
    "viewMap": "Ver mapa",
    "editPlan": "Editar plan",
    "deletePlan": "Eliminar plan",
    "deletePlanConfirmTitle": "¿Eliminar este plan de respaldo?",
    "deletePlanConfirmDesc": "Este plan ya no aparecerá en el viaje. Esta acción no se puede deshacer.",
    "proposeDeletePlanTitle": "¿Proponer eliminar este plan?",
    "proposeDeletePlanDesc": "Se enviará una propuesta al creador del viaje para su revisión.",
    "updatedDirectly": "¡Actualizado directamente!",
    "proposalSent": "Propuesta enviada. El creador del viaje la revisará.",
    "typeFood": "Comida",
    "typePlace": "Lugar alternativo",
    "typeTransport": "Transporte",
    "typeHotel": "Alojamiento",
    "typeIndoor": "Interior",
    "typeBadWeather": "Mal tiempo",
    "typeOther": "Otro",
    "delete": "Eliminar"
  },
  "de": {
    "backupPlanTitle": "Notfallplan",
    "backupPlanSubtitle": "Plan B für unvorhergesehene Fälle",
    "forActivity": "Für Aktivität",
    "planName": "Planname *",
    "planNamePlaceholder": "z.B. Restaurant in Hotelnähe, Indoor-Aktivität...",
    "planType": "Plantyp",
    "whenToUse": "Wann nutzen?",
    "whenToUsePlaceholder": "z.B. bei Regen, geschlossen, zu voll...",
    "additionalInfo": "Zusätzliche Informationen",
    "locationPlaceholder": "z.B. Restaurant B in Hotelnähe",
    "googleMapsLink": "Google Maps-Link",
    "googleMapsPlaceholder": "z.B. https://www.google.com/maps/dir/...",
    "estimatedCost": "Geschätzte Kosten",
    "estimatedCostPlaceholder": "z.B. 200000",
    "notes": "Notizen",
    "notesPlaceholder": "z.B. Vor Ankunft anrufen, Taxi nehmen...",
    "cancel": "Abbrechen",
    "savePlan": "Plan speichern",
    "sendProposal": "Vorschlag senden",
    "noBackupPlanTitle": "Noch keine Notfallpläne",
    "noBackupPlanDesc": "Fügen Sie Alternativen hinzu, um bei Änderungen flexibel zu bleiben.",
    "addFirstPlan": "Ersten Plan hinzufügen",
    "proposeFirstPlan": "Ersten Plan vorschlagen",
    "newProposal": "Neuer Vorschlag",
    "editProposal": "Vorschlag bearbeiten",
    "deleteProposal": "Vorschlag löschen",
    "loadingMap": "Karte wird geladen...",
    "viewTravelRoute": "Reiseroute anzeigen",
    "openWithGoogleMaps": "Mit Google Maps öffnen",
    "viewMap": "Karte anzeigen",
    "editPlan": "Plan bearbeiten",
    "deletePlan": "Plan löschen",
    "deletePlanConfirmTitle": "Diesen Notfallplan löschen?",
    "deletePlanConfirmDesc": "Dieser Plan wird aus der Reise entfernt. Dies kann nicht rückgängig gemacht werden.",
    "proposeDeletePlanTitle": "Löschen dieses Plans vorschlagen?",
    "proposeDeletePlanDesc": "Ein Vorschlag wird zur Überprüfung an den Reiseveranstalter gesendet.",
    "updatedDirectly": "Direkt aktualisiert!",
    "proposalSent": "Vorschlag gesendet. Er wird nun überprüft.",
    "typeFood": "Essen",
    "typePlace": "Alternativer Ort",
    "typeTransport": "Transport",
    "typeHotel": "Unterkunft",
    "typeIndoor": "Indoor",
    "typeBadWeather": "Schlechtes Wetter",
    "typeOther": "Sonstiges",
    "delete": "Löschen"
  },
  "it": {
    "backupPlanTitle": "Piano di riserva",
    "backupPlanSubtitle": "Piano B per imprevisti",
    "forActivity": "Per l'attività",
    "planName": "Nome del piano *",
    "planNamePlaceholder": "es., Ristorante vicino all'hotel, luogo al coperto...",
    "planType": "Tipo di piano",
    "whenToUse": "Quando usarlo?",
    "whenToUsePlaceholder": "es., Se piove, è chiuso, c'è troppa gente...",
    "additionalInfo": "Informazioni aggiuntive",
    "locationPlaceholder": "es., Ristorante B vicino all'hotel",
    "googleMapsLink": "Link di Google Maps",
    "googleMapsPlaceholder": "es., https://www.google.com/maps/dir/...",
    "estimatedCost": "Costo stimato",
    "estimatedCostPlaceholder": "es., 200000",
    "notes": "Note",
    "notesPlaceholder": "es., Chiamare prima di arrivare, prendere un taxi...",
    "cancel": "Annulla",
    "savePlan": "Salva piano",
    "sendProposal": "Invia proposta",
    "noBackupPlanTitle": "Nessun piano di riserva",
    "noBackupPlanDesc": "Aggiungi un'alternativa per rendere il viaggio più flessibile in caso di imprevisti.",
    "addFirstPlan": "Aggiungi il primo piano",
    "proposeFirstPlan": "Proponi il primo piano",
    "newProposal": "Nuova proposta",
    "editProposal": "Modifica proposta",
    "deleteProposal": "Elimina proposta",
    "loadingMap": "Caricamento mappa...",
    "viewTravelRoute": "Vedi percorso di viaggio",
    "openWithGoogleMaps": "Apri con Google Maps",
    "viewMap": "Vedi mappa",
    "editPlan": "Modifica piano",
    "deletePlan": "Elimina piano",
    "deletePlanConfirmTitle": "Eliminare questo piano di riserva?",
    "deletePlanConfirmDesc": "Questo piano non apparirà più nel viaggio. L'azione è irreversibile.",
    "proposeDeletePlanTitle": "Proporre l'eliminazione di questo piano?",
    "proposeDeletePlanDesc": "Verrà inviata una proposta al creatore del viaggio per l'approvazione.",
    "updatedDirectly": "Aggiornato direttamente!",
    "proposalSent": "Proposta inviata. Il creatore del viaggio la valuterà.",
    "typeFood": "Ristorazione",
    "typePlace": "Luogo alternativo",
    "typeTransport": "Trasporto",
    "typeHotel": "Alloggio",
    "typeIndoor": "Al coperto",
    "typeBadWeather": "Maltempo",
    "typeOther": "Altro",
    "delete": "Elimina"
  },
  "pt": {
    "backupPlanTitle": "Plano de backup",
    "backupPlanSubtitle": "Plano B para imprevistos",
    "forActivity": "Para a atividade",
    "planName": "Nome do plano *",
    "planNamePlaceholder": "ex., Restaurante perto do hotel, local coberto...",
    "planType": "Tipo de plano",
    "whenToUse": "Quando usar?",
    "whenToUsePlaceholder": "ex., Se chover, estiver fechado, muita gente...",
    "additionalInfo": "Informações adicionais",
    "locationPlaceholder": "ex., Restaurante B perto do hotel",
    "googleMapsLink": "Link do Google Maps",
    "googleMapsPlaceholder": "ex., https://www.google.com/maps/dir/...",
    "estimatedCost": "Custo estimado",
    "estimatedCostPlaceholder": "ex., 200000",
    "notes": "Notas",
    "notesPlaceholder": "ex., Ligar antes de chegar, pegar um táxi...",
    "cancel": "Cancelar",
    "savePlan": "Salvar plano",
    "sendProposal": "Enviar proposta",
    "noBackupPlanTitle": "Nenhum plano de backup ainda",
    "noBackupPlanDesc": "Adicione uma alternativa para tornar o viagem mais flexível.",
    "addFirstPlan": "Adicionar o primeiro plano",
    "proposeFirstPlan": "Propor o primeiro plano",
    "newProposal": "Nova proposta",
    "editProposal": "Editar proposta",
    "deleteProposal": "Excluir proposta",
    "loadingMap": "Carregando mapa...",
    "viewTravelRoute": "Ver rota de viagem",
    "openWithGoogleMaps": "Abrir com o Google Maps",
    "viewMap": "Ver mapa",
    "editPlan": "Editar plano",
    "deletePlan": "Excluir plano",
    "deletePlanConfirmTitle": "Excluir este plano de backup?",
    "deletePlanConfirmDesc": "Este plano não aparecerá mais na viagem. Esta ação não pode ser desfeita.",
    "proposeDeletePlanTitle": "Propor a exclusão deste plano?",
    "proposeDeletePlanDesc": "Uma proposta será enviada ao dono da viagem para análise.",
    "updatedDirectly": "Atualizado diretamente!",
    "proposalSent": "Proposta enviada. O dono da viagem irá analisá-la.",
    "typeFood": "Alimentação",
    "typePlace": "Lugar alternativo",
    "typeTransport": "Transporte",
    "typeHotel": "Acomodação",
    "typeIndoor": "Local coberto",
    "typeBadWeather": "Tempo ruim",
    "typeOther": "Outro",
    "delete": "Excluir"
  },
  "id": {
    "backupPlanTitle": "Rencana cadangan",
    "backupPlanSubtitle": "Rencana B untuk situasi tak terduga",
    "forActivity": "Untuk aktivitas",
    "planName": "Nama rencana *",
    "planNamePlaceholder": "msl., Restoran dekat hotel, tempat indoor...",
    "planType": "Jenis rencana",
    "whenToUse": "Kapan digunakan?",
    "whenToUsePlaceholder": "msl., Saat hujan, tutup, terlalu ramai...",
    "additionalInfo": "Informasi tambahan",
    "locationPlaceholder": "msl., Restoran B dekat hotel",
    "googleMapsLink": "Tautan Google Maps",
    "googleMapsPlaceholder": "msl., https://www.google.com/maps/dir/...",
    "estimatedCost": "Perkiraan biaya",
    "estimatedCostPlaceholder": "msl., 200000",
    "notes": "Catatan",
    "notesPlaceholder": "msl., Telepon sebelum datang, naik taksi...",
    "cancel": "Batal",
    "savePlan": "Simpan rencana",
    "sendProposal": "Kirim usulan",
    "noBackupPlanTitle": "Belum ada rencana cadangan",
    "noBackupPlanDesc": "Tambahkan alternatif agar perjalanan lebih fleksibel saat ada perubahan.",
    "addFirstPlan": "Tambah rencana pertama",
    "proposeFirstPlan": "Usulkan rencana pertama",
    "newProposal": "Usulan baru",
    "editProposal": "Edit usulan",
    "deleteProposal": "Hapus usulan",
    "loadingMap": "Memuat peta...",
    "viewTravelRoute": "Lihat rute perjalanan",
    "openWithGoogleMaps": "Buka dengan Google Maps",
    "viewMap": "Lihat peta",
    "editPlan": "Edit rencana",
    "deletePlan": "Hapus rencana",
    "deletePlanConfirmTitle": "Hapus rencana cadangan ini?",
    "deletePlanConfirmDesc": "Rencana ini tidak akan muncul lagi di perjalanan. Tindakan ini tidak dapat dibatalkan.",
    "proposeDeletePlanTitle": "Usulkan penghapusan rencana ini?",
    "proposeDeletePlanDesc": "Usulan akan dikirim ke pemilik perjalanan untuk ditinjau.",
    "updatedDirectly": "Langsung diperbarui!",
    "proposalSent": "Usulan terkirim. Pemilik perjalanan akan meninjaunya.",
    "typeFood": "Makan",
    "typePlace": "Tempat alternatif",
    "typeTransport": "Transportasi",
    "typeHotel": "Akomodasi",
    "typeIndoor": "Dalam ruangan",
    "typeBadWeather": "Cuaca buruk",
    "typeOther": "Lainnya",
    "delete": "Hapus"
  },
  "ja": {
    "backupPlanTitle": "バックアッププラン",
    "backupPlanSubtitle": "予期せぬ事態のためのプランB",
    "forActivity": "対象アクティビティ",
    "planName": "プラン名 *",
    "planNamePlaceholder": "例：ホテルの近くのレストラン、屋内施設...",
    "planType": "プランの種類",
    "whenToUse": "いつ使う？",
    "whenToUsePlaceholder": "例：雨天時、閉まっている時、混雑時...",
    "additionalInfo": "追加情報",
    "locationPlaceholder": "例：ホテルの近くのレストランB",
    "googleMapsLink": "Googleマップリンク",
    "googleMapsPlaceholder": "例：https://www.google.com/maps/dir/...",
    "estimatedCost": "予想費用",
    "estimatedCostPlaceholder": "例：200000",
    "notes": "メモ",
    "notesPlaceholder": "例：到着前に電話する、タクシーに乗る...",
    "cancel": "キャンセル",
    "savePlan": "プランを保存",
    "sendProposal": "提案を送信",
    "noBackupPlanTitle": "バックアッププランはまだありません",
    "noBackupPlanDesc": "予定変更に備えて代替案を追加し、柔軟に対応できるようにしましょう。",
    "addFirstPlan": "最初のプランを追加",
    "proposeFirstPlan": "最初のプランを提案",
    "newProposal": "新規提案",
    "editProposal": "提案を編集",
    "deleteProposal": "提案を削除",
    "loadingMap": "地図を読み込み中...",
    "viewTravelRoute": "移動ルートを見る",
    "openWithGoogleMaps": "Googleマップで開く",
    "viewMap": "地図を見る",
    "editPlan": "プランを編集",
    "deletePlan": "プランを削除",
    "deletePlanConfirmTitle": "このプランを削除しますか？",
    "deletePlanConfirmDesc": "このプランは旅行に表示されなくなります。この操作は元に戻せません。",
    "proposeDeletePlanTitle": "このプランの削除を提案しますか？",
    "proposeDeletePlanDesc": "削除の提案が旅行のオーナーに送信されます。",
    "updatedDirectly": "直接更新されました！",
    "proposalSent": "提案を送信しました。オーナーが確認します。",
    "typeFood": "食事",
    "typePlace": "代替場所",
    "typeTransport": "交通",
    "typeHotel": "宿泊",
    "typeIndoor": "屋内",
    "typeBadWeather": "悪天候",
    "typeOther": "その他",
    "delete": "削除"
  },
  "ko": {
    "backupPlanTitle": "백업 계획",
    "backupPlanSubtitle": "예기치 않은 상황을 위한 플랜 B",
    "forActivity": "활동용",
    "planName": "계획 이름 *",
    "planNamePlaceholder": "예: 호텔 근처 식당, 실내 명소...",
    "planType": "계획 유형",
    "whenToUse": "언제 사용하나요?",
    "whenToUsePlaceholder": "예: 비가 올 때, 문을 닫았을 때, 혼잡할 때...",
    "additionalInfo": "추가 정보",
    "locationPlaceholder": "예: 호텔 근처 B 식당",
    "googleMapsLink": "Google 지도 링크",
    "googleMapsPlaceholder": "예: https://www.google.com/maps/dir/...",
    "estimatedCost": "예상 비용",
    "estimatedCostPlaceholder": "예: 200000",
    "notes": "메모",
    "notesPlaceholder": "예: 도착 전 전화하기, 택시 타기...",
    "cancel": "취소",
    "savePlan": "계획 저장",
    "sendProposal": "제안 보내기",
    "noBackupPlanTitle": "아직 백업 계획이 없습니다",
    "noBackupPlanDesc": "상황이 변할 때 여행을 더 유연하게 만들 수 있는 대안을 추가하세요.",
    "addFirstPlan": "첫 번째 계획 추가",
    "proposeFirstPlan": "첫 번째 계획 제안",
    "newProposal": "새 제안",
    "editProposal": "제안 편집",
    "deleteProposal": "제안 삭제",
    "loadingMap": "지도 로드 중...",
    "viewTravelRoute": "여행 경로 보기",
    "openWithGoogleMaps": "Google 지도로 열기",
    "viewMap": "지도 보기",
    "editPlan": "계획 편집",
    "deletePlan": "계획 삭제",
    "deletePlanConfirmTitle": "이 백업 계획을 삭제하시겠습니까?",
    "deletePlanConfirmDesc": "이 계획은 여행에 더 이상 나타나지 않습니다. 이 작업은 취소할 수 없습니다.",
    "proposeDeletePlanTitle": "이 계획 삭제를 제안하시겠습니까?",
    "proposeDeletePlanDesc": "삭제 제안이 여행 주최자에게 전송됩니다.",
    "updatedDirectly": "직접 업데이트되었습니다!",
    "proposalSent": "제안이 전송되었습니다. 주최자가 검토할 것입니다.",
    "typeFood": "식사",
    "typePlace": "대체 장소",
    "typeTransport": "교통",
    "typeHotel": "숙박",
    "typeIndoor": "실내",
    "typeBadWeather": "악천후",
    "typeOther": "기타",
    "delete": "삭제"
  },
  "th": {
    "backupPlanTitle": "แผนสำรอง",
    "backupPlanSubtitle": "แผน B สำหรับสถานการณ์ที่ไม่คาดคิด",
    "forActivity": "สำหรับกิจกรรม",
    "planName": "ชื่อแผน *",
    "planNamePlaceholder": "เช่น ร้านอาหารใกล้โรงแรม, สถานที่ในร่ม...",
    "planType": "ประเภทแผน",
    "whenToUse": "ใช้เมื่อไหร่?",
    "whenToUsePlaceholder": "เช่น เมื่อฝนตก, ร้านปิด, คนเยอะ...",
    "additionalInfo": "ข้อมูลเพิ่มเติม",
    "locationPlaceholder": "เช่น ร้านอาหาร B ใกล้โรงแรม",
    "googleMapsLink": "ลิงก์ Google Maps",
    "googleMapsPlaceholder": "เช่น https://www.google.com/maps/dir/...",
    "estimatedCost": "ค่าใช้จ่ายโดยประมาณ",
    "estimatedCostPlaceholder": "เช่น 200000",
    "notes": "หมายเหตุ",
    "notesPlaceholder": "เช่น โทรแจ้งก่อนมาถึง, นั่งแท็กซี่...",
    "cancel": "ยกเลิก",
    "savePlan": "บันทึกแผน",
    "sendProposal": "ส่งข้อเสนอ",
    "noBackupPlanTitle": "ยังไม่มีแผนสำรอง",
    "noBackupPlanDesc": "เพิ่มทางเลือกเพื่อให้การเดินทางยืดหยุ่นขึ้นเมื่อสถานการณ์เปลี่ยนไป",
    "addFirstPlan": "เพิ่มแผนแรก",
    "proposeFirstPlan": "เสนอแผนแรก",
    "newProposal": "ข้อเสนอใหม่",
    "editProposal": "แก้ไขข้อเสนอ",
    "deleteProposal": "ลบข้อเสนอ",
    "loadingMap": "กำลังโหลดแผนที่...",
    "viewTravelRoute": "ดูเส้นทางการเดินทาง",
    "openWithGoogleMaps": "เปิดด้วย Google Maps",
    "viewMap": "ดูแผนที่",
    "editPlan": "แก้ไขแผน",
    "deletePlan": "ลบแผน",
    "deletePlanConfirmTitle": "ลบแผนสำรองนี้?",
    "deletePlanConfirmDesc": "แผนนี้จะไม่ปรากฏในการเดินทางอีก การกระทำนี้ไม่สามารถยกเลิกได้",
    "proposeDeletePlanTitle": "เสนอให้ลบแผนนี้?",
    "proposeDeletePlanDesc": "ข้อเสนอให้ลบจะถูกส่งไปยังเจ้าของการเดินทางเพื่อพิจารณา",
    "updatedDirectly": "อัปเดตโดยตรงแล้ว!",
    "proposalSent": "ส่งข้อเสนอแล้ว เจ้าของการเดินทางจะตรวจสอบ",
    "typeFood": "อาหาร",
    "typePlace": "สถานที่ทางเลือก",
    "typeTransport": "การเดินทาง",
    "typeHotel": "ที่พัก",
    "typeIndoor": "ในร่ม",
    "typeBadWeather": "สภาพอากาศแย่",
    "typeOther": "อื่นๆ",
    "delete": "ลบ"
  },
  "zh": {
    "backupPlanTitle": "备用计划",
    "backupPlanSubtitle": "应对突发情况的 B 计划",
    "forActivity": "针对活动",
    "planName": "计划名称 *",
    "planNamePlaceholder": "例如：酒店附近的餐厅、室内景点...",
    "planType": "计划类型",
    "whenToUse": "何时使用？",
    "whenToUsePlaceholder": "例如：下雨时、关门时、太拥挤时...",
    "additionalInfo": "附加信息",
    "locationPlaceholder": "例如：酒店附近的 B 餐厅",
    "googleMapsLink": "谷歌地图链接",
    "googleMapsPlaceholder": "例如：https://www.google.com/maps/dir/...",
    "estimatedCost": "预估费用",
    "estimatedCostPlaceholder": "例如：200000",
    "notes": "备注",
    "notesPlaceholder": "例如：到达前打电话、乘出租车...",
    "cancel": "取消",
    "savePlan": "保存计划",
    "sendProposal": "发送建议",
    "noBackupPlanTitle": "暂无备用计划",
    "noBackupPlanDesc": "添加一个替代方案，让旅行在发生变化时更加灵活。",
    "addFirstPlan": "添加第一个计划",
    "proposeFirstPlan": "建议第一个计划",
    "newProposal": "新建议",
    "editProposal": "编辑建议",
    "deleteProposal": "删除建议",
    "loadingMap": "正在加载地图...",
    "viewTravelRoute": "查看旅行路线",
    "openWithGoogleMaps": "使用谷歌地图打开",
    "viewMap": "查看地图",
    "editPlan": "编辑计划",
    "deletePlan": "删除计划",
    "deletePlanConfirmTitle": "删除此备用计划？",
    "deletePlanConfirmDesc": "该计划将不再出现在行程中。此操作无法撤销。",
    "proposeDeletePlanTitle": "建议删除此计划？",
    "proposeDeletePlanDesc": "删除建议将发送给行程创建者以供审核。",
    "updatedDirectly": "已直接更新！",
    "proposalSent": "建议已发送。行程创建者将进行审核。",
    "typeFood": "餐饮",
    "typePlace": "替代地点",
    "typeTransport": "交通",
    "typeHotel": "住宿",
    "typeIndoor": "室内",
    "typeBadWeather": "恶劣天气",
    "typeOther": "其他",
    "delete": "删除"
  }
}

for lang, trans in translations.items():
    filepath = os.path.join(locales_dir, f"{lang}.json")
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if "share" not in data:
            data["share"] = {}
        data["share"].update(trans)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully updated missing backup strings in share namespace.")
