import json
import os

translations = {
    "vi": {
        "workspaceTitle": "Không gian chuyến đi",
        "workspaceDesc": "Tùy chỉnh thông tin, thành viên và dữ liệu cho hành trình của bạn.",
        "workspaceDescNoTrip": "Quản lý ứng dụng và cấu hình dữ liệu.",
        "currentTrip": "Hành trình hiện tại",
        "noLocation": "Chưa có địa điểm",
        "membersCount": "thành viên",
        "eventsCount": "lịch trình",
        "expensesCount": "chi phí",
        "packingProgress": "Chuẩn bị",
        "sectionFeatures": "Tính năng",
        "featureTripInfo": "Thông tin chuyến đi",
        "featureMembers": "Thành viên",
        "featureWrapped": "Tổng kết hành trình",
        "featureJournal": "Bản tin hành trình",
        "featureDocuments": "Vé, đặt chỗ & giấy tờ",
        "featureShare": "Chia sẻ chuyến đi",
        "sectionData": "QUẢN LÝ DỮ LIỆU",
        "dataTripData": "Dữ liệu chuyến đi",
        "dataBackup": "Sao lưu hành trình",
        "dataExportPdf": "Xuất báo cáo PDF",
        "dataExportExcel": "Xuất bảng tính Excel",
        "sectionDanger": "Vùng nguy hiểm",
        "actionEndTrip": "Kết thúc chuyến đi",
        "actionRestoreTrip": "Khôi phục chuyến đi",
        "actionDeleteTrip": "Xóa vĩnh viễn chuyến đi",
        "madeBy": "thực hiện bởi"
    },
    "en": {
        "workspaceTitle": "Trip Workspace",
        "workspaceDesc": "Customize info, members, and data for your journey.",
        "workspaceDescNoTrip": "Manage app and data configuration.",
        "currentTrip": "Current trip",
        "noLocation": "No location set",
        "membersCount": "members",
        "eventsCount": "events",
        "expensesCount": "expenses",
        "packingProgress": "Prepared",
        "sectionFeatures": "FEATURES",
        "featureTripInfo": "Trip Information",
        "featureMembers": "Members",
        "featureWrapped": "Trip Wrapped",
        "featureJournal": "Travel Journal",
        "featureDocuments": "Tickets & Documents",
        "featureShare": "Share Trip",
        "sectionData": "DATA MANAGEMENT",
        "dataTripData": "Trip Data",
        "dataBackup": "Backup Trip",
        "dataExportPdf": "Export PDF Report",
        "dataExportExcel": "Export Excel Spreadsheet",
        "sectionDanger": "Danger Zone",
        "actionEndTrip": "End trip",
        "actionRestoreTrip": "Restore trip",
        "actionDeleteTrip": "Delete trip permanently",
        "madeBy": "made by"
    },
    "ja": {
        "workspaceTitle": "旅行ワークスペース",
        "workspaceDesc": "旅行の情報、メンバー、データをカスタマイズします。",
        "workspaceDescNoTrip": "アプリとデータの構成を管理します。",
        "currentTrip": "現在の旅行",
        "noLocation": "場所未設定",
        "membersCount": "メンバー",
        "eventsCount": "イベント",
        "expensesCount": "費用",
        "packingProgress": "準備完了",
        "sectionFeatures": "機能",
        "featureTripInfo": "旅行情報",
        "featureMembers": "メンバー",
        "featureWrapped": "旅行のまとめ",
        "featureJournal": "旅行日記",
        "featureDocuments": "チケットと書類",
        "featureShare": "旅行を共有",
        "sectionData": "データ管理",
        "dataTripData": "旅行データ",
        "dataBackup": "旅行のバックアップ",
        "dataExportPdf": "PDFレポートを出力",
        "dataExportExcel": "Excelスプレッドシートを出力",
        "sectionDanger": "危険エリア",
        "actionEndTrip": "旅行を終了",
        "actionRestoreTrip": "旅行を復元",
        "actionDeleteTrip": "旅行を完全に削除",
        "madeBy": "開発者"
    },
    "ko": {
        "workspaceTitle": "여행 워크스페이스",
        "workspaceDesc": "여행 정보, 멤버 및 데이터를 사용자 지정합니다.",
        "workspaceDescNoTrip": "앱 및 데이터 구성을 관리합니다.",
        "currentTrip": "현재 여행",
        "noLocation": "위치 미설정",
        "membersCount": "멤버",
        "eventsCount": "일정",
        "expensesCount": "비용",
        "packingProgress": "준비됨",
        "sectionFeatures": "기능",
        "featureTripInfo": "여행 정보",
        "featureMembers": "멤버",
        "featureWrapped": "여행 요약",
        "featureJournal": "여행 일지",
        "featureDocuments": "티켓 및 문서",
        "featureShare": "여행 공유",
        "sectionData": "데이터 관리",
        "dataTripData": "여행 데이터",
        "dataBackup": "여행 백업",
        "dataExportPdf": "PDF 보고서 내보내기",
        "dataExportExcel": "Excel 스프레드시트 내보내기",
        "sectionDanger": "위험 구역",
        "actionEndTrip": "여행 종료",
        "actionRestoreTrip": "여행 복원",
        "actionDeleteTrip": "여행 영구 삭제",
        "madeBy": "제작자"
    },
    "zh": {
        "workspaceTitle": "旅行工作区",
        "workspaceDesc": "自定义您的行程信息、成员和数据。",
        "workspaceDescNoTrip": "管理应用和数据配置。",
        "currentTrip": "当前行程",
        "noLocation": "未设置地点",
        "membersCount": "成员",
        "eventsCount": "日程",
        "expensesCount": "费用",
        "packingProgress": "已准备",
        "sectionFeatures": "功能",
        "featureTripInfo": "行程信息",
        "featureMembers": "成员",
        "featureWrapped": "行程总结",
        "featureJournal": "旅行日记",
        "featureDocuments": "票务与证件",
        "featureShare": "分享行程",
        "sectionData": "数据管理",
        "dataTripData": "行程数据",
        "dataBackup": "备份行程",
        "dataExportPdf": "导出 PDF 报告",
        "dataExportExcel": "导出 Excel 表格",
        "sectionDanger": "危险区域",
        "actionEndTrip": "结束行程",
        "actionRestoreTrip": "恢复行程",
        "actionDeleteTrip": "永久删除行程",
        "madeBy": "制作者"
    },
    "es": {
        "workspaceTitle": "Espacio de viaje",
        "workspaceDesc": "Personaliza la información, miembros y datos de tu viaje.",
        "workspaceDescNoTrip": "Gestiona la configuración de la app y datos.",
        "currentTrip": "Viaje actual",
        "noLocation": "Sin ubicación",
        "membersCount": "miembros",
        "eventsCount": "eventos",
        "expensesCount": "gastos",
        "packingProgress": "Preparado",
        "sectionFeatures": "Funciones",
        "featureTripInfo": "Info del viaje",
        "featureMembers": "Miembros",
        "featureWrapped": "Resumen del viaje",
        "featureJournal": "Diario de viaje",
        "featureDocuments": "Billetes y documentos",
        "featureShare": "Compartir viaje",
        "sectionData": "Gestión de datos",
        "dataTripData": "Datos del viaje",
        "dataBackup": "Copiar viaje",
        "dataExportPdf": "Exportar PDF",
        "dataExportExcel": "Exportar Excel",
        "sectionDanger": "Zona de peligro",
        "actionEndTrip": "Finalizar viaje",
        "actionRestoreTrip": "Restaurar viaje",
        "actionDeleteTrip": "Eliminar viaje permanentemente",
        "madeBy": "hecho por"
    },
    "fr": {
        "workspaceTitle": "Espace de voyage",
        "workspaceDesc": "Personnalisez les infos, les membres et les données de votre voyage.",
        "workspaceDescNoTrip": "Gérer la configuration de l'application et des données.",
        "currentTrip": "Voyage actuel",
        "noLocation": "Aucun lieu",
        "membersCount": "membres",
        "eventsCount": "événements",
        "expensesCount": "dépenses",
        "packingProgress": "Préparé",
        "sectionFeatures": "Fonctionnalités",
        "featureTripInfo": "Infos du voyage",
        "featureMembers": "Membres",
        "featureWrapped": "Résumé du voyage",
        "featureJournal": "Journal de voyage",
        "featureDocuments": "Billets et documents",
        "featureShare": "Partager le voyage",
        "sectionData": "Gestion des données",
        "dataTripData": "Données du voyage",
        "dataBackup": "Sauvegarder",
        "dataExportPdf": "Exporter en PDF",
        "dataExportExcel": "Exporter en Excel",
        "sectionDanger": "Zone de danger",
        "actionEndTrip": "Terminer le voyage",
        "actionRestoreTrip": "Restaurer le voyage",
        "actionDeleteTrip": "Supprimer définitivement",
        "madeBy": "fait par"
    },
    "de": {
        "workspaceTitle": "Reise-Arbeitsbereich",
        "workspaceDesc": "Passen Sie Infos, Mitglieder und Daten für Ihre Reise an.",
        "workspaceDescNoTrip": "App- und Datenkonfiguration verwalten.",
        "currentTrip": "Aktuelle Reise",
        "noLocation": "Kein Ort",
        "membersCount": "Mitglieder",
        "eventsCount": "Ereignisse",
        "expensesCount": "Ausgaben",
        "packingProgress": "Vorbereitet",
        "sectionFeatures": "Funktionen",
        "featureTripInfo": "Reiseinfos",
        "featureMembers": "Mitglieder",
        "featureWrapped": "Reisezusammenfassung",
        "featureJournal": "Reisetagebuch",
        "featureDocuments": "Tickets & Dokumente",
        "featureShare": "Reise teilen",
        "sectionData": "Datenverwaltung",
        "dataTripData": "Reisedaten",
        "dataBackup": "Reise sichern",
        "dataExportPdf": "PDF exportieren",
        "dataExportExcel": "Excel exportieren",
        "sectionDanger": "Gefahrenzone",
        "actionEndTrip": "Reise beenden",
        "actionRestoreTrip": "Reise wiederherstellen",
        "actionDeleteTrip": "Reise dauerhaft löschen",
        "madeBy": "erstellt von"
    },
    "it": {
        "workspaceTitle": "Spazio di viaggio",
        "workspaceDesc": "Personalizza informazioni, membri e dati per il tuo viaggio.",
        "workspaceDescNoTrip": "Gestisci l'app e la configurazione dei dati.",
        "currentTrip": "Viaggio attuale",
        "noLocation": "Nessuna posizione",
        "membersCount": "membri",
        "eventsCount": "eventi",
        "expensesCount": "spese",
        "packingProgress": "Preparato",
        "sectionFeatures": "Funzionalità",
        "featureTripInfo": "Info viaggio",
        "featureMembers": "Membri",
        "featureWrapped": "Riassunto viaggio",
        "featureJournal": "Diario di viaggio",
        "featureDocuments": "Biglietti e documenti",
        "featureShare": "Condividi viaggio",
        "sectionData": "Gestione dati",
        "dataTripData": "Dati viaggio",
        "dataBackup": "Esegui backup",
        "dataExportPdf": "Esporta PDF",
        "dataExportExcel": "Esporta Excel",
        "sectionDanger": "Zona di pericolo",
        "actionEndTrip": "Termina viaggio",
        "actionRestoreTrip": "Ripristina viaggio",
        "actionDeleteTrip": "Elimina definitivamente",
        "madeBy": "creato da"
    },
    "pt": {
        "workspaceTitle": "Espaço de viagem",
        "workspaceDesc": "Personalize informações, membros e dados da sua viagem.",
        "workspaceDescNoTrip": "Gerencie o aplicativo e a configuração de dados.",
        "currentTrip": "Viagem atual",
        "noLocation": "Sem localização",
        "membersCount": "membros",
        "eventsCount": "eventos",
        "expensesCount": "despesas",
        "packingProgress": "Preparado",
        "sectionFeatures": "Recursos",
        "featureTripInfo": "Infos da viagem",
        "featureMembers": "Membros",
        "featureWrapped": "Resumo da viagem",
        "featureJournal": "Diário de viagem",
        "featureDocuments": "Passagens e docs",
        "featureShare": "Compartilhar",
        "sectionData": "Gestão de Dados",
        "dataTripData": "Dados da viagem",
        "dataBackup": "Fazer backup",
        "dataExportPdf": "Exportar PDF",
        "dataExportExcel": "Exportar Excel",
        "sectionDanger": "Zona de perigo",
        "actionEndTrip": "Encerrar viagem",
        "actionRestoreTrip": "Restaurar viagem",
        "actionDeleteTrip": "Excluir permanentemente",
        "madeBy": "feito por"
    },
    "th": {
        "workspaceTitle": "พื้นที่การเดินทาง",
        "workspaceDesc": "ปรับแต่งข้อมูล สมาชิก และข้อมูลสำหรับการเดินทางของคุณ",
        "workspaceDescNoTrip": "จัดการแอปและการกำหนดค่าข้อมูล",
        "currentTrip": "ทริปปัจจุบัน",
        "noLocation": "ไม่มีสถานที่",
        "membersCount": "สมาชิก",
        "eventsCount": "กิจกรรม",
        "expensesCount": "ค่าใช้จ่าย",
        "packingProgress": "เตรียมพร้อม",
        "sectionFeatures": "คุณสมบัติ",
        "featureTripInfo": "ข้อมูลการเดินทาง",
        "featureMembers": "สมาชิก",
        "featureWrapped": "สรุปการเดินทาง",
        "featureJournal": "บันทึกการเดินทาง",
        "featureDocuments": "ตั๋วและเอกสาร",
        "featureShare": "แบ่งปันการเดินทาง",
        "sectionData": "การจัดการข้อมูล",
        "dataTripData": "ข้อมูลการเดินทาง",
        "dataBackup": "สำรองข้อมูลทริป",
        "dataExportPdf": "ส่งออกรายงาน PDF",
        "dataExportExcel": "ส่งออกสเปรดชีต Excel",
        "sectionDanger": "เขตอันตราย",
        "actionEndTrip": "สิ้นสุดการเดินทาง",
        "actionRestoreTrip": "กู้คืนการเดินทาง",
        "actionDeleteTrip": "ลบการเดินทางอย่างถาวร",
        "madeBy": "สร้างโดย"
    },
    "id": {
        "workspaceTitle": "Ruang Perjalanan",
        "workspaceDesc": "Sesuaikan info, anggota, dan data untuk perjalanan Anda.",
        "workspaceDescNoTrip": "Kelola aplikasi dan konfigurasi data.",
        "currentTrip": "Perjalanan saat ini",
        "noLocation": "Belum ada lokasi",
        "membersCount": "anggota",
        "eventsCount": "acara",
        "expensesCount": "pengeluaran",
        "packingProgress": "Disiapkan",
        "sectionFeatures": "Fitur",
        "featureTripInfo": "Info Perjalanan",
        "featureMembers": "Anggota",
        "featureWrapped": "Ringkasan Perjalanan",
        "featureJournal": "Jurnal Perjalanan",
        "featureDocuments": "Tiket & Dokumen",
        "featureShare": "Bagikan Perjalanan",
        "sectionData": "Manajemen Data",
        "dataTripData": "Data Perjalanan",
        "dataBackup": "Cadangkan",
        "dataExportPdf": "Ekspor Laporan PDF",
        "dataExportExcel": "Ekspor Spreadsheet Excel",
        "sectionDanger": "Zona Bahaya",
        "actionEndTrip": "Akhiri perjalanan",
        "actionRestoreTrip": "Pulihkan perjalanan",
        "actionDeleteTrip": "Hapus permanen",
        "madeBy": "dibuat oleh"
    }
}

for lang, data_dict in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    if "more" not in data:
        data["more"] = {}
        
    for k, v in data_dict.items():
        data["more"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
