import json
import os

translations = {
    "ko": {
        "edit": "편집",
        "deleteAction": "삭제",
        "privateTag": "개인용",
        "addToList": "목록에 추가",
        "companionSelect": "동행자 선택",
        "proposeEdit": "편집 제안",
        "proposeDelete": "삭제 제안",
        "proposeAdd": "추가 제안",
        "addPrivate": "개인 항목 추가",
        "editPrivate": "개인 항목 편집",
        "deletePrivate": "개인 항목 삭제",
        "emptyPrivate": "개인 준비물 없음",
        "emptyShared": "준비물 없음",
        "proposeDeleteTitle": "이 항목을 삭제 제안하시겠습니까?",
        "deletePrivateTitle": "개인 항목을 삭제하시겠습니까?",
        "deletePrivateDesc": "이 작업은 취소할 수 없습니다.",
        "proposeDeleteDesc": "삭제를 제안합니다. 리더가 승인해야 합니다.",
        "saveChanges": "변경사항 저장"
    },
    "zh": {
        "edit": "编辑",
        "deleteAction": "删除",
        "privateTag": "个人",
        "addToList": "添加到清单",
        "companionSelect": "选择同行者",
        "proposeEdit": "建议编辑",
        "proposeDelete": "建议删除",
        "proposeAdd": "建议添加",
        "addPrivate": "添加个人物品",
        "editPrivate": "编辑个人物品",
        "deletePrivate": "删除个人物品",
        "emptyPrivate": "暂无个人物品",
        "emptyShared": "暂无物品",
        "proposeDeleteTitle": "建议删除此物品？",
        "deletePrivateTitle": "删除个人物品？",
        "deletePrivateDesc": "此操作无法撤销。",
        "proposeDeleteDesc": "您正在发送删除建议，需队长审核。",
        "saveChanges": "保存更改"
    },
    "ja": {
        "edit": "編集",
        "deleteAction": "削除",
        "privateTag": "個人用",
        "addToList": "リストに追加",
        "companionSelect": "同行者を選択",
        "proposeEdit": "編集を提案",
        "proposeDelete": "削除を提案",
        "proposeAdd": "追加を提案",
        "addPrivate": "個人用を追加",
        "editPrivate": "個人用を編集",
        "deletePrivate": "個人用を削除",
        "emptyPrivate": "個人用品なし",
        "emptyShared": "準備品なし",
        "proposeDeleteTitle": "このアイテムの削除を提案しますか？",
        "deletePrivateTitle": "個人用アイテムを削除しますか？",
        "deletePrivateDesc": "この操作は元に戻せません。",
        "proposeDeleteDesc": "削除を提案しています。リーダーの承認が必要です。",
        "saveChanges": "変更を保存"
    },
    "en": {
        "edit": "Edit",
        "deleteAction": "Delete",
        "privateTag": "Personal",
        "addToList": "Add to list",
        "companionSelect": "Select companion",
        "proposeEdit": "Propose edit",
        "proposeDelete": "Propose delete",
        "proposeAdd": "Propose add",
        "addPrivate": "Add personal item",
        "editPrivate": "Edit personal item",
        "deletePrivate": "Delete personal item",
        "emptyPrivate": "No personal items",
        "emptyShared": "No items yet",
        "proposeDeleteTitle": "Propose to delete this item?",
        "deletePrivateTitle": "Delete personal item?",
        "deletePrivateDesc": "This action cannot be undone.",
        "proposeDeleteDesc": "You are proposing to delete this item. The leader will review it.",
        "saveChanges": "Save changes"
    },
    "es": {
        "edit": "Editar",
        "deleteAction": "Eliminar",
        "privateTag": "Personal",
        "addToList": "Añadir a la lista",
        "companionSelect": "Seleccionar acompañante",
        "proposeEdit": "Proponer edición",
        "proposeDelete": "Proponer eliminación",
        "proposeAdd": "Proponer adición",
        "addPrivate": "Añadir artículo personal",
        "editPrivate": "Editar artículo personal",
        "deletePrivate": "Eliminar artículo personal",
        "emptyPrivate": "Sin artículos personales",
        "emptyShared": "Sin artículos",
        "proposeDeleteTitle": "¿Proponer eliminar este artículo?",
        "deletePrivateTitle": "¿Eliminar artículo personal?",
        "deletePrivateDesc": "Esta acción no se puede deshacer.",
        "proposeDeleteDesc": "Estás proponiendo eliminar este artículo. El líder lo revisará.",
        "saveChanges": "Guardar cambios"
    },
    "fr": {
        "edit": "Modifier",
        "deleteAction": "Supprimer",
        "privateTag": "Personnel",
        "addToList": "Ajouter à la liste",
        "companionSelect": "Sélectionner un compagnon",
        "proposeEdit": "Proposer une modification",
        "proposeDelete": "Proposer une suppression",
        "proposeAdd": "Proposer un ajout",
        "addPrivate": "Ajouter un article personnel",
        "editPrivate": "Modifier un article personnel",
        "deletePrivate": "Supprimer un article personnel",
        "emptyPrivate": "Aucun article personnel",
        "emptyShared": "Aucun article",
        "proposeDeleteTitle": "Proposer de supprimer cet article ?",
        "deletePrivateTitle": "Supprimer l'article personnel ?",
        "deletePrivateDesc": "Cette action est irréversible.",
        "proposeDeleteDesc": "Vous proposez de supprimer cet article. Le chef l'examinera.",
        "saveChanges": "Enregistrer"
    },
    "de": {
        "edit": "Bearbeiten",
        "deleteAction": "Löschen",
        "privateTag": "Persönlich",
        "addToList": "Zur Liste hinzufügen",
        "companionSelect": "Begleiter auswählen",
        "proposeEdit": "Änderung vorschlagen",
        "proposeDelete": "Löschen vorschlagen",
        "proposeAdd": "Hinzufügen vorschlagen",
        "addPrivate": "Persönlichen Artikel hinzufügen",
        "editPrivate": "Persönlichen Artikel bearbeiten",
        "deletePrivate": "Persönlichen Artikel löschen",
        "emptyPrivate": "Keine persönlichen Artikel",
        "emptyShared": "Keine Artikel",
        "proposeDeleteTitle": "Löschen dieses Artikels vorschlagen?",
        "deletePrivateTitle": "Persönlichen Artikel löschen?",
        "deletePrivateDesc": "Diese Aktion kann nicht rückgängig gemacht werden.",
        "proposeDeleteDesc": "Sie schlagen vor, diesen Artikel zu löschen. Der Leiter wird es prüfen.",
        "saveChanges": "Änderungen speichern"
    },
    "it": {
        "edit": "Modifica",
        "deleteAction": "Elimina",
        "privateTag": "Personale",
        "addToList": "Aggiungi alla lista",
        "companionSelect": "Seleziona compagno",
        "proposeEdit": "Proponi modifica",
        "proposeDelete": "Proponi eliminazione",
        "proposeAdd": "Proponi aggiunta",
        "addPrivate": "Aggiungi articolo personale",
        "editPrivate": "Modifica articolo personale",
        "deletePrivate": "Elimina articolo personale",
        "emptyPrivate": "Nessun articolo personale",
        "emptyShared": "Nessun articolo",
        "proposeDeleteTitle": "Proporre l'eliminazione di questo articolo?",
        "deletePrivateTitle": "Eliminare l'articolo personale?",
        "deletePrivateDesc": "Questa azione non può essere annullata.",
        "proposeDeleteDesc": "Stai proponendo di eliminare questo articolo. Il leader lo esaminerà.",
        "saveChanges": "Salva modifiche"
    },
    "pt": {
        "edit": "Editar",
        "deleteAction": "Excluir",
        "privateTag": "Pessoal",
        "addToList": "Adicionar à lista",
        "companionSelect": "Selecionar companheiro",
        "proposeEdit": "Propor edição",
        "proposeDelete": "Propor exclusão",
        "proposeAdd": "Propor adição",
        "addPrivate": "Adicionar item pessoal",
        "editPrivate": "Editar item pessoal",
        "deletePrivate": "Excluir item pessoal",
        "emptyPrivate": "Sem itens pessoais",
        "emptyShared": "Sem itens",
        "proposeDeleteTitle": "Propor exclusão deste item?",
        "deletePrivateTitle": "Excluir item pessoal?",
        "deletePrivateDesc": "Esta ação não pode ser desfeita.",
        "proposeDeleteDesc": "Você está propondo excluir este item. O líder revisará.",
        "saveChanges": "Salvar alterações"
    },
    "th": {
        "edit": "แก้ไข",
        "deleteAction": "ลบ",
        "privateTag": "ส่วนตัว",
        "addToList": "เพิ่มลงรายการ",
        "companionSelect": "เลือกผู้ร่วมเดินทาง",
        "proposeEdit": "เสนอแก้ไข",
        "proposeDelete": "เสนอลบ",
        "proposeAdd": "เสนอเพิ่ม",
        "addPrivate": "เพิ่มของใช้ส่วนตัว",
        "editPrivate": "แก้ไขของใช้ส่วนตัว",
        "deletePrivate": "ลบของใช้ส่วนตัว",
        "emptyPrivate": "ไม่มีของใช้ส่วนตัว",
        "emptyShared": "ไม่มีสิ่งของ",
        "proposeDeleteTitle": "เสนอลบรายการนี้?",
        "deletePrivateTitle": "ลบของใช้ส่วนตัว?",
        "deletePrivateDesc": "การดำเนินการนี้ไม่สามารถย้อนกลับได้",
        "proposeDeleteDesc": "คุณกำลังเสนอลบรายการนี้ หัวหน้าจะทำการพิจารณา",
        "saveChanges": "บันทึก"
    },
    "id": {
        "edit": "Edit",
        "deleteAction": "Hapus",
        "privateTag": "Pribadi",
        "addToList": "Tambahkan ke daftar",
        "companionSelect": "Pilih pendamping",
        "proposeEdit": "Usulkan edit",
        "proposeDelete": "Usulkan hapus",
        "proposeAdd": "Usulkan penambahan",
        "addPrivate": "Tambah barang pribadi",
        "editPrivate": "Edit barang pribadi",
        "deletePrivate": "Hapus barang pribadi",
        "emptyPrivate": "Tidak ada barang pribadi",
        "emptyShared": "Tidak ada barang",
        "proposeDeleteTitle": "Usulkan hapus barang ini?",
        "deletePrivateTitle": "Hapus barang pribadi?",
        "deletePrivateDesc": "Tindakan ini tidak dapat dibatalkan.",
        "proposeDeleteDesc": "Anda mengusulkan untuk menghapus barang ini. Pemimpin akan meninjaunya.",
        "saveChanges": "Simpan perubahan"
    },
    "vi": {
        "edit": "Sửa",
        "deleteAction": "Xóa",
        "privateTag": "Cá nhân",
        "addToList": "Thêm vào hành lý",
        "companionSelect": "Chọn người đồng hành",
        "proposeEdit": "Đề xuất sửa",
        "proposeDelete": "Đề xuất xóa",
        "proposeAdd": "Đề xuất thêm",
        "addPrivate": "Thêm chuẩn bị cá nhân",
        "editPrivate": "Sửa chuẩn bị cá nhân",
        "deletePrivate": "Xóa chuẩn bị cá nhân",
        "emptyPrivate": "Chưa có chuẩn bị cá nhân",
        "emptyShared": "Chưa có chuẩn bị nào",
        "proposeDeleteTitle": "Đề xuất xóa mục này?",
        "deletePrivateTitle": "Xóa mục chuẩn bị cá nhân?",
        "deletePrivateDesc": "Hành động này sẽ xóa vĩnh viễn mục chuẩn bị cá nhân của bạn và không thể hoàn tác.",
        "proposeDeleteDesc": "Bạn đang gửi đề xuất xóa mục chuẩn bị này. Chủ chuyến đi sẽ xem và xét duyệt đề xuất của bạn.",
        "saveChanges": "Lưu thay đổi"
    }
}

for lang, data_dict in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    if "packing" not in data:
        data["packing"] = {}
        
    for k, v in data_dict.items():
        data["packing"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
