import json
import os

translations = {
    "vi": {
        "membersTitle": "Thành viên",
        "membersSubtitle": "Quản lý những người cùng tham gia và chia sẻ hành trình.",
        "addMember": "Thêm thành viên",
        "statMembers": "THÀNH VIÊN",
        "statTasks": "PHÂN CÔNG",
        "statPaid": "ĐÃ CHI TRẢ",
        "statReady": "Sẵn sàng",
        "statNeedMore": "Cần thêm",
        "statSplit": "CHIA CHI PHÍ",
        "emptyMembers": "Thêm thành viên để chia chi phí, phân công chuẩn bị và tổng kết chuyến đi rõ ràng hơn.",
        "memberListTitle": "Danh sách thành viên",
        "searchMember": "Tìm kiếm thành viên hoặc vai trò...",
        "noSearchResults": "Không tìm thấy thành viên nào khớp với từ khóa",
        "noMembersYet": "Chưa có thành viên nào trong chuyến đi.",
        
        "roleLeader": "Trưởng nhóm",
        "roleLeaderDesc": "Người tạo chuyến đi và có toàn quyền quản trị tối cao.",
        "roleDriver": "Tài xế",
        "roleDriverDesc": "Phụ trách di chuyển, lái xe và quản lý phương tiện chính.",
        "roleNavigator": "Dẫn đường",
        "roleNavigatorDesc": "Phụ trách dẫn đường, lộ trình di chuyển và bản đồ.",
        "roleCostManager": "Quản lý chi phí",
        "roleCostManagerDesc": "Quản lý quỹ chung, ghi chép và chia tiền chi tiêu.",
        "roleCompanion": "Người đồng hành",
        "roleCompanionDesc": "Xem thông tin chuyến đi và gửi các ý kiến đề xuất.",
        "roleLuggage": "Hành lý",
        "roleLuggageDesc": "Phụ trách quản lý và sắp xếp hành lý chung.",
        
        "permEditTripDirectly": "Sửa lịch trình trực tiếp",
        "permManageCostDirectly": "Quản lý chi phí trực tiếp",
        "permSuggestCost": "Đề xuất thêm chi phí",
        "permSuggestTrip": "Đề xuất sửa lịch trình",
        
        "rolesHelpTitle": "Thông tin các vai trò",
        "rolesHelpSubtitle": "Mỗi thành viên có trách nhiệm khác nhau để cùng vận hành chuyến đi",
        
        "formAddTitle": "Thêm thành viên",
        "formEditTitle": "Thông tin thành viên",
        "nameLabel": "Tên thành viên *",
        "namePlaceholder": "VD: Tùng",
        "nameRequired": "Vui lòng nhập tên thành viên.",
        "genderLabel": "Giới tính (để tạo ảnh đại diện ngẫu nhiên)",
        "genderMale": "Nam",
        "genderFemale": "Nữ",
        "genderOther": "Khác",
        "groupLabel": "Nhóm / Gia đình (Tuỳ chọn)",
        "groupPlaceholder": "VD: Gia đình A, Nhóm bạn B...",
        "phoneLabel": "Điện thoại (Tuỳ chọn)",
        "phonePlaceholder": "VD: 0987654321",
        "phoneHelp": "Dùng để liên hệ nhanh trong chuyến đi khi cần.",
        "roleLabel": "Vai trò trong chuyến đi",
        "viewRoles": "Xem vai trò",
        "noteLabel": "Ghi chú (Tuỳ chọn)",
        "notePlaceholder": "Ghi chú thêm về thành viên này...",
        "btnCancel": "Hủy",
        "btnSave": "Lưu thay đổi",
        "btnAdd": "Thêm thành viên",
        "btnSuggestAdd": "Gửi đề xuất thêm",
        "btnSuggestRole": "Gửi đề xuất đổi vai trò",
        
        "groupPrefix": "Nhóm: ",
        "phonePrefix": "SĐT: ",
        "taskCount": "việc",
        "paidPrefix": "Đã chi: ",
        "paidTimes": "lần",
        
        "suggestNew": "Đề xuất mới",
        "suggestChangeRole": "Đề xuất đổi vai trò",
        "suggestDelete": "Đề xuất xóa",
        "options": "Tùy chọn đề xuất",
        "changeRole": "Đổi vai trò",
        
        "suggestDeleteTitle": "Đề xuất xóa thành viên?",
        "suggestDeleteDesc": "Bạn đang gửi đề xuất xóa thành viên này. Chủ chuyến đi sẽ xem và xét duyệt đề xuất.",
        "suggestDeleteBtn": "Đề xuất xóa",
        
        "deleteTitle": "Xóa thành viên?",
        "deleteDesc": "Bạn có chắc chắn muốn xóa thành viên này khỏi chuyến đi? Hành động này không thể hoàn tác.",
        "deleteBtn": "Xóa thành viên",
        
        "suggestRoleTitle": "Đề xuất đổi vai trò",
        "memberLabel": "Thành viên: ",
        "chooseNewRole": "Chọn vai trò mới"
    },
    "en": {
        "membersTitle": "Members",
        "membersSubtitle": "Manage participants and share the journey.",
        "addMember": "Add member",
        "statMembers": "MEMBERS",
        "statTasks": "TASKS",
        "statPaid": "PAID",
        "statReady": "Ready",
        "statNeedMore": "Need more",
        "statSplit": "SPLIT COST",
        "emptyMembers": "Add members to split costs, assign tasks, and summarize the trip more clearly.",
        "memberListTitle": "Member List",
        "searchMember": "Search members or roles...",
        "noSearchResults": "No members found matching",
        "noMembersYet": "No members in the trip yet.",
        
        "roleLeader": "Leader",
        "roleLeaderDesc": "Creator of the trip with full administrative privileges.",
        "roleDriver": "Driver",
        "roleDriverDesc": "In charge of transportation and driving.",
        "roleNavigator": "Navigator",
        "roleNavigatorDesc": "In charge of directions and maps.",
        "roleCostManager": "Cost Manager",
        "roleCostManagerDesc": "Manages the shared fund, records, and splits expenses.",
        "roleCompanion": "Companion",
        "roleCompanionDesc": "Views trip information and sends suggestions.",
        "roleLuggage": "Luggage",
        "roleLuggageDesc": "In charge of managing shared luggage.",
        
        "permEditTripDirectly": "Edit itinerary directly",
        "permManageCostDirectly": "Manage costs directly",
        "permSuggestCost": "Suggest adding expenses",
        "permSuggestTrip": "Suggest editing itinerary",
        
        "rolesHelpTitle": "Role Information",
        "rolesHelpSubtitle": "Each member has different responsibilities to run the trip",
        
        "formAddTitle": "Add member",
        "formEditTitle": "Member information",
        "nameLabel": "Member name *",
        "namePlaceholder": "e.g., John",
        "nameRequired": "Please enter a member name.",
        "genderLabel": "Gender (for random avatar)",
        "genderMale": "Male",
        "genderFemale": "Female",
        "genderOther": "Other",
        "groupLabel": "Group / Family (Optional)",
        "groupPlaceholder": "e.g., Family A, Friends B...",
        "phoneLabel": "Phone (Optional)",
        "phonePlaceholder": "e.g., 0987654321",
        "phoneHelp": "Used for quick contact during the trip.",
        "roleLabel": "Trip role",
        "viewRoles": "View roles",
        "noteLabel": "Notes (Optional)",
        "notePlaceholder": "Additional notes about this member...",
        "btnCancel": "Cancel",
        "btnSave": "Save changes",
        "btnAdd": "Add member",
        "btnSuggestAdd": "Send add request",
        "btnSuggestRole": "Send role change request",
        
        "groupPrefix": "Group: ",
        "phonePrefix": "Phone: ",
        "taskCount": "tasks",
        "paidPrefix": "Paid: ",
        "paidTimes": "times",
        
        "suggestNew": "New request",
        "suggestChangeRole": "Role change request",
        "suggestDelete": "Delete request",
        "options": "Request options",
        "changeRole": "Change role",
        
        "suggestDeleteTitle": "Suggest deleting member?",
        "suggestDeleteDesc": "You are suggesting to delete this member. The trip owner will review this request.",
        "suggestDeleteBtn": "Suggest delete",
        
        "deleteTitle": "Delete member?",
        "deleteDesc": "Are you sure you want to remove this member from the trip? This action cannot be undone.",
        "deleteBtn": "Delete member",
        
        "suggestRoleTitle": "Suggest role change",
        "memberLabel": "Member: ",
        "chooseNewRole": "Choose new role"
    },
    "ja": {
        "membersTitle": "メンバー",
        "membersSubtitle": "参加者を管理し、旅を共有します。",
        "addMember": "メンバーを追加",
        "statMembers": "メンバー",
        "statTasks": "タスク",
        "statPaid": "支払い済み",
        "statReady": "準備完了",
        "statNeedMore": "さらに必要",
        "statSplit": "費用分割",
        "emptyMembers": "メンバーを追加して、費用の分割、タスクの割り当て、旅のまとめを明確にします。",
        "memberListTitle": "メンバーリスト",
        "searchMember": "メンバーや役割を検索...",
        "noSearchResults": "一致するメンバーが見つかりません",
        "noMembersYet": "まだメンバーがいません。",
        
        "roleLeader": "リーダー",
        "roleLeaderDesc": "旅行の作成者であり、完全な管理者権限を持ちます。",
        "roleDriver": "運転手",
        "roleDriverDesc": "移動と運転を担当します。",
        "roleNavigator": "ナビゲーター",
        "roleNavigatorDesc": "道案内と地図を担当します。",
        "roleCostManager": "費用管理者",
        "roleCostManagerDesc": "共有資金を管理し、記録し、費用を分割します。",
        "roleCompanion": "同行者",
        "roleCompanionDesc": "旅行情報を閲覧し、提案を送信します。",
        "roleLuggage": "荷物",
        "roleLuggageDesc": "共有の荷物を管理します。",
        
        "permEditTripDirectly": "旅程を直接編集",
        "permManageCostDirectly": "費用を直接管理",
        "permSuggestCost": "費用の追加を提案",
        "permSuggestTrip": "旅程の編集を提案",
        
        "rolesHelpTitle": "役割情報",
        "rolesHelpSubtitle": "各メンバーは旅行を運営するための異なる責任を持ちます",
        
        "formAddTitle": "メンバーを追加",
        "formEditTitle": "メンバー情報",
        "nameLabel": "メンバー名 *",
        "namePlaceholder": "例：ジョン",
        "nameRequired": "メンバー名を入力してください。",
        "genderLabel": "性別（ランダムなアバター用）",
        "genderMale": "男性",
        "genderFemale": "女性",
        "genderOther": "その他",
        "groupLabel": "グループ/家族（任意）",
        "groupPlaceholder": "例：家族A、友達B...",
        "phoneLabel": "電話番号（任意）",
        "phonePlaceholder": "例：0987654321",
        "phoneHelp": "旅行中の迅速な連絡に使用されます。",
        "roleLabel": "旅行での役割",
        "viewRoles": "役割を表示",
        "noteLabel": "メモ（任意）",
        "notePlaceholder": "このメンバーに関する追加メモ...",
        "btnCancel": "キャンセル",
        "btnSave": "変更を保存",
        "btnAdd": "メンバーを追加",
        "btnSuggestAdd": "追加リクエストを送信",
        "btnSuggestRole": "役割変更リクエストを送信",
        
        "groupPrefix": "グループ: ",
        "phonePrefix": "電話: ",
        "taskCount": "タスク",
        "paidPrefix": "支払い済み: ",
        "paidTimes": "回",
        
        "suggestNew": "新規リクエスト",
        "suggestChangeRole": "役割変更リクエスト",
        "suggestDelete": "削除リクエスト",
        "options": "リクエストオプション",
        "changeRole": "役割を変更",
        
        "suggestDeleteTitle": "メンバーの削除を提案しますか？",
        "suggestDeleteDesc": "このメンバーの削除を提案しています。旅行の所有者がこのリクエストを確認します。",
        "suggestDeleteBtn": "削除を提案",
        
        "deleteTitle": "メンバーを削除しますか？",
        "deleteDesc": "このメンバーを旅行から削除してもよろしいですか？この操作は元に戻せません。",
        "deleteBtn": "メンバーを削除",
        
        "suggestRoleTitle": "役割の変更を提案",
        "memberLabel": "メンバー: ",
        "chooseNewRole": "新しい役割を選択"
    },
    "ko": {
        "membersTitle": "멤버",
        "membersSubtitle": "참가자를 관리하고 여행을 공유하세요.",
        "addMember": "멤버 추가",
        "statMembers": "멤버",
        "statTasks": "할 일",
        "statPaid": "결제됨",
        "statReady": "준비됨",
        "statNeedMore": "더 필요함",
        "statSplit": "비용 나누기",
        "emptyMembers": "비용을 나누고, 할 일을 할당하고, 여행을 더 명확하게 요약하려면 멤버를 추가하세요.",
        "memberListTitle": "멤버 목록",
        "searchMember": "멤버 또는 역할 검색...",
        "noSearchResults": "일치하는 멤버가 없습니다",
        "noMembersYet": "아직 멤버가 없습니다.",
        
        "roleLeader": "리더",
        "roleLeaderDesc": "전체 관리 권한을 가진 여행의 생성자입니다.",
        "roleDriver": "운전기사",
        "roleDriverDesc": "교통 및 운전을 담당합니다.",
        "roleNavigator": "내비게이터",
        "roleNavigatorDesc": "길 안내와 지도를 담당합니다.",
        "roleCostManager": "비용 관리자",
        "roleCostManagerDesc": "공동 자금을 관리하고, 기록하며, 비용을 나눕니다.",
        "roleCompanion": "동행자",
        "roleCompanionDesc": "여행 정보를 보고 제안을 보냅니다.",
        "roleLuggage": "수하물",
        "roleLuggageDesc": "공동 수하물을 관리합니다.",
        
        "permEditTripDirectly": "일정 직접 편집",
        "permManageCostDirectly": "비용 직접 관리",
        "permSuggestCost": "비용 추가 제안",
        "permSuggestTrip": "일정 편집 제안",
        
        "rolesHelpTitle": "역할 정보",
        "rolesHelpSubtitle": "각 멤버는 여행을 운영하기 위해 다른 책임을 가집니다.",
        
        "formAddTitle": "멤버 추가",
        "formEditTitle": "멤버 정보",
        "nameLabel": "멤버 이름 *",
        "namePlaceholder": "예: 존",
        "nameRequired": "멤버 이름을 입력하세요.",
        "genderLabel": "성별 (무작위 아바타 생성용)",
        "genderMale": "남성",
        "genderFemale": "여성",
        "genderOther": "기타",
        "groupLabel": "그룹 / 가족 (선택)",
        "groupPlaceholder": "예: 가족 A, 친구 B...",
        "phoneLabel": "전화번호 (선택)",
        "phonePlaceholder": "예: 0987654321",
        "phoneHelp": "여행 중 빠른 연락을 위해 사용됩니다.",
        "roleLabel": "여행 역할",
        "viewRoles": "역할 보기",
        "noteLabel": "메모 (선택)",
        "notePlaceholder": "이 멤버에 대한 추가 메모...",
        "btnCancel": "취소",
        "btnSave": "변경 사항 저장",
        "btnAdd": "멤버 추가",
        "btnSuggestAdd": "추가 요청 보내기",
        "btnSuggestRole": "역할 변경 요청 보내기",
        
        "groupPrefix": "그룹: ",
        "phonePrefix": "전화: ",
        "taskCount": "개",
        "paidPrefix": "결제 금액: ",
        "paidTimes": "회",
        
        "suggestNew": "새 요청",
        "suggestChangeRole": "역할 변경 요청",
        "suggestDelete": "삭제 요청",
        "options": "요청 옵션",
        "changeRole": "역할 변경",
        
        "suggestDeleteTitle": "멤버 삭제를 제안하시겠습니까?",
        "suggestDeleteDesc": "이 멤버의 삭제를 제안하고 있습니다. 여행 소유자가 이 요청을 검토합니다.",
        "suggestDeleteBtn": "삭제 제안",
        
        "deleteTitle": "멤버 삭제?",
        "deleteDesc": "이 멤버를 여행에서 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "deleteBtn": "멤버 삭제",
        
        "suggestRoleTitle": "역할 변경 제안",
        "memberLabel": "멤버: ",
        "chooseNewRole": "새 역할 선택"
    },
    "zh": {
        "membersTitle": "成员",
        "membersSubtitle": "管理参与者并分享旅程。",
        "addMember": "添加成员",
        "statMembers": "成员",
        "statTasks": "任务",
        "statPaid": "已支付",
        "statReady": "准备就绪",
        "statNeedMore": "还需要",
        "statSplit": "分摊费用",
        "emptyMembers": "添加成员以分摊费用、分配任务并更清晰地总结行程。",
        "memberListTitle": "成员列表",
        "searchMember": "搜索成员或角色...",
        "noSearchResults": "未找到匹配的成员",
        "noMembersYet": "行程中还没有成员。",
        
        "roleLeader": "领队",
        "roleLeaderDesc": "行程的创建者，拥有完全的管理权限。",
        "roleDriver": "司机",
        "roleDriverDesc": "负责交通和驾驶。",
        "roleNavigator": "领航员",
        "roleNavigatorDesc": "负责指路和地图。",
        "roleCostManager": "财务主管",
        "roleCostManagerDesc": "管理共同基金、记录并分摊费用。",
        "roleCompanion": "同行者",
        "roleCompanionDesc": "查看行程信息并发送建议。",
        "roleLuggage": "行李",
        "roleLuggageDesc": "负责管理共享行李。",
        
        "permEditTripDirectly": "直接编辑行程",
        "permManageCostDirectly": "直接管理费用",
        "permSuggestCost": "建议添加费用",
        "permSuggestTrip": "建议编辑行程",
        
        "rolesHelpTitle": "角色信息",
        "rolesHelpSubtitle": "每个成员在运营行程中负有不同的责任",
        
        "formAddTitle": "添加成员",
        "formEditTitle": "成员信息",
        "nameLabel": "成员名称 *",
        "namePlaceholder": "例如：约翰",
        "nameRequired": "请输入成员名称。",
        "genderLabel": "性别（用于随机头像）",
        "genderMale": "男",
        "genderFemale": "女",
        "genderOther": "其他",
        "groupLabel": "群组 / 家庭（可选）",
        "groupPlaceholder": "例如：家庭 A，朋友 B...",
        "phoneLabel": "电话（可选）",
        "phonePlaceholder": "例如：0987654321",
        "phoneHelp": "用于行程中需要时的快速联系。",
        "roleLabel": "行程角色",
        "viewRoles": "查看角色",
        "noteLabel": "备注（可选）",
        "notePlaceholder": "关于此成员的附加备注...",
        "btnCancel": "取消",
        "btnSave": "保存更改",
        "btnAdd": "添加成员",
        "btnSuggestAdd": "发送添加请求",
        "btnSuggestRole": "发送角色更改请求",
        
        "groupPrefix": "群组: ",
        "phonePrefix": "电话: ",
        "taskCount": "项",
        "paidPrefix": "已付: ",
        "paidTimes": "次",
        
        "suggestNew": "新请求",
        "suggestChangeRole": "更改角色请求",
        "suggestDelete": "删除请求",
        "options": "请求选项",
        "changeRole": "更改角色",
        
        "suggestDeleteTitle": "建议删除成员？",
        "suggestDeleteDesc": "您正在建议删除此成员。行程所有者将审核此请求。",
        "suggestDeleteBtn": "建议删除",
        
        "deleteTitle": "删除成员？",
        "deleteDesc": "您确定要从行程中删除此成员吗？此操作无法撤消。",
        "deleteBtn": "删除成员",
        
        "suggestRoleTitle": "建议更改角色",
        "memberLabel": "成员: ",
        "chooseNewRole": "选择新角色"
    },
    "th": {
        "membersTitle": "สมาชิก",
        "membersSubtitle": "จัดการผู้เข้าร่วมและแบ่งปันการเดินทาง",
        "addMember": "เพิ่มสมาชิก",
        "statMembers": "สมาชิก",
        "statTasks": "งาน",
        "statPaid": "จ่ายแล้ว",
        "statReady": "พร้อม",
        "statNeedMore": "ต้องการเพิ่ม",
        "statSplit": "แบ่งค่าใช้จ่าย",
        "emptyMembers": "เพิ่มสมาชิกเพื่อแบ่งค่าใช้จ่าย มอบหมายงาน และสรุปการเดินทางให้ชัดเจนยิ่งขึ้น",
        "memberListTitle": "รายชื่อสมาชิก",
        "searchMember": "ค้นหาสมาชิกหรือบทบาท...",
        "noSearchResults": "ไม่พบสมาชิกที่ตรงกัน",
        "noMembersYet": "ยังไม่มีสมาชิกในการเดินทาง",
        
        "roleLeader": "หัวหน้า",
        "roleLeaderDesc": "ผู้สร้างการเดินทางที่มีสิทธิ์ผู้ดูแลระบบเต็มรูปแบบ",
        "roleDriver": "คนขับรถ",
        "roleDriverDesc": "รับผิดชอบด้านการขนส่งและการขับขี่",
        "roleNavigator": "ผู้นำทาง",
        "roleNavigatorDesc": "รับผิดชอบเรื่องทิศทางและแผนที่",
        "roleCostManager": "ผู้จัดการค่าใช้จ่าย",
        "roleCostManagerDesc": "จัดการกองทุนรวม บันทึกและแบ่งค่าใช้จ่าย",
        "roleCompanion": "ผู้ร่วมเดินทาง",
        "roleCompanionDesc": "ดูข้อมูลการเดินทางและส่งข้อเสนอแนะ",
        "roleLuggage": "สัมภาระ",
        "roleLuggageDesc": "รับผิดชอบจัดการสัมภาระส่วนรวม",
        
        "permEditTripDirectly": "แก้ไขแผนการเดินทางโดยตรง",
        "permManageCostDirectly": "จัดการค่าใช้จ่ายโดยตรง",
        "permSuggestCost": "เสนอแนะเพิ่มค่าใช้จ่าย",
        "permSuggestTrip": "เสนอแนะแก้ไขแผนการเดินทาง",
        
        "rolesHelpTitle": "ข้อมูลบทบาท",
        "rolesHelpSubtitle": "สมาชิกแต่ละคนมีความรับผิดชอบที่แตกต่างกันในการดำเนินการเดินทาง",
        
        "formAddTitle": "เพิ่มสมาชิก",
        "formEditTitle": "ข้อมูลสมาชิก",
        "nameLabel": "ชื่อสมาชิก *",
        "namePlaceholder": "เช่น จอห์น",
        "nameRequired": "กรุณาป้อนชื่อสมาชิก",
        "genderLabel": "เพศ (สำหรับอวตารสุ่ม)",
        "genderMale": "ชาย",
        "genderFemale": "หญิง",
        "genderOther": "อื่นๆ",
        "groupLabel": "กลุ่ม / ครอบครัว (ไม่บังคับ)",
        "groupPlaceholder": "เช่น ครอบครัว A, เพื่อน B...",
        "phoneLabel": "โทรศัพท์ (ไม่บังคับ)",
        "phonePlaceholder": "เช่น 0987654321",
        "phoneHelp": "ใช้สำหรับติดต่อด่วนระหว่างการเดินทางเมื่อจำเป็น",
        "roleLabel": "บทบาทในการเดินทาง",
        "viewRoles": "ดูบทบาท",
        "noteLabel": "หมายเหตุ (ไม่บังคับ)",
        "notePlaceholder": "หมายเหตุเพิ่มเติมเกี่ยวกับสมาชิกนี้...",
        "btnCancel": "ยกเลิก",
        "btnSave": "บันทึกการเปลี่ยนแปลง",
        "btnAdd": "เพิ่มสมาชิก",
        "btnSuggestAdd": "ส่งคำขอเพิ่ม",
        "btnSuggestRole": "ส่งคำขอเปลี่ยนบทบาท",
        
        "groupPrefix": "กลุ่ม: ",
        "phonePrefix": "โทร: ",
        "taskCount": "งาน",
        "paidPrefix": "จ่าย: ",
        "paidTimes": "ครั้ง",
        
        "suggestNew": "คำขอใหม่",
        "suggestChangeRole": "คำขอเปลี่ยนบทบาท",
        "suggestDelete": "คำขอลบ",
        "options": "ตัวเลือกคำขอ",
        "changeRole": "เปลี่ยนบทบาท",
        
        "suggestDeleteTitle": "เสนอแนะให้ลบสมาชิก?",
        "suggestDeleteDesc": "คุณกำลังเสนอแนะให้ลบสมาชิกนี้ เจ้าของการเดินทางจะตรวจสอบคำขอนี้",
        "suggestDeleteBtn": "เสนอแนะให้ลบ",
        
        "deleteTitle": "ลบสมาชิก?",
        "deleteDesc": "คุณแน่ใจหรือไม่ว่าต้องการลบสมาชิกนี้ออกจากการเดินทาง? การกระทำนี้ไม่สามารถยกเลิกได้",
        "deleteBtn": "ลบสมาชิก",
        
        "suggestRoleTitle": "เสนอแนะเปลี่ยนบทบาท",
        "memberLabel": "สมาชิก: ",
        "chooseNewRole": "เลือกบทบาทใหม่"
    },
    "fr": {
        "membersTitle": "Membres",
        "membersSubtitle": "Gérez les participants et partagez le voyage.",
        "addMember": "Ajouter un membre",
        "statMembers": "MEMBRES",
        "statTasks": "TÂCHES",
        "statPaid": "PAYÉ",
        "statReady": "Prêt",
        "statNeedMore": "Besoin de plus",
        "statSplit": "PARTAGER",
        "emptyMembers": "Ajoutez des membres pour partager les coûts, assigner des tâches et mieux organiser le voyage.",
        "memberListTitle": "Liste des membres",
        "searchMember": "Rechercher des membres ou rôles...",
        "noSearchResults": "Aucun membre trouvé",
        "noMembersYet": "Aucun membre dans ce voyage pour l'instant.",
        
        "roleLeader": "Leader",
        "roleLeaderDesc": "Créateur du voyage avec tous les droits d'administration.",
        "roleDriver": "Chauffeur",
        "roleDriverDesc": "En charge du transport et de la conduite.",
        "roleNavigator": "Navigateur",
        "roleNavigatorDesc": "En charge de l'itinéraire et des cartes.",
        "roleCostManager": "Trésorier",
        "roleCostManagerDesc": "Gère le fonds commun et partage les dépenses.",
        "roleCompanion": "Compagnon",
        "roleCompanionDesc": "Consulte les informations et envoie des suggestions.",
        "roleLuggage": "Bagages",
        "roleLuggageDesc": "En charge de la gestion des bagages communs.",
        
        "permEditTripDirectly": "Modifier l'itinéraire",
        "permManageCostDirectly": "Gérer les coûts",
        "permSuggestCost": "Suggérer des dépenses",
        "permSuggestTrip": "Suggérer des modifications",
        
        "rolesHelpTitle": "Informations sur les rôles",
        "rolesHelpSubtitle": "Chaque membre a des responsabilités différentes",
        
        "formAddTitle": "Ajouter un membre",
        "formEditTitle": "Informations du membre",
        "nameLabel": "Nom du membre *",
        "namePlaceholder": "Ex: Jean",
        "nameRequired": "Veuillez entrer un nom.",
        "genderLabel": "Genre (pour l'avatar)",
        "genderMale": "Homme",
        "genderFemale": "Femme",
        "genderOther": "Autre",
        "groupLabel": "Groupe / Famille (Optionnel)",
        "groupPlaceholder": "Ex: Famille A, Amis B...",
        "phoneLabel": "Téléphone (Optionnel)",
        "phonePlaceholder": "Ex: 0987654321",
        "phoneHelp": "Pour un contact rapide pendant le voyage.",
        "roleLabel": "Rôle dans le voyage",
        "viewRoles": "Voir les rôles",
        "noteLabel": "Notes (Optionnel)",
        "notePlaceholder": "Notes supplémentaires...",
        "btnCancel": "Annuler",
        "btnSave": "Enregistrer",
        "btnAdd": "Ajouter le membre",
        "btnSuggestAdd": "Suggérer l'ajout",
        "btnSuggestRole": "Suggérer le rôle",
        
        "groupPrefix": "Groupe: ",
        "phonePrefix": "Tél: ",
        "taskCount": "tâches",
        "paidPrefix": "Payé: ",
        "paidTimes": "fois",
        
        "suggestNew": "Nouvelle suggestion",
        "suggestChangeRole": "Suggestion de rôle",
        "suggestDelete": "Suggestion de suppr.",
        "options": "Options",
        "changeRole": "Changer le rôle",
        
        "suggestDeleteTitle": "Suggérer la suppression ?",
        "suggestDeleteDesc": "Le créateur du voyage examinera cette demande.",
        "suggestDeleteBtn": "Suggérer la suppression",
        
        "deleteTitle": "Supprimer le membre ?",
        "deleteDesc": "Êtes-vous sûr de vouloir supprimer ce membre ? Cette action est irréversible.",
        "deleteBtn": "Supprimer le membre",
        
        "suggestRoleTitle": "Suggérer un rôle",
        "memberLabel": "Membre: ",
        "chooseNewRole": "Choisir un nouveau rôle"
    },
    "es": {
        "membersTitle": "Miembros",
        "membersSubtitle": "Gestiona los participantes y comparte el viaje.",
        "addMember": "Añadir miembro",
        "statMembers": "MIEMBROS",
        "statTasks": "TAREAS",
        "statPaid": "PAGADO",
        "statReady": "Listo",
        "statNeedMore": "Faltan",
        "statSplit": "DIVIDIR",
        "emptyMembers": "Añade miembros para dividir gastos y asignar tareas.",
        "memberListTitle": "Lista de miembros",
        "searchMember": "Buscar miembros o roles...",
        "noSearchResults": "No se encontraron miembros",
        "noMembersYet": "Aún no hay miembros en el viaje.",
        
        "roleLeader": "Líder",
        "roleLeaderDesc": "Creador del viaje con privilegios totales.",
        "roleDriver": "Conductor",
        "roleDriverDesc": "Encargado del transporte y la conducción.",
        "roleNavigator": "Navegador",
        "roleNavigatorDesc": "Encargado de la ruta y los mapas.",
        "roleCostManager": "Tesorero",
        "roleCostManagerDesc": "Gestiona el fondo común y divide los gastos.",
        "roleCompanion": "Acompañante",
        "roleCompanionDesc": "Ve la información y envía sugerencias.",
        "roleLuggage": "Equipaje",
        "roleLuggageDesc": "Encargado de gestionar el equipaje común.",
        
        "permEditTripDirectly": "Editar itinerario",
        "permManageCostDirectly": "Gestionar costes",
        "permSuggestCost": "Sugerir gastos",
        "permSuggestTrip": "Sugerir cambios",
        
        "rolesHelpTitle": "Información de roles",
        "rolesHelpSubtitle": "Cada miembro tiene diferentes responsabilidades",
        
        "formAddTitle": "Añadir miembro",
        "formEditTitle": "Información del miembro",
        "nameLabel": "Nombre del miembro *",
        "namePlaceholder": "Ej: Juan",
        "nameRequired": "Introduce un nombre.",
        "genderLabel": "Género (para el avatar)",
        "genderMale": "Hombre",
        "genderFemale": "Mujer",
        "genderOther": "Otro",
        "groupLabel": "Grupo / Familia (Opcional)",
        "groupPlaceholder": "Ej: Familia A...",
        "phoneLabel": "Teléfono (Opcional)",
        "phonePlaceholder": "Ej: 0987654321",
        "phoneHelp": "Para contacto rápido durante el viaje.",
        "roleLabel": "Rol en el viaje",
        "viewRoles": "Ver roles",
        "noteLabel": "Notas (Opcional)",
        "notePlaceholder": "Notas adicionales...",
        "btnCancel": "Cancelar",
        "btnSave": "Guardar cambios",
        "btnAdd": "Añadir miembro",
        "btnSuggestAdd": "Sugerir miembro",
        "btnSuggestRole": "Sugerir rol",
        
        "groupPrefix": "Grupo: ",
        "phonePrefix": "Tel: ",
        "taskCount": "tareas",
        "paidPrefix": "Pagado: ",
        "paidTimes": "veces",
        
        "suggestNew": "Nueva sugerencia",
        "suggestChangeRole": "Sugerencia de rol",
        "suggestDelete": "Sugerencia de elim.",
        "options": "Opciones",
        "changeRole": "Cambiar rol",
        
        "suggestDeleteTitle": "¿Sugerir eliminación?",
        "suggestDeleteDesc": "El creador del viaje revisará esta solicitud.",
        "suggestDeleteBtn": "Sugerir eliminar",
        
        "deleteTitle": "¿Eliminar miembro?",
        "deleteDesc": "¿Estás seguro de que deseas eliminar este miembro? Esta acción no se puede deshacer.",
        "deleteBtn": "Eliminar miembro",
        
        "suggestRoleTitle": "Sugerir cambio de rol",
        "memberLabel": "Miembro: ",
        "chooseNewRole": "Elegir nuevo rol"
    },
    "de": {
        "membersTitle": "Mitglieder",
        "membersSubtitle": "Teilnehmer verwalten und die Reise teilen.",
        "addMember": "Mitglied hinzufügen",
        "statMembers": "MITGLIEDER",
        "statTasks": "AUFGABEN",
        "statPaid": "BEZAHLT",
        "statReady": "Bereit",
        "statNeedMore": "Fehlt noch",
        "statSplit": "AUFTEILEN",
        "emptyMembers": "Fügen Sie Mitglieder hinzu, um Kosten zu teilen und Aufgaben zuzuweisen.",
        "memberListTitle": "Mitgliederliste",
        "searchMember": "Mitglieder oder Rollen suchen...",
        "noSearchResults": "Keine passenden Mitglieder gefunden",
        "noMembersYet": "Noch keine Mitglieder in der Reise.",
        
        "roleLeader": "Leiter",
        "roleLeaderDesc": "Ersteller der Reise mit vollen Rechten.",
        "roleDriver": "Fahrer",
        "roleDriverDesc": "Verantwortlich für Transport und Fahren.",
        "roleNavigator": "Navigator",
        "roleNavigatorDesc": "Verantwortlich für Routen und Karten.",
        "roleCostManager": "Schatzmeister",
        "roleCostManagerDesc": "Verwaltet die gemeinsame Kasse und teilt Ausgaben.",
        "roleCompanion": "Begleiter",
        "roleCompanionDesc": "Sieht Reiseinfos und sendet Vorschläge.",
        "roleLuggage": "Gepäck",
        "roleLuggageDesc": "Verantwortlich für das gemeinsame Gepäck.",
        
        "permEditTripDirectly": "Reiseroute bearbeiten",
        "permManageCostDirectly": "Kosten verwalten",
        "permSuggestCost": "Ausgaben vorschlagen",
        "permSuggestTrip": "Änderungen vorschlagen",
        
        "rolesHelpTitle": "Rolleninformationen",
        "rolesHelpSubtitle": "Jedes Mitglied hat unterschiedliche Aufgaben",
        
        "formAddTitle": "Mitglied hinzufügen",
        "formEditTitle": "Mitgliedsinformationen",
        "nameLabel": "Name des Mitglieds *",
        "namePlaceholder": "z.B. Johann",
        "nameRequired": "Bitte Namen eingeben.",
        "genderLabel": "Geschlecht (für Avatar)",
        "genderMale": "Männlich",
        "genderFemale": "Weiblich",
        "genderOther": "Divers",
        "groupLabel": "Gruppe / Familie (Optional)",
        "groupPlaceholder": "z.B. Familie A...",
        "phoneLabel": "Telefon (Optional)",
        "phonePlaceholder": "z.B. 0987654321",
        "phoneHelp": "Für schnellen Kontakt während der Reise.",
        "roleLabel": "Rolle auf der Reise",
        "viewRoles": "Rollen ansehen",
        "noteLabel": "Notizen (Optional)",
        "notePlaceholder": "Zusätzliche Notizen...",
        "btnCancel": "Abbrechen",
        "btnSave": "Speichern",
        "btnAdd": "Mitglied hinzufügen",
        "btnSuggestAdd": "Mitglied vorschlagen",
        "btnSuggestRole": "Rolle vorschlagen",
        
        "groupPrefix": "Gruppe: ",
        "phonePrefix": "Tel: ",
        "taskCount": "Aufgaben",
        "paidPrefix": "Bezahlt: ",
        "paidTimes": "mal",
        
        "suggestNew": "Neuer Vorschlag",
        "suggestChangeRole": "Rollenvorschlag",
        "suggestDelete": "Löschvorschlag",
        "options": "Optionen",
        "changeRole": "Rolle ändern",
        
        "suggestDeleteTitle": "Löschen vorschlagen?",
        "suggestDeleteDesc": "Der Reiseersteller wird diese Anfrage prüfen.",
        "suggestDeleteBtn": "Löschen vorschlagen",
        
        "deleteTitle": "Mitglied löschen?",
        "deleteDesc": "Möchten Sie dieses Mitglied wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
        "deleteBtn": "Mitglied löschen",
        
        "suggestRoleTitle": "Rollenwechsel vorschlagen",
        "memberLabel": "Mitglied: ",
        "chooseNewRole": "Neue Rolle wählen"
    },
    "it": {
        "membersTitle": "Membri",
        "membersSubtitle": "Gestisci i partecipanti e condividi il viaggio.",
        "addMember": "Aggiungi membro",
        "statMembers": "MEMBRI",
        "statTasks": "COMPITI",
        "statPaid": "PAGATO",
        "statReady": "Pronto",
        "statNeedMore": "Più membri",
        "statSplit": "DIVIDERE",
        "emptyMembers": "Aggiungi membri per dividere i costi e assegnare compiti.",
        "memberListTitle": "Elenco dei membri",
        "searchMember": "Cerca membri o ruoli...",
        "noSearchResults": "Nessun membro trovato",
        "noMembersYet": "Ancora nessun membro nel viaggio.",
        
        "roleLeader": "Leader",
        "roleLeaderDesc": "Creatore del viaggio con pieni privilegi.",
        "roleDriver": "Autista",
        "roleDriverDesc": "Incaricato del trasporto e della guida.",
        "roleNavigator": "Navigatore",
        "roleNavigatorDesc": "Incaricato del percorso e delle mappe.",
        "roleCostManager": "Tesoriere",
        "roleCostManagerDesc": "Gestisce il fondo comune e divide le spese.",
        "roleCompanion": "Accompagnatore",
        "roleCompanionDesc": "Vede le info e invia suggerimenti.",
        "roleLuggage": "Bagagli",
        "roleLuggageDesc": "Gestisce i bagagli comuni.",
        
        "permEditTripDirectly": "Modifica itinerario",
        "permManageCostDirectly": "Gestisci costi",
        "permSuggestCost": "Suggerisci spese",
        "permSuggestTrip": "Suggerisci modifiche",
        
        "rolesHelpTitle": "Informazioni sui ruoli",
        "rolesHelpSubtitle": "Ogni membro ha responsabilità diverse",
        
        "formAddTitle": "Aggiungi membro",
        "formEditTitle": "Informazioni sul membro",
        "nameLabel": "Nome del membro *",
        "namePlaceholder": "Es: Giovanni",
        "nameRequired": "Inserisci un nome.",
        "genderLabel": "Genere (per l'avatar)",
        "genderMale": "Uomo",
        "genderFemale": "Donna",
        "genderOther": "Altro",
        "groupLabel": "Gruppo / Famiglia (Opzionale)",
        "groupPlaceholder": "Es: Famiglia A...",
        "phoneLabel": "Telefono (Opzionale)",
        "phonePlaceholder": "Es: 0987654321",
        "phoneHelp": "Per contatti rapidi durante il viaggio.",
        "roleLabel": "Ruolo nel viaggio",
        "viewRoles": "Vedi ruoli",
        "noteLabel": "Note (Opzionale)",
        "notePlaceholder": "Note aggiuntive...",
        "btnCancel": "Annulla",
        "btnSave": "Salva modifiche",
        "btnAdd": "Aggiungi membro",
        "btnSuggestAdd": "Suggerisci aggiunta",
        "btnSuggestRole": "Suggerisci ruolo",
        
        "groupPrefix": "Gruppo: ",
        "phonePrefix": "Tel: ",
        "taskCount": "compiti",
        "paidPrefix": "Pagato: ",
        "paidTimes": "volte",
        
        "suggestNew": "Nuova richiesta",
        "suggestChangeRole": "Richiesta ruolo",
        "suggestDelete": "Richiesta elim.",
        "options": "Opzioni",
        "changeRole": "Cambia ruolo",
        
        "suggestDeleteTitle": "Suggerire l'eliminazione?",
        "suggestDeleteDesc": "Il creatore del viaggio esaminerà la richiesta.",
        "suggestDeleteBtn": "Suggerisci l'eliminazione",
        
        "deleteTitle": "Eliminare il membro?",
        "deleteDesc": "Sei sicuro di voler eliminare questo membro? Questa azione non può essere annullata.",
        "deleteBtn": "Elimina membro",
        
        "suggestRoleTitle": "Suggerisci cambio ruolo",
        "memberLabel": "Membro: ",
        "chooseNewRole": "Scegli nuovo ruolo"
    },
    "pt": {
        "membersTitle": "Membros",
        "membersSubtitle": "Gerencie os participantes e compartilhe a viagem.",
        "addMember": "Adicionar membro",
        "statMembers": "MEMBROS",
        "statTasks": "TAREFAS",
        "statPaid": "PAGO",
        "statReady": "Pronto",
        "statNeedMore": "Faltam",
        "statSplit": "DIVIDIR",
        "emptyMembers": "Adicione membros para dividir custos e atribuir tarefas.",
        "memberListTitle": "Lista de membros",
        "searchMember": "Buscar membros ou funções...",
        "noSearchResults": "Nenhum membro encontrado",
        "noMembersYet": "Ainda não há membros na viagem.",
        
        "roleLeader": "Líder",
        "roleLeaderDesc": "Criador da viagem com privilégios totais.",
        "roleDriver": "Motorista",
        "roleDriverDesc": "Encarregado do transporte e da direção.",
        "roleNavigator": "Navegador",
        "roleNavigatorDesc": "Encarregado da rota e dos mapas.",
        "roleCostManager": "Gestão de custos",
        "roleCostManagerDesc": "Gerencia o fundo comum e divide as despesas.",
        "roleCompanion": "Acompanhante",
        "roleCompanionDesc": "Vê as informações e envia sugestões.",
        "roleLuggage": "Bagagem",
        "roleLuggageDesc": "Gerencia a bagagem comum.",
        
        "permEditTripDirectly": "Editar itinerário",
        "permManageCostDirectly": "Gerenciar custos",
        "permSuggestCost": "Sugerir despesas",
        "permSuggestTrip": "Sugerir mudanças",
        
        "rolesHelpTitle": "Informações sobre funções",
        "rolesHelpSubtitle": "Cada membro tem diferentes responsabilidades",
        
        "formAddTitle": "Adicionar membro",
        "formEditTitle": "Informações do membro",
        "nameLabel": "Nome do membro *",
        "namePlaceholder": "Ex: João",
        "nameRequired": "Por favor, insira um nome.",
        "genderLabel": "Gênero (para o avatar)",
        "genderMale": "Homem",
        "genderFemale": "Mulher",
        "genderOther": "Outro",
        "groupLabel": "Grupo / Família (Opcional)",
        "groupPlaceholder": "Ex: Família A...",
        "phoneLabel": "Telefone (Opcional)",
        "phonePlaceholder": "Ex: 0987654321",
        "phoneHelp": "Para contato rápido durante a viagem.",
        "roleLabel": "Função na viagem",
        "viewRoles": "Ver funções",
        "noteLabel": "Notas (Opcional)",
        "notePlaceholder": "Notas adicionais...",
        "btnCancel": "Cancelar",
        "btnSave": "Salvar",
        "btnAdd": "Adicionar membro",
        "btnSuggestAdd": "Sugerir membro",
        "btnSuggestRole": "Sugerir função",
        
        "groupPrefix": "Grupo: ",
        "phonePrefix": "Tel: ",
        "taskCount": "tarefas",
        "paidPrefix": "Pago: ",
        "paidTimes": "vezes",
        
        "suggestNew": "Nova sugestão",
        "suggestChangeRole": "Sugestão de função",
        "suggestDelete": "Sugestão de exclusão",
        "options": "Opções",
        "changeRole": "Mudar função",
        
        "suggestDeleteTitle": "Sugerir exclusão?",
        "suggestDeleteDesc": "O criador da viagem revisará esta solicitação.",
        "suggestDeleteBtn": "Sugerir exclusão",
        
        "deleteTitle": "Excluir membro?",
        "deleteDesc": "Tem certeza de que deseja excluir este membro? Esta ação não pode ser desfeita.",
        "deleteBtn": "Excluir membro",
        
        "suggestRoleTitle": "Sugerir mudança de função",
        "memberLabel": "Membro: ",
        "chooseNewRole": "Escolha nova função"
    },
    "id": {
        "membersTitle": "Anggota",
        "membersSubtitle": "Kelola peserta dan bagikan perjalanan.",
        "addMember": "Tambah anggota",
        "statMembers": "ANGGOTA",
        "statTasks": "TUGAS",
        "statPaid": "DIBAYAR",
        "statReady": "Siap",
        "statNeedMore": "Kurang",
        "statSplit": "BAGI BIAYA",
        "emptyMembers": "Tambahkan anggota untuk membagi biaya dan membagikan tugas.",
        "memberListTitle": "Daftar anggota",
        "searchMember": "Cari anggota atau peran...",
        "noSearchResults": "Tidak ada anggota yang cocok",
        "noMembersYet": "Belum ada anggota dalam perjalanan.",
        
        "roleLeader": "Pemimpin",
        "roleLeaderDesc": "Pembuat perjalanan dengan hak istimewa penuh.",
        "roleDriver": "Sopir",
        "roleDriverDesc": "Bertanggung jawab atas transportasi dan mengemudi.",
        "roleNavigator": "Navigator",
        "roleNavigatorDesc": "Bertanggung jawab atas rute dan peta.",
        "roleCostManager": "Manajer Biaya",
        "roleCostManagerDesc": "Mengelola dana bersama dan membagi pengeluaran.",
        "roleCompanion": "Pendamping",
        "roleCompanionDesc": "Melihat informasi perjalanan dan mengirim saran.",
        "roleLuggage": "Bagasi",
        "roleLuggageDesc": "Mengelola bagasi bersama.",
        
        "permEditTripDirectly": "Edit rencana perjalanan",
        "permManageCostDirectly": "Kelola biaya",
        "permSuggestCost": "Saran pengeluaran",
        "permSuggestTrip": "Saran perubahan",
        
        "rolesHelpTitle": "Informasi Peran",
        "rolesHelpSubtitle": "Setiap anggota memiliki tanggung jawab berbeda",
        
        "formAddTitle": "Tambah anggota",
        "formEditTitle": "Informasi anggota",
        "nameLabel": "Nama anggota *",
        "namePlaceholder": "Cth: Budi",
        "nameRequired": "Silakan masukkan nama.",
        "genderLabel": "Jenis kelamin (untuk avatar)",
        "genderMale": "Pria",
        "genderFemale": "Wanita",
        "genderOther": "Lainnya",
        "groupLabel": "Grup / Keluarga (Opsional)",
        "groupPlaceholder": "Cth: Keluarga A...",
        "phoneLabel": "Telepon (Opsional)",
        "phonePlaceholder": "Cth: 0987654321",
        "phoneHelp": "Untuk kontak cepat selama perjalanan.",
        "roleLabel": "Peran perjalanan",
        "viewRoles": "Lihat peran",
        "noteLabel": "Catatan (Opsional)",
        "notePlaceholder": "Catatan tambahan...",
        "btnCancel": "Batal",
        "btnSave": "Simpan",
        "btnAdd": "Tambah anggota",
        "btnSuggestAdd": "Saran penambahan",
        "btnSuggestRole": "Saran peran",
        
        "groupPrefix": "Grup: ",
        "phonePrefix": "Telp: ",
        "taskCount": "tugas",
        "paidPrefix": "Dibayar: ",
        "paidTimes": "kali",
        
        "suggestNew": "Saran baru",
        "suggestChangeRole": "Saran peran",
        "suggestDelete": "Saran hapus",
        "options": "Opsi",
        "changeRole": "Ubah peran",
        
        "suggestDeleteTitle": "Saran untuk menghapus?",
        "suggestDeleteDesc": "Pembuat perjalanan akan meninjau permintaan ini.",
        "suggestDeleteBtn": "Sarankan hapus",
        
        "deleteTitle": "Hapus anggota?",
        "deleteDesc": "Apakah Anda yakin ingin menghapus anggota ini? Tindakan ini tidak dapat dibatalkan.",
        "deleteBtn": "Hapus anggota",
        
        "suggestRoleTitle": "Sarankan ubah peran",
        "memberLabel": "Anggota: ",
        "chooseNewRole": "Pilih peran baru"
    }
}

def update_locales():
    for lang, trans in translations.items():
        filepath = f"src/locales/{lang}.json"
        if not os.path.exists(filepath):
            continue
            
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        if "members" not in data:
            data["members"] = {}
        if "roles" not in data:
            data["roles"] = {}
            
        # Distribute keys to "members" and "roles" namespaces based on context
        for key, val in trans.items():
            if key.startswith("role") or key.startswith("perm"):
                data["roles"][key] = val
            else:
                data["members"][key] = val
                
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated {filepath}")

if __name__ == "__main__":
    update_locales()
