import json
import os

translations = {
    "ko": {
        "pageTitle": "비용",
        "pageSubtitle": "여행 중 지출, 결제 및 분담 내역을 추적합니다.",
        "addExpense": "비용 추가",
        "totalTrip": "총 여행 비용",
        "sharedTrip": "공동 비용",
        "personalExpense": "개인 비용",
        "avgPerGroup": "그룹당 평균",
        "avgPerPerson": "1인당 평균",
        "noCompanion": "아직 동행자가 없습니다",
        "byCategory": "카테고리별 비용",
        "sharePerMember": "인원/그룹별 분담금",
        "addCompanionStats": "통계를 보려면 동행자를 추가하세요.",
        "addCompanionShare": "개별 분담금을 보려면 동행자를 추가하세요.",
        "expenseList": "비용 목록",
        "noExpenses": "아직 비용 내역이 없습니다",
        "noExpensesDesc": "여행 후 자동으로 정산할 수 있도록 식사, 교통, 티켓 비용을 기록하세요.",
        "deleteTitle": "이 비용을 삭제하시겠습니까?",
        "deleteDesc": "이 비용은 여행 목록에서 제거됩니다. 삭제 후에는 되돌릴 수 없습니다.",
        "deleteConfirm": "비용 삭제",
        "settlementTitle": "비용 정산",
        "settlementBalanced": "모든 정산이 완료되었습니다. 빚진 사람이 없습니다.",
        "settlementAddCompanion": "분담금이나 환불액을 계산하려면 동행자를 추가하세요.",
        "settlementNoExpense": "정산할 공동 비용이 없습니다.",
        "groupLabel": "(그룹: {{group}})",
        "unnamed": "이름 없는 비용",
        "splitPersonal": "개인",
        "splitPerGroup": "그룹별",
        "splitShared": "공동",
        "paidByOf": "소유자: {{name}}",
        "paidByPay": "결제자: {{name}}",
        "paidByNone": "미지정",
        "personalLabel": "개인",
        "forNPeople": "({{count}}명)",
        "options": "옵션",
        "edit": "편집",
        "delete": "삭제",
        "editExpense": "비용 편집",
        "amount": "금액",
        "selectCurrency": "통화 선택",
        "vnd": "VND (베트남 동)",
        "exchangeRate": "환율: 1 {{currency}} = {{rate}} VND",
        "errAmount": "0보다 큰 금액을 입력하세요.",
        "errPayer": "결제자를 선택하세요.",
        "errCategory": "카테고리 이름을 입력하세요.",
        "dateLabel": "날짜",
        "descLabel": "내용",
        "descPlaceholder": "예: 택시, 점심, 티켓...",
        "payerLabel": "결제자",
        "payerPlaceholder": "결제자 선택",
        "noCompanionWarn": "아직 여행에 동행자가 없습니다. 분담금을 계산하려면 추가하세요.",
        "personalOwner": "이 비용은 누구의 것입니까?",
        "personalPlaceholder": "동행자 선택 (선택 사항)",
        "advanced": "고급 설정",
        "categoryLabel": "카테고리",
        "customCatLabel": "사용자 지정 카테고리 이름 *",
        "customCatPlaceholder": "예: 기념품, 오토바이 대여",
        "linkTimeline": "일정에 연결 (선택 사항)",
        "noLink": "연결 안 함 (일반 비용)",
        "splitMethod": "분담 방법",
        "splitSharedGroup": "그룹 공동",
        "splitPersonalSelf": "각자 결제",
        "allPeople": "모두",
        "nParticipants": "참여자 {{count}}명",
        "participateAll": "모두",
        "participateN": "{{count}}명",
        "participate": "참여",
        "close": "닫기",
        "reselectAll": "모두 다시 선택",
        "perPerson": "개인별",
        "perGroup": "가족별",
        "save": "저장",
        "add": "추가",
        "toastUpdated": "비용이 업데이트되었습니다",
        "toastAdded": "비용이 추가되었습니다",
        "noCatYet": "아직 비용 카테고리가 없습니다.",
        "noSharedAnalysis": "분석할 공동 비용이 없습니다.",
        "noExpenseAnalysis": "분석할 비용이 없습니다.",
        "noExpenseList": "목록에 아직 비용이 없습니다",
        "noCompanionShared": "아직 동행자가 없습니다. '각자 결제'를 선택하거나 동행자 추가를 제안하세요.",
        "sharedSuggest": "여행 후 동일하게 나누어 정산할 비용을 제안하세요.",
        "suggestOption": "제안 옵션",
        "paidBy": "결제자:",
        "savingNew": "저장 중...",
        "suggestNew": "새 제안",
        "savingEdit": "저장 중...",
        "suggestEdit": "제안 편집",
        "deletingSugg": "삭제 중...",
        "suggestDelete": "제안 삭제",
        "splitGroupLabel": "그룹 공동",
        "personalSelfLabel": "각자 결제",
        "catTransport": "교통",
        "catFlights": "항공권",
        "catFood": "식음료",
        "catAccommodation": "숙박",
        "catTickets": "티켓/관광",
        "catShopping": "쇼핑",
        "catEntertainment": "엔터테인먼트",
        "catPreparation": "준비물",
        "catOther": "기타",
        "catCustom": "기타..."
    },
    "zh": {
        "pageTitle": "费用",
        "pageSubtitle": "跟踪旅行期间的支出、付款和分摊情况。",
        "addExpense": "添加费用",
        "totalTrip": "旅行总费用",
        "sharedTrip": "共同费用",
        "personalExpense": "个人费用",
        "avgPerGroup": "每组平均",
        "avgPerPerson": "人均",
        "noCompanion": "暂无同行者",
        "byCategory": "按类别统计",
        "sharePerMember": "每人/组的分摊额",
        "addCompanionStats": "添加同行者以查看统计数据。",
        "addCompanionShare": "添加同行者以查看个人分摊额。",
        "expenseList": "费用列表",
        "noExpenses": "暂无费用",
        "noExpensesDesc": "记录您的餐饮、交通和门票费用，以便在旅行后自动结算。",
        "deleteTitle": "删除此费用？",
        "deleteDesc": "此费用将从旅行中移除。删除后无法撤销。",
        "deleteConfirm": "删除费用",
        "settlementTitle": "费用结算",
        "settlementBalanced": "所有人已结清，互不相欠。",
        "settlementAddCompanion": "添加同行者以计算分摊额或退款。",
        "settlementNoExpense": "暂无需要结算的共同费用。",
        "groupLabel": "(组别: {{group}})",
        "unnamed": "未命名费用",
        "splitPersonal": "个人",
        "splitPerGroup": "按组",
        "splitShared": "共同",
        "paidByOf": "归属: {{name}}",
        "paidByPay": "付款人: {{name}}",
        "paidByNone": "未指定",
        "personalLabel": "个人",
        "forNPeople": "({{count}}人)",
        "options": "选项",
        "edit": "编辑",
        "delete": "删除",
        "editExpense": "编辑费用",
        "amount": "金额",
        "selectCurrency": "选择货币",
        "vnd": "VND (越南盾)",
        "exchangeRate": "汇率: 1 {{currency}} = {{rate}} VND",
        "errAmount": "请输入大于0的金额。",
        "errPayer": "请选择付款人。",
        "errCategory": "请输入类别名称。",
        "dateLabel": "日期",
        "descLabel": "描述",
        "descPlaceholder": "例: 出租车、午餐、门票...",
        "payerLabel": "付款人",
        "payerPlaceholder": "选择付款人",
        "noCompanionWarn": "旅行中暂无同行者。请添加同行者以计算分摊额。",
        "personalOwner": "这笔费用是谁的？",
        "personalPlaceholder": "选择同行者 (可选)",
        "advanced": "高级详情",
        "categoryLabel": "类别",
        "customCatLabel": "自定义类别名称 *",
        "customCatPlaceholder": "例: 纪念品、租摩托车",
        "linkTimeline": "关联到行程 (可选)",
        "noLink": "不关联 (一般费用)",
        "splitMethod": "分摊方式",
        "splitSharedGroup": "群组分摊",
        "splitPersonalSelf": "自己付款",
        "allPeople": "所有人",
        "nParticipants": "{{count}}人参与",
        "participateAll": "全部",
        "participateN": "{{count}}人",
        "participate": "参与",
        "close": "关闭",
        "reselectAll": "重新全选",
        "perPerson": "按人",
        "perGroup": "按家庭",
        "save": "保存",
        "add": "添加",
        "toastUpdated": "费用已更新",
        "toastAdded": "费用已添加",
        "noCatYet": "暂无费用类别。",
        "noSharedAnalysis": "暂无共同费用可供分析。",
        "noExpenseAnalysis": "暂无费用可供分析。",
        "noExpenseList": "列表中暂无费用",
        "noCompanionShared": "暂无同行者。请选择“自己付款”或建议添加同行者。",
        "sharedSuggest": "建议将费用平摊并在旅行后结算。",
        "suggestOption": "建议选项",
        "paidBy": "付款人:",
        "savingNew": "保存中...",
        "suggestNew": "新建议",
        "savingEdit": "保存中...",
        "suggestEdit": "编辑建议",
        "deletingSugg": "删除中...",
        "suggestDelete": "删除建议",
        "splitGroupLabel": "群组分摊",
        "personalSelfLabel": "自己付款",
        "catTransport": "交通",
        "catFlights": "机票",
        "catFood": "餐饮",
        "catAccommodation": "住宿",
        "catTickets": "门票/观光",
        "catShopping": "购物",
        "catEntertainment": "娱乐",
        "catPreparation": "行前准备",
        "catOther": "其他",
        "catCustom": "其他..."
    },
    "ja": {
        "pageTitle": "費用",
        "pageSubtitle": "旅行中の支出、支払い、割り勘を記録します。",
        "addExpense": "費用を追加",
        "totalTrip": "旅行の総費用",
        "sharedTrip": "共同費用",
        "personalExpense": "個人費用",
        "avgPerGroup": "グループ平均",
        "avgPerPerson": "1人あたり",
        "noCompanion": "まだ同行者がいません",
        "byCategory": "カテゴリー別費用",
        "sharePerMember": "人/グループごとの負担額",
        "addCompanionStats": "同行者を追加して統計を表示します。",
        "addCompanionShare": "同行者を追加して個別の負担額を表示します。",
        "expenseList": "費用リスト",
        "noExpenses": "まだ費用はありません",
        "noExpensesDesc": "食事、交通、チケット代を記録して旅行後に自動で精算します。",
        "deleteTitle": "この費用を削除しますか？",
        "deleteDesc": "この費用は旅行から削除されます。元に戻すことはできません。",
        "deleteConfirm": "費用を削除",
        "settlementTitle": "精算",
        "settlementBalanced": "全員が精算済みです。貸し借りがありません。",
        "settlementAddCompanion": "同行者を追加して分担額や返金額を計算します。",
        "settlementNoExpense": "精算する共同費用がまだありません。",
        "groupLabel": "(グループ: {{group}})",
        "unnamed": "名前のない費用",
        "splitPersonal": "個人",
        "splitPerGroup": "グループ別",
        "splitShared": "共同",
        "paidByOf": "所有者: {{name}}",
        "paidByPay": "支払い者: {{name}}",
        "paidByNone": "未指定",
        "personalLabel": "個人",
        "forNPeople": "({{count}}人用)",
        "options": "オプション",
        "edit": "編集",
        "delete": "削除",
        "editExpense": "費用を編集",
        "amount": "金額",
        "selectCurrency": "通貨を選択",
        "vnd": "VND (ベトナム ドン)",
        "exchangeRate": "レート: 1 {{currency}} = {{rate}} VND",
        "errAmount": "0より大きい金額を入力してください。",
        "errPayer": "支払い者を選択してください。",
        "errCategory": "カテゴリー名を入力してください。",
        "dateLabel": "日付",
        "descLabel": "説明",
        "descPlaceholder": "例: タクシー、昼食、チケット...",
        "payerLabel": "支払い者",
        "payerPlaceholder": "支払い者を選択",
        "noCompanionWarn": "旅行にまだ同行者がいません。追加して割り勘を計算してください。",
        "personalOwner": "この費用は誰のものですか？",
        "personalPlaceholder": "同行者を選択 (任意)",
        "advanced": "詳細設定",
        "categoryLabel": "カテゴリー",
        "customCatLabel": "カスタムカテゴリー名 *",
        "customCatPlaceholder": "例: お土産、バイクレンタル",
        "linkTimeline": "旅程にリンク (任意)",
        "noLink": "リンクしない (一般費用)",
        "splitMethod": "割り勘方法",
        "splitSharedGroup": "グループで共有",
        "splitPersonalSelf": "各自で支払い",
        "allPeople": "全員",
        "nParticipants": "参加者 {{count}}人",
        "participateAll": "すべて",
        "participateN": "{{count}}人",
        "participate": "参加",
        "close": "閉じる",
        "reselectAll": "すべて再選択",
        "perPerson": "個人別",
        "perGroup": "家族別",
        "save": "保存",
        "add": "追加",
        "toastUpdated": "費用が更新されました",
        "toastAdded": "費用が追加されました",
        "noCatYet": "費用カテゴリーがまだありません。",
        "noSharedAnalysis": "分析する共同費用がありません。",
        "noExpenseAnalysis": "分析する費用がありません。",
        "noExpenseList": "リストにまだ費用がありません",
        "noCompanionShared": "まだ同行者がいません。「各自で支払い」を選択するか、同行者の追加を提案してください。",
        "sharedSuggest": "費用を均等に割り勘して後で精算することを提案します。",
        "suggestOption": "提案のオプション",
        "paidBy": "支払い者:",
        "savingNew": "保存中...",
        "suggestNew": "新しい提案",
        "savingEdit": "保存中...",
        "suggestEdit": "提案を編集",
        "deletingSugg": "削除中...",
        "suggestDelete": "提案を削除",
        "splitGroupLabel": "グループで共有",
        "personalSelfLabel": "各自で支払い",
        "catTransport": "交通",
        "catFlights": "航空券",
        "catFood": "飲食",
        "catAccommodation": "宿泊",
        "catTickets": "チケット/観光",
        "catShopping": "ショッピング",
        "catEntertainment": "エンターテイメント",
        "catPreparation": "準備",
        "catOther": "その他",
        "catCustom": "その他..."
    },
    "fr": {
        "pageTitle": "Dépenses",
        "pageSubtitle": "Suivez les dépenses, les paiements et le partage pendant le voyage.",
        "addExpense": "Ajouter",
        "totalTrip": "Dépenses totales",
        "sharedTrip": "Dépenses partagées",
        "personalExpense": "Dépenses personnelles",
        "avgPerGroup": "Moy. / Groupe",
        "avgPerPerson": "Moy. / Pers.",
        "noCompanion": "Pas encore de compagnons",
        "byCategory": "Par catégorie",
        "sharePerMember": "Part par personne/groupe",
        "addCompanionStats": "Ajoutez des compagnons pour les statistiques.",
        "addCompanionShare": "Ajoutez des compagnons pour voir les parts.",
        "expenseList": "Liste des dépenses",
        "noExpenses": "Aucune dépense",
        "noExpensesDesc": "Enregistrez vos repas, transports et billets pour un équilibrage automatique.",
        "deleteTitle": "Supprimer cette dépense ?",
        "deleteDesc": "Cette dépense sera retirée. Cette action est irréversible.",
        "deleteConfirm": "Supprimer",
        "settlementTitle": "Équilibre des comptes",
        "settlementBalanced": "Tout est réglé. Personne ne doit rien.",
        "settlementAddCompanion": "Ajoutez des compagnons pour calculer les parts.",
        "settlementNoExpense": "Pas de dépenses partagées à équilibrer.",
        "groupLabel": "(Groupe: {{group}})",
        "unnamed": "Dépense sans nom",
        "splitPersonal": "Personnel",
        "splitPerGroup": "Par Groupe",
        "splitShared": "Partagé",
        "paidByOf": "À: {{name}}",
        "paidByPay": "Payé par: {{name}}",
        "paidByNone": "Non assigné",
        "personalLabel": "Personnel",
        "forNPeople": "(pour {{count}})",
        "options": "Options",
        "edit": "Modifier",
        "delete": "Supprimer",
        "editExpense": "Modifier la dépense",
        "amount": "Montant",
        "selectCurrency": "Choisir la devise",
        "vnd": "VND (Dong)",
        "exchangeRate": "Taux: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Entrez un montant > 0.",
        "errPayer": "Sélectionnez un payeur.",
        "errCategory": "Entrez une catégorie.",
        "dateLabel": "Date",
        "descLabel": "Description",
        "descPlaceholder": "Ex: Taxi, déjeuner...",
        "payerLabel": "Payé par",
        "payerPlaceholder": "Sélectionner payeur",
        "noCompanionWarn": "Pas de compagnon. Ajoutez-en pour calculer le partage.",
        "personalOwner": "À qui est cette dépense ?",
        "personalPlaceholder": "Choisir compagnon (optionnel)",
        "advanced": "Détails avancés",
        "categoryLabel": "Catégorie",
        "customCatLabel": "Catégorie personnalisée *",
        "customCatPlaceholder": "Ex: Souvenirs",
        "linkTimeline": "Lier à l'itinéraire (Optionnel)",
        "noLink": "Ne pas lier",
        "splitMethod": "Méthode de partage",
        "splitSharedGroup": "Partagé en groupe",
        "splitPersonalSelf": "Paie pour soi",
        "allPeople": "Tous",
        "nParticipants": "{{count}} participants",
        "participateAll": "Tous",
        "participateN": "{{count}} pers.",
        "participate": "Participants",
        "close": "Fermer",
        "reselectAll": "Tout sélectionner",
        "perPerson": "Par Pers.",
        "perGroup": "Par Famille",
        "save": "Enregistrer",
        "add": "Ajouter",
        "toastUpdated": "Dépense mise à jour",
        "toastAdded": "Dépense ajoutée",
        "noCatYet": "Pas encore de catégories.",
        "noSharedAnalysis": "Pas de dépenses partagées à analyser.",
        "noExpenseAnalysis": "Pas de dépenses à analyser.",
        "noExpenseList": "Aucune dépense dans la liste",
        "noCompanionShared": "Pas de compagnons. Choisissez \"Paie pour soi\" ou suggérez-en.",
        "sharedSuggest": "Suggérer de partager équitablement.",
        "suggestOption": "Options de suggestion",
        "paidBy": "Payé par:",
        "savingNew": "Enregistrement...",
        "suggestNew": "Nouvelle suggestion",
        "savingEdit": "Enregistrement...",
        "suggestEdit": "Modifier la suggestion",
        "deletingSugg": "Suppression...",
        "suggestDelete": "Supprimer la suggestion",
        "splitGroupLabel": "Partagé en groupe",
        "personalSelfLabel": "Paie pour soi",
        "catTransport": "Transport",
        "catFlights": "Vols",
        "catFood": "Alimentation",
        "catAccommodation": "Hébergement",
        "catTickets": "Billets/Visites",
        "catShopping": "Achats",
        "catEntertainment": "Divertissement",
        "catPreparation": "Préparation",
        "catOther": "Autre",
        "catCustom": "Autre..."
    },
    "de": {
        "pageTitle": "Ausgaben",
        "pageSubtitle": "Ausgaben, Zahlungen und Aufteilungen verfolgen.",
        "addExpense": "Hinzufügen",
        "totalTrip": "Gesamtausgaben",
        "sharedTrip": "Geteilte Ausgaben",
        "personalExpense": "Persönliche Ausgaben",
        "avgPerGroup": "Ø / Gruppe",
        "avgPerPerson": "Ø / Person",
        "noCompanion": "Noch keine Begleiter",
        "byCategory": "Nach Kategorie",
        "sharePerMember": "Anteil pro Person/Gruppe",
        "addCompanionStats": "Begleiter hinzufügen für Statistiken.",
        "addCompanionShare": "Begleiter hinzufügen, um Anteile zu sehen.",
        "expenseList": "Ausgabenliste",
        "noExpenses": "Noch keine Ausgaben",
        "noExpensesDesc": "Essen, Transport und Tickets erfassen für autom. Abrechnung.",
        "deleteTitle": "Ausgabe löschen?",
        "deleteDesc": "Diese Ausgabe wird entfernt. Dies kann nicht rückgängig gemacht werden.",
        "deleteConfirm": "Löschen",
        "settlementTitle": "Abrechnung",
        "settlementBalanced": "Alle sind quitt. Niemand schuldet etwas.",
        "settlementAddCompanion": "Begleiter hinzufügen, um Anteile zu berechnen.",
        "settlementNoExpense": "Keine geteilten Ausgaben zur Abrechnung.",
        "groupLabel": "(Gruppe: {{group}})",
        "unnamed": "Unbenannte Ausgabe",
        "splitPersonal": "Persönlich",
        "splitPerGroup": "Pro Gruppe",
        "splitShared": "Geteilt",
        "paidByOf": "Von: {{name}}",
        "paidByPay": "Bezahlt von: {{name}}",
        "paidByNone": "Nicht zugewiesen",
        "personalLabel": "Persönlich",
        "forNPeople": "(für {{count}})",
        "options": "Optionen",
        "edit": "Bearbeiten",
        "delete": "Löschen",
        "editExpense": "Ausgabe bearbeiten",
        "amount": "Betrag",
        "selectCurrency": "Währung",
        "vnd": "VND",
        "exchangeRate": "Kurs: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Betrag > 0 eingeben.",
        "errPayer": "Zahler auswählen.",
        "errCategory": "Kategorie eingeben.",
        "dateLabel": "Datum",
        "descLabel": "Beschreibung",
        "descPlaceholder": "Z.B. Taxi, Mittagessen...",
        "payerLabel": "Bezahlt von",
        "payerPlaceholder": "Zahler wählen",
        "noCompanionWarn": "Keine Begleiter. Hinzufügen für Aufteilung.",
        "personalOwner": "Wessen Ausgabe?",
        "personalPlaceholder": "Begleiter wählen (optional)",
        "advanced": "Erweitert",
        "categoryLabel": "Kategorie",
        "customCatLabel": "Eigene Kategorie *",
        "customCatPlaceholder": "Z.B. Souvenirs",
        "linkTimeline": "Mit Reiseplan verknüpfen",
        "noLink": "Nicht verknüpfen",
        "splitMethod": "Aufteilung",
        "splitSharedGroup": "In Gruppe geteilt",
        "splitPersonalSelf": "Zahlt für sich selbst",
        "allPeople": "Alle",
        "nParticipants": "{{count}} Teilnehmer",
        "participateAll": "Alle",
        "participateN": "{{count}} Pers.",
        "participate": "Teilnehmer",
        "close": "Schließen",
        "reselectAll": "Alle auswählen",
        "perPerson": "Pro Person",
        "perGroup": "Pro Familie",
        "save": "Speichern",
        "add": "Hinzufügen",
        "toastUpdated": "Aktualisiert",
        "toastAdded": "Hinzugefügt",
        "noCatYet": "Noch keine Kategorien.",
        "noSharedAnalysis": "Keine geteilten Ausgaben zur Analyse.",
        "noExpenseAnalysis": "Keine Ausgaben zur Analyse.",
        "noExpenseList": "Noch keine Ausgaben in der Liste",
        "noCompanionShared": "Keine Begleiter. 'Zahlt für sich selbst' wählen oder Begleiter vorschlagen.",
        "sharedSuggest": "Vorschlagen, Ausgaben gleichmäßig zu teilen.",
        "suggestOption": "Vorschlagsoptionen",
        "paidBy": "Bezahlt von:",
        "savingNew": "Speichern...",
        "suggestNew": "Neuer Vorschlag",
        "savingEdit": "Speichern...",
        "suggestEdit": "Vorschlag bearbeiten",
        "deletingSugg": "Löschen...",
        "suggestDelete": "Vorschlag löschen",
        "splitGroupLabel": "In Gruppe geteilt",
        "personalSelfLabel": "Zahlt für sich selbst",
        "catTransport": "Transport",
        "catFlights": "Flüge",
        "catFood": "Essen & Trinken",
        "catAccommodation": "Unterkunft",
        "catTickets": "Tickets/Touren",
        "catShopping": "Einkaufen",
        "catEntertainment": "Unterhaltung",
        "catPreparation": "Vorbereitung",
        "catOther": "Sonstiges",
        "catCustom": "Sonstiges..."
    },
    "it": {
        "pageTitle": "Spese",
        "pageSubtitle": "Tieni traccia di spese, pagamenti e divisioni.",
        "addExpense": "Aggiungi",
        "totalTrip": "Spese Totali",
        "sharedTrip": "Spese Condivise",
        "personalExpense": "Spese Personali",
        "avgPerGroup": "Med. / Gruppo",
        "avgPerPerson": "Med. / Persona",
        "noCompanion": "Nessun compagno",
        "byCategory": "Per Categoria",
        "sharePerMember": "Quota per Persona/Gruppo",
        "addCompanionStats": "Aggiungi compagni per le statistiche.",
        "addCompanionShare": "Aggiungi compagni per vedere le quote.",
        "expenseList": "Lista Spese",
        "noExpenses": "Nessuna spesa",
        "noExpensesDesc": "Registra pasti, trasporti e biglietti per bilanciare automaticamente.",
        "deleteTitle": "Eliminare questa spesa?",
        "deleteDesc": "Questa spesa verrà rimossa. L'azione è irreversibile.",
        "deleteConfirm": "Elimina",
        "settlementTitle": "Bilancio",
        "settlementBalanced": "Siete pari. Nessuno deve nulla.",
        "settlementAddCompanion": "Aggiungi compagni per calcolare le quote.",
        "settlementNoExpense": "Nessuna spesa condivisa da bilanciare.",
        "groupLabel": "(Gruppo: {{group}})",
        "unnamed": "Spesa senza nome",
        "splitPersonal": "Personale",
        "splitPerGroup": "Per Gruppo",
        "splitShared": "Condivisa",
        "paidByOf": "Di: {{name}}",
        "paidByPay": "Pagato da: {{name}}",
        "paidByNone": "Non assegnato",
        "personalLabel": "Personale",
        "forNPeople": "(per {{count}})",
        "options": "Opzioni",
        "edit": "Modifica",
        "delete": "Elimina",
        "editExpense": "Modifica Spesa",
        "amount": "Importo",
        "selectCurrency": "Valuta",
        "vnd": "VND",
        "exchangeRate": "Tasso: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Inserisci importo > 0.",
        "errPayer": "Seleziona pagatore.",
        "errCategory": "Inserisci categoria.",
        "dateLabel": "Data",
        "descLabel": "Descrizione",
        "descPlaceholder": "Es: Taxi, pranzo...",
        "payerLabel": "Pagato da",
        "payerPlaceholder": "Seleziona",
        "noCompanionWarn": "Nessun compagno. Aggiungi per dividere.",
        "personalOwner": "Di chi è questa spesa?",
        "personalPlaceholder": "Seleziona (opzionale)",
        "advanced": "Avanzate",
        "categoryLabel": "Categoria",
        "customCatLabel": "Categoria personalizzata *",
        "customCatPlaceholder": "Es: Souvenir",
        "linkTimeline": "Collega a Itinerario (Opzionale)",
        "noLink": "Non collegare",
        "splitMethod": "Metodo di divisione",
        "splitSharedGroup": "Condiviso nel gruppo",
        "splitPersonalSelf": "Paga per sé",
        "allPeople": "Tutti",
        "nParticipants": "{{count}} partecipanti",
        "participateAll": "Tutti",
        "participateN": "{{count}} pers.",
        "participate": "Partecipanti",
        "close": "Chiudi",
        "reselectAll": "Seleziona Tutti",
        "perPerson": "Per Persona",
        "perGroup": "Per Famiglia",
        "save": "Salva",
        "add": "Aggiungi",
        "toastUpdated": "Aggiornato",
        "toastAdded": "Aggiunto",
        "noCatYet": "Ancora nessuna categoria.",
        "noSharedAnalysis": "Nessuna spesa condivisa da analizzare.",
        "noExpenseAnalysis": "Nessuna spesa da analizzare.",
        "noExpenseList": "Nessuna spesa nella lista",
        "noCompanionShared": "Nessun compagno. Scegli 'Paga per sé' o suggerisci compagni.",
        "sharedSuggest": "Suggerisci di dividere equamente e saldare dopo.",
        "suggestOption": "Opzioni suggerimento",
        "paidBy": "Pagato da:",
        "savingNew": "Salvataggio...",
        "suggestNew": "Nuovo suggerimento",
        "savingEdit": "Salvataggio...",
        "suggestEdit": "Modifica suggerimento",
        "deletingSugg": "Eliminazione...",
        "suggestDelete": "Elimina suggerimento",
        "splitGroupLabel": "Condiviso nel gruppo",
        "personalSelfLabel": "Paga per sé",
        "catTransport": "Trasporto",
        "catFlights": "Voli",
        "catFood": "Cibo e Bevande",
        "catAccommodation": "Alloggio",
        "catTickets": "Biglietti/Tour",
        "catShopping": "Shopping",
        "catEntertainment": "Intrattenimento",
        "catPreparation": "Preparativi",
        "catOther": "Altro",
        "catCustom": "Altro..."
    },
    "pt": {
        "pageTitle": "Despesas",
        "pageSubtitle": "Acompanhe gastos, pagamentos e divisões.",
        "addExpense": "Adicionar",
        "totalTrip": "Despesas Totais",
        "sharedTrip": "Despesas Compartilhadas",
        "personalExpense": "Despesas Pessoais",
        "avgPerGroup": "Média / Grupo",
        "avgPerPerson": "Média / Pessoa",
        "noCompanion": "Sem companheiros",
        "byCategory": "Por Categoria",
        "sharePerMember": "Cota por Pessoa/Grupo",
        "addCompanionStats": "Adicione companheiros para as estatísticas.",
        "addCompanionShare": "Adicione companheiros para ver as cotas.",
        "expenseList": "Lista de Despesas",
        "noExpenses": "Ainda sem despesas",
        "noExpensesDesc": "Registre refeições e transportes para equilibrar automaticamente.",
        "deleteTitle": "Excluir esta despesa?",
        "deleteDesc": "Esta despesa será removida. Isso não pode ser desfeito.",
        "deleteConfirm": "Excluir",
        "settlementTitle": "Acerto de Contas",
        "settlementBalanced": "Estão todos quites. Ninguém deve nada.",
        "settlementAddCompanion": "Adicione companheiros para calcular cotas.",
        "settlementNoExpense": "Nenhuma despesa compartilhada para acertar.",
        "groupLabel": "(Grupo: {{group}})",
        "unnamed": "Despesa sem nome",
        "splitPersonal": "Pessoal",
        "splitPerGroup": "Por Grupo",
        "splitShared": "Compartilhado",
        "paidByOf": "De: {{name}}",
        "paidByPay": "Pago por: {{name}}",
        "paidByNone": "Não atribuído",
        "personalLabel": "Pessoal",
        "forNPeople": "(para {{count}})",
        "options": "Opções",
        "edit": "Editar",
        "delete": "Excluir",
        "editExpense": "Editar Despesa",
        "amount": "Valor",
        "selectCurrency": "Moeda",
        "vnd": "VND",
        "exchangeRate": "Taxa: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Insira um valor > 0.",
        "errPayer": "Selecione o pagador.",
        "errCategory": "Insira uma categoria.",
        "dateLabel": "Data",
        "descLabel": "Descrição",
        "descPlaceholder": "Ex: Táxi, almoço...",
        "payerLabel": "Pago por",
        "payerPlaceholder": "Selecionar",
        "noCompanionWarn": "Sem companheiros. Adicione para dividir.",
        "personalOwner": "De quem é essa despesa?",
        "personalPlaceholder": "Selecionar (opcional)",
        "advanced": "Avançado",
        "categoryLabel": "Categoria",
        "customCatLabel": "Categoria Personalizada *",
        "customCatPlaceholder": "Ex: Lembrancinhas",
        "linkTimeline": "Vincular ao Itinerário (Opcional)",
        "noLink": "Não vincular",
        "splitMethod": "Método de divisão",
        "splitSharedGroup": "Compartilhado no grupo",
        "splitPersonalSelf": "Paga para si",
        "allPeople": "Todos",
        "nParticipants": "{{count}} participantes",
        "participateAll": "Todos",
        "participateN": "{{count}} pes.",
        "participate": "Participantes",
        "close": "Fechar",
        "reselectAll": "Selecionar Todos",
        "perPerson": "Por Pessoa",
        "perGroup": "Por Família",
        "save": "Salvar",
        "add": "Adicionar",
        "toastUpdated": "Atualizado",
        "toastAdded": "Adicionado",
        "noCatYet": "Ainda sem categorias.",
        "noSharedAnalysis": "Nenhuma despesa compartilhada para analisar.",
        "noExpenseAnalysis": "Nenhuma despesa para analisar.",
        "noExpenseList": "Nenhuma despesa na lista",
        "noCompanionShared": "Sem companheiros. Escolha 'Paga para si' ou sugira companheiros.",
        "sharedSuggest": "Sugerir divisão igualitária e acerto posterior.",
        "suggestOption": "Opções de sugestão",
        "paidBy": "Pago por:",
        "savingNew": "Salvando...",
        "suggestNew": "Nova sugestão",
        "savingEdit": "Salvando...",
        "suggestEdit": "Editar sugestão",
        "deletingSugg": "Excluindo...",
        "suggestDelete": "Excluir sugestão",
        "splitGroupLabel": "Compartilhado no grupo",
        "personalSelfLabel": "Paga para si",
        "catTransport": "Transporte",
        "catFlights": "Voos",
        "catFood": "Alimentação",
        "catAccommodation": "Acomodação",
        "catTickets": "Ingressos/Passeios",
        "catShopping": "Compras",
        "catEntertainment": "Entretenimento",
        "catPreparation": "Preparação",
        "catOther": "Outro",
        "catCustom": "Outro..."
    },
    "th": {
        "pageTitle": "ค่าใช้จ่าย",
        "pageSubtitle": "ติดตามการใช้จ่าย การชำระเงิน และการหารค่าใช้จ่าย",
        "addExpense": "เพิ่มค่าใช้จ่าย",
        "totalTrip": "ค่าใช้จ่ายทั้งหมด",
        "sharedTrip": "ค่าใช้จ่ายส่วนรวม",
        "personalExpense": "ค่าใช้จ่ายส่วนตัว",
        "avgPerGroup": "เฉลี่ย / กลุ่ม",
        "avgPerPerson": "เฉลี่ย / คน",
        "noCompanion": "ยังไม่มีผู้ร่วมเดินทาง",
        "byCategory": "แยกตามหมวดหมู่",
        "sharePerMember": "ส่วนแบ่งต่อคน/กลุ่ม",
        "addCompanionStats": "เพิ่มผู้ร่วมเดินทางเพื่อดูสถิติ",
        "addCompanionShare": "เพิ่มผู้ร่วมเดินทางเพื่อดูส่วนแบ่ง",
        "expenseList": "รายการค่าใช้จ่าย",
        "noExpenses": "ยังไม่มีค่าใช้จ่าย",
        "noExpensesDesc": "บันทึกค่าอาหารและเดินทางเพื่อคำนวณส่วนแบ่งอัตโนมัติ",
        "deleteTitle": "ลบค่าใช้จ่ายนี้หรือไม่?",
        "deleteDesc": "ค่าใช้จ่ายนี้จะถูกลบออกจากการเดินทาง ไม่สามารถกู้คืนได้",
        "deleteConfirm": "ลบ",
        "settlementTitle": "สรุปยอดเงิน",
        "settlementBalanced": "ทุกคนจ่ายครบแล้ว ไม่มีใครค้างชำระ",
        "settlementAddCompanion": "เพิ่มผู้ร่วมเดินทางเพื่อคำนวณยอดเงิน",
        "settlementNoExpense": "ยังไม่มีค่าใช้จ่ายส่วนรวม",
        "groupLabel": "(กลุ่ม: {{group}})",
        "unnamed": "ค่าใช้จ่ายไม่มีชื่อ",
        "splitPersonal": "ส่วนตัว",
        "splitPerGroup": "ตามกลุ่ม",
        "splitShared": "ส่วนรวม",
        "paidByOf": "ของ: {{name}}",
        "paidByPay": "จ่ายโดย: {{name}}",
        "paidByNone": "ยังไม่ได้เลือก",
        "personalLabel": "ส่วนตัว",
        "forNPeople": "(สำหรับ {{count}} คน)",
        "options": "ตัวเลือก",
        "edit": "แก้ไข",
        "delete": "ลบ",
        "editExpense": "แก้ไขค่าใช้จ่าย",
        "amount": "จำนวนเงิน",
        "selectCurrency": "เลือกสกุลเงิน",
        "vnd": "VND",
        "exchangeRate": "อัตรา: 1 {{currency}} = {{rate}} VND",
        "errAmount": "กรุณาป้อนจำนวนเงิน > 0",
        "errPayer": "กรุณาเลือกผู้จ่ายเงิน",
        "errCategory": "กรุณาป้อนหมวดหมู่",
        "dateLabel": "วันที่",
        "descLabel": "คำอธิบาย",
        "descPlaceholder": "เช่น ค่าแท็กซี่, อาหารกลางวัน...",
        "payerLabel": "จ่ายโดย",
        "payerPlaceholder": "เลือก",
        "noCompanionWarn": "ยังไม่มีผู้ร่วมเดินทาง เพิ่มเพื่อคำนวณการหารเงิน",
        "personalOwner": "ค่าใช้จ่ายของใคร?",
        "personalPlaceholder": "เลือก (ไม่บังคับ)",
        "advanced": "ขั้นสูง",
        "categoryLabel": "หมวดหมู่",
        "customCatLabel": "หมวดหมู่กำหนดเอง *",
        "customCatPlaceholder": "เช่น ของที่ระลึก",
        "linkTimeline": "เชื่อมโยงกับแผนการเดินทาง",
        "noLink": "ไม่เชื่อมโยง",
        "splitMethod": "วิธีหารค่าใช้จ่าย",
        "splitSharedGroup": "แชร์ในกลุ่ม",
        "splitPersonalSelf": "จ่ายของตัวเอง",
        "allPeople": "ทุกคน",
        "nParticipants": "ผู้เข้าร่วม {{count}} คน",
        "participateAll": "ทั้งหมด",
        "participateN": "{{count}} คน",
        "participate": "ผู้เข้าร่วม",
        "close": "ปิด",
        "reselectAll": "เลือกทั้งหมด",
        "perPerson": "ต่อคน",
        "perGroup": "ต่อครอบครัว",
        "save": "บันทึก",
        "add": "เพิ่ม",
        "toastUpdated": "อัปเดตแล้ว",
        "toastAdded": "เพิ่มแล้ว",
        "noCatYet": "ยังไม่มีหมวดหมู่",
        "noSharedAnalysis": "ไม่มีค่าใช้จ่ายส่วนรวมให้วิเคราะห์",
        "noExpenseAnalysis": "ไม่มีค่าใช้จ่ายให้วิเคราะห์",
        "noExpenseList": "ไม่มีค่าใช้จ่ายในรายการ",
        "noCompanionShared": "ยังไม่มีผู้ร่วมเดินทาง เลือก 'จ่ายของตัวเอง' หรือเสนอให้เพิ่มผู้ร่วมเดินทาง",
        "sharedSuggest": "เสนอให้แชร์ค่าใช้จ่ายและชำระเงินภายหลัง",
        "suggestOption": "ตัวเลือกคำแนะนำ",
        "paidBy": "จ่ายโดย:",
        "savingNew": "กำลังบันทึก...",
        "suggestNew": "คำแนะนำใหม่",
        "savingEdit": "กำลังบันทึก...",
        "suggestEdit": "แก้ไขคำแนะนำ",
        "deletingSugg": "กำลังลบ...",
        "suggestDelete": "ลบคำแนะนำ",
        "splitGroupLabel": "แชร์ในกลุ่ม",
        "personalSelfLabel": "จ่ายของตัวเอง",
        "catTransport": "การเดินทาง",
        "catFlights": "เที่ยวบิน",
        "catFood": "อาหารและเครื่องดื่ม",
        "catAccommodation": "ที่พัก",
        "catTickets": "ตั๋ว/ทัวร์",
        "catShopping": "ช้อปปิ้ง",
        "catEntertainment": "ความบันเทิง",
        "catPreparation": "การเตรียมตัว",
        "catOther": "อื่นๆ",
        "catCustom": "อื่นๆ..."
    },
    "id": {
        "pageTitle": "Pengeluaran",
        "pageSubtitle": "Lacak pengeluaran, pembayaran, dan pembagian.",
        "addExpense": "Tambah",
        "totalTrip": "Total Pengeluaran",
        "sharedTrip": "Pengeluaran Bersama",
        "personalExpense": "Pengeluaran Pribadi",
        "avgPerGroup": "Rata-rata / Grup",
        "avgPerPerson": "Rata-rata / Orang",
        "noCompanion": "Belum ada pendamping",
        "byCategory": "Berdasarkan Kategori",
        "sharePerMember": "Bagian per Orang/Grup",
        "addCompanionStats": "Tambah pendamping untuk melihat statistik.",
        "addCompanionShare": "Tambah pendamping untuk melihat bagian.",
        "expenseList": "Daftar Pengeluaran",
        "noExpenses": "Belum ada pengeluaran",
        "noExpensesDesc": "Catat pengeluaran makan, transportasi, dan tiket.",
        "deleteTitle": "Hapus pengeluaran ini?",
        "deleteDesc": "Pengeluaran ini akan dihapus. Tidak dapat dibatalkan.",
        "deleteConfirm": "Hapus",
        "settlementTitle": "Penyelesaian Tagihan",
        "settlementBalanced": "Semua lunas. Tidak ada yang berhutang.",
        "settlementAddCompanion": "Tambah pendamping untuk menghitung tagihan.",
        "settlementNoExpense": "Belum ada pengeluaran bersama.",
        "groupLabel": "(Grup: {{group}})",
        "unnamed": "Tanpa nama",
        "splitPersonal": "Pribadi",
        "splitPerGroup": "Per Grup",
        "splitShared": "Bersama",
        "paidByOf": "Milik: {{name}}",
        "paidByPay": "Dibayar oleh: {{name}}",
        "paidByNone": "Belum ditentukan",
        "personalLabel": "Pribadi",
        "forNPeople": "(untuk {{count}} orang)",
        "options": "Opsi",
        "edit": "Edit",
        "delete": "Hapus",
        "editExpense": "Edit Pengeluaran",
        "amount": "Jumlah",
        "selectCurrency": "Pilih Mata Uang",
        "vnd": "VND",
        "exchangeRate": "Kurs: 1 {{currency}} = {{rate}} VND",
        "errAmount": "Masukkan jumlah > 0.",
        "errPayer": "Pilih pembayar.",
        "errCategory": "Masukkan kategori.",
        "dateLabel": "Tanggal",
        "descLabel": "Deskripsi",
        "descPlaceholder": "Mis: Taksi, makan siang...",
        "payerLabel": "Dibayar oleh",
        "payerPlaceholder": "Pilih",
        "noCompanionWarn": "Belum ada pendamping. Tambah untuk berbagi.",
        "personalOwner": "Milik siapa ini?",
        "personalPlaceholder": "Pilih (opsional)",
        "advanced": "Lanjutan",
        "categoryLabel": "Kategori",
        "customCatLabel": "Kategori Khusus *",
        "customCatPlaceholder": "Mis: Suvenir",
        "linkTimeline": "Tautkan ke Itinerari",
        "noLink": "Jangan tautkan",
        "splitMethod": "Metode Pembagian",
        "splitSharedGroup": "Berbagi di grup",
        "splitPersonalSelf": "Bayar sendiri",
        "allPeople": "Semua orang",
        "nParticipants": "{{count}} peserta",
        "participateAll": "Semua",
        "participateN": "{{count}} org",
        "participate": "Peserta",
        "close": "Tutup",
        "reselectAll": "Pilih Semua",
        "perPerson": "Per Orang",
        "perGroup": "Per Keluarga",
        "save": "Simpan",
        "add": "Tambah",
        "toastUpdated": "Diperbarui",
        "toastAdded": "Ditambahkan",
        "noCatYet": "Belum ada kategori.",
        "noSharedAnalysis": "Tidak ada pengeluaran bersama untuk dianalisis.",
        "noExpenseAnalysis": "Tidak ada pengeluaran untuk dianalisis.",
        "noExpenseList": "Tidak ada pengeluaran dalam daftar",
        "noCompanionShared": "Belum ada pendamping. Pilih 'Bayar sendiri' atau usulkan pendamping.",
        "sharedSuggest": "Usulkan pembagian biaya secara merata.",
        "suggestOption": "Opsi saran",
        "paidBy": "Dibayar oleh:",
        "savingNew": "Menyimpan...",
        "suggestNew": "Saran baru",
        "savingEdit": "Menyimpan...",
        "suggestEdit": "Edit saran",
        "deletingSugg": "Menghapus...",
        "suggestDelete": "Hapus saran",
        "splitGroupLabel": "Berbagi di grup",
        "personalSelfLabel": "Bayar sendiri",
        "catTransport": "Transportasi",
        "catFlights": "Penerbangan",
        "catFood": "Makanan & Minuman",
        "catAccommodation": "Akomodasi",
        "catTickets": "Tiket/Tur",
        "catShopping": "Belanja",
        "catEntertainment": "Hiburan",
        "catPreparation": "Persiapan",
        "catOther": "Lainnya",
        "catCustom": "Lainnya..."
    }
}

for lang, data_dict in translations.items():
    filepath = f"src/locales/{lang}.json"
    if not os.path.exists(filepath):
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    if "expenses" not in data:
        data["expenses"] = {}
        
    for k, v in data_dict.items():
        data["expenses"][k] = v

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")
