import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import fs from "fs";
import path from "path";

function firebaseSWPlugin() {
  return {
    name: "firebase-sw-plugin",
    configResolved(config: any) {
      const env = config.env;
      const swContent = `// Autogenerated by firebase-sw-plugin in vite.config.ts
importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY || ''}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${env.VITE_FIREBASE_APP_ID || ''}"
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log('[firebase-messaging-sw.js] Background message received:', payload);
  const notificationTitle = payload.notification?.title || 'KAT Journey';
  const notificationOptions = {
    body: payload.notification?.body || '',
    icon: payload.notification?.image || '/asset/icon-192.png',
    badge: '/asset/icon-192.png',
    data: payload.data
  };
  self.registration.showNotification(notificationTitle, notificationOptions);
});
`;
      const destPath = path.resolve(config.publicDir || 'public', "firebase-messaging-sw.js");
      try {
        fs.writeFileSync(destPath, swContent);
      } catch (err) {
        console.error("Failed to generate firebase-messaging-sw.js:", err);
      }
    }
  };
}

export default defineConfig({
  plugins: [
    react(),
    firebaseSWPlugin(),
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: ["asset/favicon.ico", "asset/apple-touch-icon.png"],
      manifest: {
        name: "KAT Journey",
        short_name: "KAT Journey",
        description: "Lên kế hoạch chuyến đi gọn gàng, theo dõi lịch trình, checklist, chi phí và lưu lại kỷ niệm du lịch.",
        theme_color: "#FAF7F1",
        background_color: "#FAF7F1",
        display: "standalone",
        start_url: "/",
        icons: [
          {
            src: "/asset/icon-192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/asset/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/asset/maskable-icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable"
          }
        ]
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 5000000,
        globPatterns: ["**/*.{js,css,html,ico,png,svg}"],
        importScripts: ["/firebase-messaging-sw.js"]
      }
    })
  ],
  esbuild: {
    drop: ['console', 'debugger'],
  },
  build: {
    chunkSizeWarningLimit: 1400,
    rollupOptions: {
      output: {
        manualChunks: {
          react: ["react", "react-dom"],
          firebase: ["firebase/app", "firebase/auth", "firebase/firestore"],
          i18n: ["i18next", "i18next-browser-languagedetector", "react-i18next"],
          documents: ["jspdf", "xlsx", "exceljs"],
          ui: ["@hugeicons/react"],
        },
      },
    },
  }
});
