import { supabase } from '../lib/supabase';
import { db as localDb } from '../db';
import { ChangeRequestSection, ChangeRequestAction } from './sharedTripRequestService';

function getTableName(collectionName: string): string {
  const map: Record<string, string> = {
    members: 'share_members',
    activities: 'share_activities',
    expenses: 'share_expenses',
    checklist: 'share_checklist',
    journals: 'share_journals',
    backupPlans: 'share_backup_plans',
    travelDocuments: 'share_travel_documents'
  };
  return map[collectionName] || `share_${collectionName}`;
}

export async function approveChangeRequest(token: string, requestId: string): Promise<void> {
  const { data: { session } } = await supabase.auth.getSession();
  const user = session?.user;
  if (!user) throw new Error("Vui lòng đăng nhập.");

  // 1. Validate Owner
  const { data: shareData, error: shareError } = await supabase
    .from('public_shares')
    .select('owner_uid, source_trip_id')
    .eq('token', token)
    .maybeSingle();

  if (shareError || !shareData) {
    throw new Error('Link chia sẻ không tồn tại.');
  }

  if (shareData.owner_uid !== user.id) {
    throw new Error('Thiết bị này không còn quyền quản lý link chia sẻ này.');
  }

  // 2. Claim change request atomically by updating its status
  const { data: requestData, error: requestError } = await supabase
    .from('change_requests')
    .update({
      status: 'approved',
      reviewed_by_uid: user.id,
      reviewed_at: new Date().toISOString()
    })
    .eq('id', requestId)
    .eq('share_token', token)
    .in('status', ['pending', 'auto_approved'])
    .select('*')
    .maybeSingle();

  if (requestError || !requestData) {
    throw new Error('Yêu cầu không tồn tại hoặc đã được xử lý trước đó.');
  }

  const tripId = shareData.source_trip_id;
  const trip = await localDb.trips.get(Number(tripId));

  if (!trip) {
    throw new Error('Không tìm thấy chuyến đi gốc trên thiết bị này. Không thể áp dụng thay đổi.');
  }

  const section = requestData.section as ChangeRequestSection;
  const action = requestData.action as ChangeRequestAction;
  const targetId = requestData.target_id;
  const afterData = requestData.after_data;

  // 3. Apply to Dexie
  const dexieTableMap: Record<ChangeRequestSection, any> = {
    activities: localDb.events,
    expenses: localDb.expenses,
    checklist: localDb.checklist,
    journals: localDb.journals,
    backupPlans: localDb.backupPlans,
    travelDocuments: localDb.travelDocuments,
    members: localDb.members
  };

  const localTable = dexieTableMap[section];
  let dexieId: number | string | undefined;

  try {
    if (action === 'create') {
      const newItem = { ...afterData, tripId: Number(tripId) };
      delete newItem.id; // ensure ID is auto-generated by Dexie
      dexieId = await localTable.add(newItem);
    } else if (action === 'update' && targetId) {
      dexieId = Number(targetId) || targetId;
      await localTable.update(dexieId, afterData);
    } else if (action === 'delete' && targetId) {
      dexieId = Number(targetId) || targetId;
      await localTable.delete(dexieId);
    }
  } catch (err: any) {
    throw new Error('Lỗi khi cập nhật dữ liệu gốc: ' + err.message);
  }

  // 4. Apply to Supabase Public Snapshot
  try {
    const table = getTableName(section);
    const docId = action === 'create' ? String(dexieId) : String(targetId);
    
    if (action === 'create') {
      const now = new Date().toISOString();
      await supabase
        .from(table)
        .insert({
          id: docId,
          share_token: token,
          data: { ...afterData, id: dexieId, tripId: 0 },
          created_at: now,
          updated_at: now,
          created_by_uid: user.id,
          updated_by_uid: user.id
        });
    } else if (action === 'update') {
      await supabase
        .from(table)
        .update({
          data: afterData,
          updated_at: new Date().toISOString(),
          updated_by_uid: user.id
        })
        .eq('share_token', token)
        .eq('id', docId);
    } else if (action === 'delete') {
      await supabase
        .from(table)
        .delete()
        .eq('share_token', token)
        .eq('id', docId);
    }
  } catch (err: any) {
    throw new Error('Lỗi khi đồng bộ lên Supabase: ' + err.message);
  }
}

export async function rejectChangeRequest(token: string, requestId: string): Promise<void> {
  const { data: { session } } = await supabase.auth.getSession();
  const user = session?.user;
  if (!user) throw new Error("Vui lòng đăng nhập.");

  const { data: shareData, error: shareError } = await supabase
    .from('public_shares')
    .select('owner_uid')
    .eq('token', token)
    .maybeSingle();

  if (shareError || !shareData || shareData.owner_uid !== user.id) {
    throw new Error('Thiết bị này không còn quyền quản lý link chia sẻ này.');
  }

  const { error } = await supabase
    .from('change_requests')
    .update({
      status: 'rejected',
      reviewed_at: new Date().toISOString(),
      reviewed_by_uid: user.id
    })
    .eq('id', requestId)
    .eq('share_token', token);

  if (error) {
    throw new Error("Không thể từ chối yêu cầu: " + error.message);
  }
}
