import { ensureCloudShareReady } from './cloudShareService';
import { initFirebase, ensureAnonymousUser } from '../lib/firebase';
import { db as localDb } from '../db';
import { ChangeRequestSection, ChangeRequestAction } from './sharedTripRequestService';

export async function approveChangeRequest(token: string, requestId: string): Promise<void> {
  await ensureCloudShareReady();
  const user = await ensureAnonymousUser();
  const { db } = await initFirebase();
  const { doc, getDoc, updateDoc, setDoc, deleteDoc, serverTimestamp } = await import('firebase/firestore');

  const shareRef = doc(db, 'publicShares', token);
  const shareSnap = await getDoc(shareRef);

  if (!shareSnap.exists()) {
    throw new Error('Link chia sẻ không tồn tại.');
  }

  const shareData = shareSnap.data();

  if (shareData.ownerUid !== user.uid) {
    throw new Error('Thiết bị này không còn quyền quản lý link chia sẻ này.');
  }

  const requestRef = doc(shareRef, 'changeRequests', requestId);
  const requestSnap = await getDoc(requestRef);

  if (!requestSnap.exists()) {
    throw new Error('Yêu cầu không tồn tại.');
  }

  const requestData = requestSnap.data();

  if (requestData.status !== 'pending') {
    throw new Error('Yêu cầu đã được xử lý.');
  }

  const tripId = shareData.sourceTripId;
  const trip = await localDb.trips.get(Number(tripId));

  if (!trip) {
    throw new Error('Không tìm thấy chuyến đi gốc trên thiết bị này. Không thể áp dụng thay đổi.');
  }

  const section = requestData.section as ChangeRequestSection;
  const action = requestData.action as ChangeRequestAction;
  const targetId = requestData.targetId;
  const afterData = requestData.after;

  // 1. Apply to Dexie
  const dexieTableMap: Record<ChangeRequestSection, any> = {
    activities: localDb.events,
    expenses: localDb.expenses,
    checklist: localDb.checklist,
    journals: localDb.journals,
    backupPlans: localDb.backupPlans,
    travelDocuments: localDb.travelDocuments
  };

  const table = dexieTableMap[section];
  let dexieId: number | string | undefined;

  try {
    if (action === 'create') {
      const newItem = { ...afterData, tripId: Number(tripId) };
      delete newItem.id; // ensure ID is auto-generated by Dexie
      dexieId = await table.add(newItem);
    } else if (action === 'update' && targetId) {
      dexieId = Number(targetId) || targetId;
      await table.update(dexieId, afterData);
    } else if (action === 'delete' && targetId) {
      dexieId = Number(targetId) || targetId;
      await table.delete(dexieId);
    }
  } catch (err: any) {
    throw new Error('Lỗi khi cập nhật dữ liệu gốc: ' + err.message);
  }

  // 2. Apply to Firebase Public Snapshot
  try {
    const subcollectionRef = doc(shareRef, section, action === 'create' ? String(dexieId) : String(targetId));
    
    if (action === 'create') {
      await setDoc(subcollectionRef, { ...afterData, id: dexieId, tripId: 0 });
    } else if (action === 'update') {
      await updateDoc(subcollectionRef, afterData);
    } else if (action === 'delete') {
      await deleteDoc(subcollectionRef);
    }
  } catch (err: any) {
    throw new Error('Lỗi khi đồng bộ lên Firebase: ' + err.message);
  }

  // 3. Mark as approved
  await updateDoc(requestRef, {
    status: 'approved',
    reviewedAt: serverTimestamp(),
    reviewedByUid: user.uid
  });
}

export async function rejectChangeRequest(token: string, requestId: string): Promise<void> {
  await ensureCloudShareReady();
  const user = await ensureAnonymousUser();
  const { db } = await initFirebase();
  const { doc, getDoc, updateDoc, serverTimestamp } = await import('firebase/firestore');

  const shareRef = doc(db, 'publicShares', token);
  const shareSnap = await getDoc(shareRef);

  if (!shareSnap.exists() || shareSnap.data().ownerUid !== user.uid) {
    throw new Error('Thiết bị này không còn quyền quản lý link chia sẻ này.');
  }

  const requestRef = doc(shareRef, 'changeRequests', requestId);
  await updateDoc(requestRef, {
    status: 'rejected',
    reviewedAt: serverTimestamp(),
    reviewedByUid: user.uid
  });
}
